components:
  responses:
    create_service_account_response:
      content:
        application/json:
          schema:
            allOf:
            - example:
                id: 2f56a901-4b71-45dc-a8d6-6b77eb41934d
                name: api-client
                tsg_id: '1746292031'
                contact_email: user@example.com
                description: A client for our dashboard
                client_id: api-client@1746292031.iam.panserviceaccount.com
                client_secret: f9zGQfSAj7GjGbX6dvTV3
      description: Successful response.
  schemas:
    service_account_create:
      title: Root Type for service_account
      type: object
      properties:
        name:
          description: 'The [role](/sase/docs/all-roles) that you want to grant to
            this service account.

            This parameter is required.

            '
          type: string
        contact_email:
          description: 'Email address of the person or group that is managing this
            service account.

            '
          type: string
        description:
          description: 'A description for this service account.

            '
      example:
        name: api-client
        contact_email: user@example.com
        description: A client for our dashboard
    service_account_update:
      title: Update Type for service_account
      type: object
      properties:
        contact_email:
          description: 'Email address of the person or group that is managing this
            service account.

            '
          type: string
        description:
          description: 'A description for this service account.

            '
      example:
        contact_email: user@example.com
        description: A client for our dashboard
    service_account:
      title: Root Type for service_account
      type: object
      properties:
        id:
          type: string
          description: 'Unique ID for this service account.

            '
        name:
          type: string
          description: 'Service account''s name.

            '
        tsg_id:
          type: string
          description: 'Service account''s tenant service group ID.

            '
        contact_email:
          description: 'Email address for the user or group managing this service
            account.

            '
          type: string
        description:
          description: 'Service account''s description.

            '
        client_id:
          description: 'Service account''s client ID, formatted as an email address.

            '
          type: string
      example:
        id: 72caf04d-cd05-4207-921e-e673b9c0b423
        name: api-client
        tsg_id: '1746292031'
        contact_email: user@example.com
        description: A client for our dashboard
        client_id: api-client@1746292031.iam.panserviceaccount.com
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
openapi: 3.0.2
paths:
  /iam/v1/service_accounts:
    post:
      requestBody:
        description: A new `service_account` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/service_account_create'
        required: true
      tags:
      - ServiceAccounts
      responses:
        '201':
          $ref: '#/components/responses/create_service_account_response'
          description: Successful response.
      operationId: createservice_account
      summary: Create a service account
      description: 'Create a service account.

        '
      parameters: []
      security:
      - Bearer: []
    get:
      tags:
      - ServiceAccounts
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/service_account'
          description: Successful response - returns an array of `service_account`
            entities.
      operationId: getservice_accounts
      summary: List all service accounts
      description: 'List all service accounts.

        '
      parameters: []
      security:
      - Bearer: []
  /iam/v1/service_accounts/{id}:
    get:
      tags:
      - ServiceAccounts
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_account'
          description: Successful response - returns a single `service_account`.
      operationId: getservice_account
      summary: Get a service account
      description: 'Get a specific service account.

        '
      parameters:
      - name: id
        description: A unique identifier for a `service_account`.
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
    put:
      requestBody:
        description: Updated `service_account` information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/service_account_update'
        required: true
      tags:
      - ServiceAccounts
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_account'
          description: Successful response.
      operationId: updateservice_account
      summary: Update a service account
      description: 'Update a service account.

        '
      parameters:
      - name: id
        description: A unique identifier for a `service_account`.
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
    delete:
      tags:
      - ServiceAccounts
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_account'
          description: Successful response.
      operationId: deleteservice_account
      summary: Delete a service account
      description: 'Delete a service account.

        '
      parameters:
      - name: id
        description: A unique identifier for a `service_account`.
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
  /iam/v1/service_accounts/{id}/operations/reset:
    post:
      tags:
      - ServiceAccounts
      responses:
        '201':
          $ref: '#/components/responses/create_service_account_response'
          description: Successful response.
      operationId: resetservice_account
      summary: Reset a service account
      description: 'Reset a service account.

        '
      parameters:
      - name: id
        description: A unique identifier for a `service_account`.
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
info:
  title: Service Accounts
  version: '1.0'
  description: 'Service account description.

    '
  contact: {}
tags:
- name: ServiceAccounts
servers:
- url: https://api.sase.paloaltonetworks.com
