components:
  schemas:
    user_register:
      description: ''
      properties:
        email:
          description: 'The email address that you want to use to create this user.

            This email address should correspond to an email address

            used to register a user with Palo Alto Networks customer support.

            '
          example: someemail33@somedomain.com
          type: string
        firstname:
          description: 'The user''s familiar name.

            '
          example: John
          type: string
        lastname:
          description: 'The user''s surname, or family name.

            '
          example: Smith
          type: string
      required:
      - email
      - firstname
      - lastname
      title: Root Type for user_register
      type: object
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
info:
  contact: {}
  description: 'Create and verify IAM user accounts. The email address used for these
    user accounts

    must correspond to a Palo Alto Networks Customer Support account.

    '
  title: User Accounts
  version: '1.0'
openapi: 3.0.2
paths:
  /iam/v1/sso_users:
    get:
      description: "Verify that the IAM user account, as identified by an email address,\
        \ corresponds \nto a Palo Alto Networks support account.\n"
      operationId: get-iam-v1-sso_users
      parameters:
      - description: 'The email address used to identify the user account that you
          want to verify.

          '
        in: query
        name: email
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                Profile Exists:
                  value:
                    profile_exists: true
          description: Successful response - user registered for SSO
      security:
      - Bearer: []
      summary: Verify a user account
      tags:
      - UserAccounts
    post:
      description: "Create a new IAM user account. Use\n[verify a user account](/sase/api/iam/ssousers#operation/get-sso_users)\
        \ \nto ensure that the email address used for this user account\ncorresponds\
        \ to an Palo Alto Networks support account.\n"
      operationId: post-iam-v1-sso_users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_register'
        required: true
      responses:
        '200':
          content:
            application/json: {}
          description: Successful response - user registered for SSO
      security:
      - Bearer: []
      summary: Create a user account
      tags:
      - UserAccounts
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: UserAccounts
