info:
  description: |
    The Advanced Threat Prevention API endpoints require an active subscription to the Advanced Threat Prevention security service. These endpoints can only be accessed using the API key associated with the account that holds the subscription. Attempting to view an unauthorized report ID will not return any results.

    List of Advanced Threat Prevention API endpoints:
    1. Link to [Retrieve Advanced Threat Prevention cloud analysis report](advanced-threat-prevention-api-endpoints#operation/post_atp_reports_batch_mode)
    2. Link to [Retrieve the Advanced Threat Prevention cloud analysis report PCAP](advanced-threat-prevention-api-endpoints#operation/get_atp_pcaps)
  title: Advanced Threat Prevention API Overview
  version: v1.0-BETA
  contact:
    email: tp-infra@paloaltonetworks.com
openapi: 3.0.1
servers:
  - url: "https://api.threatvault.paloaltonetworks.com/service/v1"
    description: The base URI
tags:
  - description: Advanced Threat Prevention API endpoints are listed below. These APIs are currently in BETA. Please contact your Palo Alto Networks salesperson for more information.
    name: Advanced Threat Prevention API Endpoints

paths:
  /atp/reports:
    post:
      operationId: post_atp_reports_batch_mode
      description: A POST request to retrieve a single (or multiple) unique, automatically generated report, based on the analysis details provided by Advanced Threat Prevention for a specific threat. This includes contextual data specific to your network by providing various session data, transaction info, and malware details. User must provide **one or more** report IDs in request body.
      security:
        - X-TV-API-KEY: []
      summary: Get ATP reports
      tags:
        - Advanced Threat Prevention API Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: array
                  items:
                    type: string
              example:
                id:
                  [
                    "c25b5d86d8ac77e10376000517491157a07ac008bfc799f08795d59c57e23a50",
                    "a23b5d46d6ac77e70376080517991187a07ac008bfc799f08795d59c57e23a50",
                  ]
      responses:
        $ref: "api/responses/post-atp-batch-mode.yaml#/responses"

  /atp/reports/pcaps:
    get:
      operationId: get_atp_pcaps
      description: A GET request to retrieve the raw payload associated with the report ID as a PCAP.
      security:
        - X-TV-API-KEY: []
      summary: Get ATP cloud report PCAP
      tags:
        - Advanced Threat Prevention API Endpoints
      parameters:
        $ref: "api/requests/get-atp-pcap.yaml#/parameters"
      responses:
        $ref: "api/responses/get-atp-pcap.yaml#/responses"

components:
  securitySchemes:
    $ref: "components/securitySchemes.yaml#/securitySchemes"
