info:
  description: |
    The Threat Prevention API endpoints are available to customers with an active Threat Prevention or Advanced Threat Prevention subscription.

    List of Threat Prevention API endpoints:
    1. Link to [Retrieve IPS Threat Metadata](threat-prevention-public-api-endpoints#operation/threats)
    2. Link to [Retrieve Release-Note Information](threat-prevention-public-api-endpoints#operation/release_notes)
  title: Threat Prevention API Overview
  version: v1.0-BETA
  contact:
    email: tp-infra@paloaltonetworks.com
openapi: 3.0.0
servers:
  - url: "https://api.threatvault.paloaltonetworks.com/service/v1"
    description: The base URI
tags:
  - description: Threat Prevention API endpoints are listed below. These APIs are currently in BETA. Please contact your Palo Alto Networks salesperson for more information.
    name: Threat Prevention API Endpoints

paths:
  /threats:
    get:
      operationId: threats
      description: A GET request to retrieve threat signature metadata. Palo Alto Networks provides a unique threat signature ID number based on the signature category as managed by the firewall - anti-spyware, vulnerability, and file-format.
      security:
        - X-TV-API-KEY: []
      summary: Get Threat Metadata
      tags:
        - Threat Prevention API Endpoints
      parameters:
        $ref: "api/requests/get-threats.yaml#/parameters"
      responses:
        $ref: "api/responses/get-threats.yaml#/responses"

  /release-notes:
    get:
      operationId: release_notes
      description: A GET request to retrieve Applications and Threats content update release note information. The includes details about new and modified threat signatures, updates to App-IDs and HTTP decoders as well as descriptions about other changes introduced in the specified release.
      security:
        - X-TV-API-KEY: []
      summary: Get Content Release Notes
      tags:
        - Threat Prevention API Endpoints
      parameters:
        $ref: "api/requests/get-release-notes.yaml#/parameters"
      responses:
        $ref: "api/responses/get-release-notes.yaml#/responses"

components:
  securitySchemes:
    $ref: "components/securitySchemes.yaml#/securitySchemes"
