components:
  schemas:
    Aggregate:
      properties:
        data:
          description: Data
          items:
            $ref: '#/components/schemas/AggregateData'
          type: array
        field:
          description: Field
          type: string
        name:
          description: Name
          type: string
        operator:
          description: Operator
          enum:
          - max
          - count
          - min
          - avg
          - sum
          type: string
        statistic:
          description: Statistic
          type: string
        unit:
          description: Unit
          type: string
    AggregateData:
      properties:
        value:
          description: 'Value: JsonInclude(content = ALWAYS, contentFilter = classOf[Void],
            value = ALWAYS, valueFilter = classOf[Void]) '
          type: number
        view:
          type: object
    DemSiteConfig:
      properties:
        adem_enabled:
          description: Adem Enabled
          type: boolean
        id:
          description: Id
          type: string
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    DemSiteConfigQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: Aggregate
        dest_page:
          description: Dest Page
          format: int32
          type: integer
        getDeleted:
          description: GetDeleted
          type: boolean
        group_by:
          description: Group By
          items:
            description: Group By
            type: string
          type: array
        id:
          description: Id
          type: string
        isReadPreferenceSecondary:
          description: 'IsReadPreferenceSecondary: JsonIgnore(value = true) '
          type: boolean
        last_query_ts:
          description: Last Query Ts
          format: int64
          type: integer
        limit:
          description: Limit
          format: int32
          type: integer
        next_query:
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: Retrieved Fields
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: Retrieved Fields Mask
          type: boolean
        sort_case_insensitive:
          description: Sort Case Insensitive
          type: boolean
        sort_params:
          type: object
        total_count:
          description: Total Count
          format: int64
          type: integer
    DemSiteConfigQueryFilter:
      properties:
        adem_enabled:
          description: Adem Enabled
          type: boolean
        id:
          description: Id
          type: string
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    DemSiteConfigScreen:
      properties:
        adem_enabled:
          description: Adem Enabled
          type: boolean
        id:
          description: Id
          type: string
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    DemStatus:
      properties:
        dem_enabled:
          description: Dem Enabled
          type: boolean
        id:
          description: Id
          type: string
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    DemStatusQueryResponse:
      properties:
        dem_enabled:
          description: 'Indicates whether ADEM is enabled for your instance.

            '
          type: boolean
        id:
          description: 'ID of the DEM instance.

            '
          type: string
        site_id:
          description: 'Site Id: Digits(fraction = 0, integer = 50, SITEID_INVALID)
            NotNull '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          format: int32
          type: integer
        deleted_count:
          format: int64
          type: integer
        deleted_ids:
          items:
            type: string
          type: array
        id:
          type: string
        next_query:
          type: object
        tenant_id:
          type: string
        total_count:
          format: int64
          type: integer
      type: object
    ListResponse:
      properties:
        count:
          format: int32
          type: integer
        id:
          type: string
        tenant_id:
          type: string
      type: object
info:
  contact: {}
  description: List of APIs used to retrieve the Autonomous DEM status in Prisma SD-WAN.
  title: ADEM
  version: Latest
openapi: 3.0.0
paths:
  /v2.0/api/tenants/{tenant_id}/demsiteconfigs/query:
    post:
      description: Queries db for Dem site config that match query params.
      operationId: post-v2.0-api-tenants-tenant_id-demsiteconfigs-query
      parameters:
      - description: Tenant Id
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemSiteConfigQuery'
        description: Query Details for Dem site configs
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemSiteConfigQueryFilter'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: BAD_QUERY_REQUEST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Queries db for Dem site config that match query params. (v2.0)
      tags:
      - ADEM
  /v2.0/api/tenants/{tenant_id}/demstatus/query:
    post:
      description: 'Query the status of your ADEM instance.

        '
      operationId: post-v2.0-api-tenants-tenant_id-demstatus-query
      parameters:
      - description: The unique tenant ID.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemStatusQueryResponse'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemStatusQueryResponse'
                      type: array
                  type: object
          description: Successful operation
      summary: Query ADEM Status
      tags:
      - ADEM
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/demsiteconfigs:
    get:
      description: Get all ADEM status for a site
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-demsiteconfigs
      parameters:
      - description: Tenant Id
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemSiteConfig'
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get all ADEM status for a site (v2.0)
      tags:
      - ADEM
    post:
      description: Create dem site config API
      operationId: post-v2.0-api-tenants-tenant_id-sites-site_id-demsiteconfigs
      parameters:
      - description: Tenant ID
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site ID
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemSiteConfigScreen'
        description: Details of the Dem site config to be created
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemSiteConfig'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: DEM_SITE_CONFIG_NOT_SUPPORTED_FOR_HUB
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create dem site config (v2.0)
      tags:
      - ADEM
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/demsiteconfigs/{config_id}:
    delete:
      description: Delete device id Start Network Node config API
      operationId: delete-v2.0-api-tenants-tenant_id-sites-site_id-demsiteconfigs-config_id
      parameters:
      - description: Tenant ID
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site ID
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Dem site config ID
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemSiteConfig'
          description: Successful Operation
      summary: Delete Start Network Node config (v2.0)
      tags:
      - ADEM
    get:
      description: Get dem site configs API for a particular config entry
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-demsiteconfigs-config_id
      parameters:
      - description: Tenant ID
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site ID
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Dem Site Config ID
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemSiteConfig'
          description: Successful Operation
      summary: Get dem site config (v2.0)
      tags:
      - ADEM
    put:
      description: Update dem site config API
      operationId: put-v2.0-api-tenants-tenant_id-sites-site_id-demsiteconfigs-config_id
      parameters:
      - description: Tenant ID
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site ID
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: dem site Config ID
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemSiteConfigScreen'
        description: Details of the dem site config to be updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemSiteConfig'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: DEM_SITE_CONFIG_NOT_SUPPORTED_FOR_HUB
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update dem site config (v2.0)
      tags:
      - ADEM
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/demstatus:
    get:
      description: 'Get all ADEM status for a site.

        '
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-demstatus
      parameters:
      - description: Tenant Id
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemStatus'
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get ADEM Status
      tags:
      - ADEM
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/demstatus/{dem_status_id}:
    get:
      description: 'Get ADEM status for a site in Prisma SD-WAN.

        '
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-demstatus-dem_status_id
      parameters:
      - description: Tenant Id
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: Site Id
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Site Id
        in: path
        name: dem_status_id
        required: true
        schema:
          description: Dem Status Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemStatus'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get ADEM Status for a Site
      tags:
      - ADEM
servers:
- url: https://api.us.cloudgenix.com
tags:
- name: ADEM
