components:
  schemas:
    BulkResponse:
      properties:
        count:
          description: 'The total number of responses.

            '
          format: int32
          type: integer
        id:
          description: 'The ID of the response.

            '
          type: string
        type:
          description: "The type of response. \n"
          type: string
    ElementNTP:
      properties:
        description:
          description: 'The description of the Network Time Protocol (NTP) configuration.
            Max characters = 256.

            '
        id:
          description: 'The ID of the NTP configuration.

            '
          type: string
        name:
          description: 'The name of the NTP configuration. Max characters = 128.

            '
          type: string
        ntp_servers:
          description: 'The configured NTP servers. A minimum of 1 and a maximum of
            10 NTP servers can be configured.

            '
          items:
            $ref: '#/components/schemas/NTPServer'
          type: array
        source_interface_ids:
          description: 'The interface used for sending a request to an NTP server.
            A source interface can include PPPoE or sub-interfaces with IP addresses.
            Up to 10 source interfaces are supported.

            '
          items:
            description: Source Interface Ids
            type: string
          type: array
        tags:
          description: "A information field that can be added to identify the NTP\
            \ configuration. \n"
          items:
            description: Tags
            type: string
          type: array
      required:
      - ntp_servers
      - name
    ElementNTPState:
      properties:
        cts:
          $ref: '#/components/schemas/NTPServerState'
          description: 'The Controller Time Source (CTS) used as a system fail-safe
            in cases where there is no time source.

            '
        description:
          description: 'The description of the Network Time Protocol (NTP) configuration.
            Max characters = 256.

            '
        disabled:
          description: 'Indicates if the NTP configuration is disabled.

            '
          type: boolean
        disabled_reason:
          description: 'The reason for the NTP configuration to be disabled.

            '
          type: string
        element_id:
          description: "The ID of the element. \n"
          type: string
        id:
          description: 'The ID of the NTP configuration.

            '
          type: string
        inactive:
          description: 'Indicates if the NTP configuration is inactive.

            '
          type: boolean
        inactive_reason:
          description: 'The reason for the NTP configuration to be inactive.

            '
          type: string
        name:
          description: 'The name of the NTP configuration. Max characters = 128.

            '
          type: string
        ntp_hash:
          description: 'NTP hash. Values True or False.

            '
          format: int32
          type: integer
        ntp_id:
          description: "The ID of the NTP configuration. \n"
          type: string
        ntp_servers:
          description: 'The configured NTP servers. A minimum of 1 and a maximum of
            10 NTP servers can be configured.

            '
          items:
            $ref: '#/components/schemas/NTPServerState'
          type: array
        region:
          description: 'The region where the element is configured for NTP.

            '
          type: string
        source_interface_ids:
          description: 'The interface used for sending a request to an NTP server.
            A source interface can include PPPoE or sub-interfaces with IP addresses.
            Up to 10 source interfaces are supported.

            '
          items:
            description: Source Interface Ids
            type: string
          type: array
        tags:
          description: "A information field that can be added to identify the NTP\
            \ configuration. \n"
          items:
            description: Tags
            type: string
          type: array
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001)
            NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - tenant_id
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    NTPServer:
      properties:
        host:
          description: 'The host IP address or domain name.

            '
          type: string
        max_poll:
          description: 'The maximum polling interval. It specifies the polling intervals
            for NTP messages in seconds as a power of two.The values of Max Poll can
            be set between 4 and 17.

            '
          format: int32
          type: integer
        min_poll:
          description: 'The minimum polling interval. It specifies the polling intervals
            for NTP messages in seconds as a power of two.The values of Min Poll can
            be set between 4 and 17.

            '
          format: int32
          type: integer
        version:
          description: 'The version of the NTP configuration. NTP versions 2, 3 and
            4 are supported.

            '
          format: int32
          type: integer
      required:
      - max_poll
      - min_poll
      - version
      - host
    NTPServerError:
      properties:
        message:
          description: 'The error message.

            '
          type: string
        time_stamp:
          description: 'Time the error occurred.

            '
          type: string
    NTPServerState:
      properties:
        host:
          description: 'The host IP address or domain name.

            '
          type: string
        last_error:
          $ref: '#/components/schemas/NTPServerError'
          description: 'The last error displayed.

            '
        last_polled:
          description: "The last polling interval. \n"
          type: string
        last_selected:
          $ref: '#/components/schemas/NtpLastSelected'
          description: 'The last selected polling interval.

            '
    NTPTemplate:
      properties:
        default_template:
          description: 'The default NTP template.

            '
          type: boolean
        description:
          description: 'The description of the Network Time Protocol (NTP) configuration.
            Max characters = 256.

            '
        id:
          description: 'The ID of the NTP configuration template.

            '
          type: string
        name:
          description: 'The name of the NTP configuration. Max characters = 128.

            '
          type: string
        ntp_servers:
          description: "The configured NTP servers. A minimum of 1 and a maximum of\
            \ 10 NTP servers can be configured. \n"
          items:
            $ref: '#/components/schemas/NTPServer'
          type: array
        tags:
          description: 'A information field that can be added to identify the NTP
            configuration.

            '
          items:
            description: Tags
            type: string
          type: array
      required:
      - ntp_servers
      - name
    NtpLastSelected:
      properties:
        delta:
          description: 'The delta of the last selected polling interval.

            '
          format: float
          type: number
        error:
          description: 'The error message.

            '
          type: string
        ip:
          description: 'The host IP address or domain name.

            '
          type: string
        old_drift:
          description: 'The old value in the drift file.

            '
          format: float
          type: number
        slop:
          description: "The slop value. \n"
          format: float
          type: number
        stratum:
          description: 'The stratum time.

            '
          format: int32
          type: integer
        time_stamp:
          description: 'The time stamp of the polling interval.

            '
          type: string
        update_after:
          description: 'The polling interval post update.

            '
          type: string
        update_before:
          description: 'The polling interval before update.

            '
          type: string
        update_drift:
          description: 'The updated value in the drift file.

            '
          format: float
          type: number
info:
  contact: {}
  description: List of APIs used to manage NTP.
  title: NTP
  version: Latest
openapi: 3.0.0
paths:
  /v2.0/api/tenants/{tenant_id}/elements/{element_id}/ntp:
    get:
      description: List all the elements with NTP configured.
      operationId: get-v2.0-api-tenants-tenant_id-elements-element_id-ntp
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: ID of the element.
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/ElementNTP'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get Element NTP (v2.0)
      tags:
      - NTP
  /v2.0/api/tenants/{tenant_id}/elements/{element_id}/ntp/{ntp_id}:
    get:
      description: List a specific element with NTP configured.
      operationId: get-v2.0-api-tenants-tenant_id-elements-element_id-ntp-ntp_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: ID of the element.
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTP'
          description: Successful Operation
      summary: Get Specific Element NTP (v2.0)
      tags:
      - NTP
    put:
      description: Update an existing element NTP.
      operationId: put-v2.0-api-tenants-tenant_id-elements-element_id-ntp-ntp_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: ID of the element.
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElementNTP'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTP'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: NTP_CONFIG_UNSUPPORTED_SWVERSION
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: NTP_CONFIG_INVALID_INTERFACE_IDS
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update Element NTP (v2.0)
      tags:
      - NTP
  /v2.0/api/tenants/{tenant_id}/elements/{element_id}/ntp/{ntp_id}/status:
    get:
      description: List a specific element NTP status.
      operationId: get-v2.0-api-tenants-tenant_id-elements-element_id-ntp-ntp_id-status
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: ID of the element.
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTPState'
          description: Successful Operation
      summary: Get Specific Element NTP Status (v2.0)
      tags:
      - NTP
  /v2.0/api/tenants/{tenant_id}/templates/ntp:
    get:
      description: List all the existing NTP Templates of a tenant.
      operationId: get-v2.0-api-tenants-tenant_id-templates-ntp
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/NTPTemplate'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get NTP Templates of Tenant (v2.0)
      tags:
      - NTP
    post:
      description: Create a new NTP template.
      operationId: post-v2.0-api-tenants-tenant_id-templates-ntp
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NTPTemplate'
        description: Details of the NTP template to be created
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: NTP_CONFIG_DUPLICATE_DEFAULT_TEMPLATE
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create NTP Template (v2.0)
      tags:
      - NTP
  /v2.0/api/tenants/{tenant_id}/templates/ntp/{ntp_id}:
    delete:
      description: Delete an existing NTP template.
      operationId: delete-v2.0-api-tenants-tenant_id-templates-ntp-ntp_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '203':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful operation
      summary: Delete NTP Template (v2.0)
      tags:
      - NTP
    get:
      description: Get an existing NTP template.
      operationId: get-v2.0-api-tenants-tenant_id-templates-ntp-ntp_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
      summary: Get NTP Template (v2.0)
      tags:
      - NTP
    put:
      description: Update an existing NTP template.
      operationId: put-v2.0-api-tenants-tenant_id-templates-ntp-ntp_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The NTP configuration ID.
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NTPTemplate'
        description: Details of the NTP template to be updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: NTP_CONFIG_DUPLICATE_DEFAULT_TEMPLATE
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update NTP Template (v2.0)
      tags:
      - NTP
servers:
- url: https://api.us.cloudgenix.com
tags:
- name: NTP
