components:
  schemas:
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The count of the query list.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number of queries.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted query IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        tenant_id:
          description: 'The tenant ID.

            '
          type: string
        total_count:
          description: 'Total number of queries.

            '
          format: int64
          type: integer
      type: object
    PrismaAccessConfig:
      properties:
        id:
          description: 'The ID of the prisma access configs.

            '
          type: string
        remote_networks:
          description: 'The details of the prisma access configuration remote networks.

            '
          items:
            $ref: '#/components/schemas/RemoteNetwork'
          type: array
        site_id:
          description: 'The site ID of the prisma access configs.

            '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    PrismaAccessConfigQueryResponse:
      properties:
        id:
          description: 'The ID of the prisma access configs.

            '
          type: string
        remote_networks:
          description: 'The details of the prisma access configuration remote networks.

            '
          items:
            $ref: '#/components/schemas/RemoteNetwork'
          type: array
        site_id:
          description: 'The site ID of the prisma access configs.

            '
          type: string
        tenant_id:
          description: 'Tenant Id: NotNull Digits(fraction = 0, integer = 20, TENANT_ID_INVALID_0001) '
          type: string
      required:
      - site_id
      - tenant_id
    RemoteNetwork:
      properties:
        remote_network_names:
          description: 'The names of the remote networks.

            '
          items:
            description: Remote Network Names
            type: string
          type: array
        spn_name:
          description: 'The SPN (Security Processing Name) of the prisma access config.

            '
          type: string
      required:
      - spn_name
info:
  contact: {}
  description: No description available.
  title: Prisma Access Configs
  version: Latest
openapi: 3.0.0
paths:
  /v2.0/api/tenants/{tenant_id}/prismaaccess_configs/query:
    post:
      description: Query the Prisma Access configurations.
      operationId: post-v2.0-api-tenants-tenant_id-prismaaccess_configs-query
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfigQueryResponse'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/PrismaAccessConfigQueryResponse'
                      type: array
                  type: object
          description: Successful operation
      summary: Query Prisma Access Configs (v2.0)
      tags:
      - Prisma Access Configs
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/prismaaccess_configs:
    get:
      description: List all all Prisma Access configurations for a site.
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-prismaaccess_configs
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/PrismaAccessConfig'
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get Prisma Access Configs for a Site (v2.0)
      tags:
      - Prisma Access Configs
    post:
      description: Create a Prisma Access configuration with remote networks and the
        security processing node.
      operationId: post-v2.0-api-tenants-tenant_id-sites-site_id-prismaaccess_configs
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfig'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: DEM_PA_CONFIG_EXISTS
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create Prisma Access Config with Remote Networks (v2.0)
      tags:
      - Prisma Access Configs
  /v2.0/api/tenants/{tenant_id}/sites/{site_id}/prismaaccess_configs/{config_id}:
    delete:
      description: Delete a Prisma Access configuration with remote networks and the
        security processing node.
      operationId: delete-v2.0-api-tenants-tenant_id-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: INVALID_REQUEST_DUPLICATE_KEY
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Delete Prisma Access Config with Remote Networks (v2.0)
      tags:
      - Prisma Access Configs
    get:
      description: List the Prisma Access configurations for a site.
      operationId: get-v2.0-api-tenants-tenant_id-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get Prisma Access Configs for a Site (v2.0)
      tags:
      - Prisma Access Configs
    put:
      description: Update a Prisma Access configuration with remote networks and security
        processing node.
      operationId: put-v2.0-api-tenants-tenant_id-sites-site_id-prismaaccess_configs-config_id
      parameters:
      - description: ID of the tenant.
        in: path
        name: tenant_id
        required: true
        schema:
          description: Tenant Id
          type: string
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: The ID of the prisma access config.
        in: path
        name: config_id
        required: true
        schema:
          description: Config Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrismaAccessConfig'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrismaAccessConfig'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_INPUT
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: SITE_NOT_FOUND
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: INVALID_REQUEST_DUPLICATE_KEY
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update Prisma Access Config with Remote Networks (v2.0)
      tags:
      - Prisma Access Configs
servers:
- url: https://api.us.cloudgenix.com
tags:
- name: Prisma Access Configs
