components:
  schemas:
    FolderScreen:
      properties:
        dest_page: {description: 'The destination page.

            ', format: int32, type: integer}
        folder: {description: 'The requested folder name.

            ', type: string}
        id: {description: 'The ID.

            ', type: string}
        limit: {description: 'The requested pagination limit.

            ', format: int32, type: integer}
    ListResponse:
      properties:
        count: {description: 'The actual count.

            ', format: int32, type: integer}
        id: {description: 'The ID.

            ', type: string}
        tenant_id: {description: 'The tenant ID.

            ', type: string}
      type: object
    ReportListItem:
      properties:
        id: {description: 'The ID.

            ', type: string}
        modifiedTime: {description: 'The folder modified time.

            ', format: int64, type: integer}
        name: {description: 'The folder name.

            ', type: string}
        path: {description: 'The folder path.

            ', type: string}
        size: {description: 'The folder size.

            ', format: int64, type: integer}
        tenant_id: {description: Tenant Id, type: string}
        type: {description: 'The folder type.

            ', type: string}
info:
  contact: {}
  description: List of APIs used to generate reports.
  title: Reports
  version: Latest
openapi: 3.0.0
paths:
  /v2.0/api/tenants/{tenant_id}/reports:
    get:
      description: List all the report files.
      operationId: get-v2.0-api-tenants-tenant_id-reports
      parameters:
      - description: The tenant ID.
        in: path
        name: tenant_id
        required: true
        schema: {description: Tenant Id, type: string}
      responses:
        '200':
          content:
            text/plain:
              schema: {format: binary, type: string}
          description: Successful Operation
      summary: Get Report Files (v2.0)
      tags: [Reports]
  /v2.0/api/tenants/{tenant_id}/reports/query:
    post:
      description: Query all the report files.
      operationId: post-v2.0-api-tenants-tenant_id-reports-query
      parameters:
      - description: The tenant ID.
        in: path
        name: tenant_id
        required: true
        schema: {description: Tenant Id, type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/FolderScreen'}
      responses:
        '200':
          content:
            text/plain:
              schema: {format: binary, type: string}
          description: Successful Operation
      summary: Query Report Files (v2.0)
      tags: [Reports]
  /v2.0/api/tenants/{tenant_id}/reportsdir:
    get:
      description: List all the report files and folders in a specific folder.
      operationId: get-v2.0-api-tenants-tenant_id-reportsdir
      parameters:
      - description: The tenant ID.
        in: path
        name: tenant_id
        required: true
        schema: {description: Tenant Id, type: string}
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - {$ref: '#/components/schemas/ListResponse'}
                - properties:
                    items:
                      items: {$ref: '#/components/schemas/ReportListItem'}
                      type: array
                  type: object
          description: Successful Operation
      summary: Get Report Files in Specified Folder (v2.0)
      tags: [Reports]
  /v2.0/api/tenants/{tenant_id}/reportsdir/query:
    post:
      description: Query all the report files and folders in a specific folder.
      operationId: post-v2.0-api-tenants-tenant_id-reportsdir-query
      parameters:
      - description: The tenant ID.
        in: path
        name: tenant_id
        required: true
        schema: {description: Tenant Id, type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/FolderScreen'}
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - {$ref: '#/components/schemas/ListResponse'}
                - properties:
                    items:
                      items: {$ref: '#/components/schemas/ReportListItem'}
                      type: array
                  type: object
          description: Successful Operation
      summary: Query Report Files in Specified Folder (v2.0)
      tags: [Reports]
servers:
- {url: 'https://api.us.cloudgenix.com'}
tags:
- {name: Reports}
