components: {}
info:
  contact: {}
  description: 'Perform server health checks.

    '
  title: API Server Status
  version: '1.0'
openapi: 3.0.3
paths:
  /api/sase/resource/v1.0/health:
    get:
      description: 'Checks whether the Prisma Access Insights API server is up and
        running.

        '
      operationId: get-api-sase-resource-v1.0-health
      responses:
        '200':
          description: OK
      summary: API server health check
      tags:
      - APIServerStatus
  /api/sase/resource/v1.0/status:
    get:
      description: 'Checks the status of the API server.

        '
      operationId: get-api-sase-resource-v1.0-status
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: OK
      summary: API server status
      tags:
      - APIServerStatus
servers:
- url: https://pa-us.api.prismaaccess.com
tags:
- name: APIServerStatus
