version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "contributing"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "contributing"
    cooldown:
      default-days: 7
