import tailwindPlugin from "./plugins/tailwind-config.cjs";

/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

let baseUrl;
if (process.env.CI_MERGE_REQUEST_IID) {
  if (process.env.CI_PROJECT_DIR == "dev") {
    baseUrl = "/";
  } else {
    baseUrl =
      process.env.GL_PAGES_BASE_URL ??
      `/-/${process.env.CI_PROJECT_NAME}/-/jobs/${process.env.CI_JOB_ID}/artifacts/public/`;
  }
} else {
  baseUrl = process.env.GL_PAGES_BASE_URL ?? "/";
}

// Every operation page the retired /access/api/browser-mgmt/* doc set
// published, paired with its successor under /prisma-browser/api/*. Both doc
// sets are generated by docusaurus-plugin-openapi-docs, so the pairs were
// derived by matching operations across the two OpenAPI specs on HTTP method
// and path. This keeps each old deep link on the endpoint it documented
// instead of dropping every one of them on a generic index.
const browserMgmtOperationRedirects = [
  ["get-seb-api-v-1-users", "list-users"],
  ["get-seb-api-v-1-usersbyid", "get-user-by-id"],
  ["post-seb-api-v-1-users-suspend", "suspend-users"],
  ["post-seb-api-v-1-users-resume", "resume-users"],
  ["post-seb-api-v-1-users-force-reauth", "force-reauth-users"],
  ["get-seb-api-v-1-devices", "list-devices"],
  ["get-seb-api-v-1-devicesbyid", "get-device-by-id"],
  ["post-seb-api-v-1-devices-archive", "archive-devices"],
  ["post-seb-api-v-1-devices-restore", "restore-devices"],
  ["post-seb-api-v-1-devices-suspend", "suspend-devices"],
  ["post-seb-api-v-1-devices-resume", "resume-devices"],
  ["post-seb-api-v-1-devices-delete", "delete-devices"],
  ["post-seb-api-v-1-devices-force-reauth", "force-reauth-devices"],
  ["get-seb-api-v-1-device-groups", "list-device-groups"],
  ["post-seb-api-v-1-device-groups", "create-device-group"],
  ["get-seb-api-v-1-device-groupsbydevice-group-id", "get-device-group-by-id"],
  ["put-seb-api-v-1-device-groupsbydevice-group-id", "update-device-group"],
  ["delete-seb-api-v-1-device-groupsbydevice-group-id", "delete-device-group"],
  ["patch-seb-api-v-1-device-groupsbydevice-group-id", "patch-device-group"],
  ["post-seb-api-v-1-configuration-management-draft-publish", "publish-draft-configuration"],
  ["get-seb-api-v-1-user-groups", "list-user-groups"],
  ["post-seb-api-v-1-user-groups", "create-user-group"],
  ["get-seb-api-v-1-user-groupsbyid", "get-user-group-by-id"],
  ["put-seb-api-v-1-user-groupsbyid", "update-user-group"],
  ["delete-seb-api-v-1-user-groupsbyid", "delete-user-group"],
  ["get-seb-api-v-1-applications", "list-applications"],
  ["get-seb-api-v-1-applicationsbyid", "get-application-by-id"],
  ["delete-seb-api-v-1-applicationsbyid", "delete-application-by-id"],
  ["get-seb-api-v-1-applications-typebytype", "list-applications-by-type"],
  ["post-seb-api-v-1-applications-typebytype", "create-application"],
  ["get-seb-api-v-1-applications-type-by-typebyid", "get-application-by-type-and-id"],
  ["delete-seb-api-v-1-applications-type-by-typebyid", "delete-application-by-type-and-id"],
  ["patch-seb-api-v-1-applications-type-by-typebyid", "patch-application-by-type-and-id"],
  ["get-seb-api-v-1-applications-categories", "list-application-categories"],
  ["bulk-create-applications", "bulk-create-applications"],
  ["post-seb-api-v-1-applications-bulk-delete", "bulk-delete-applications"],
  ["get-seb-api-v-1-application-groups", "list-application-groups"],
  ["post-seb-api-v-1-application-groups", "create-application-group"],
  ["get-seb-api-v-1-application-groupsbyid", "get-application-group-by-id"],
  ["delete-seb-api-v-1-application-groupsbyid", "delete-application-group-by-id"],
  ["patch-seb-api-v-1-application-groupsbyid", "patch-application-group-by-id"],
  ["get-seb-api-v-1-applications-plugins", "list-application-plugins"],
  ["get-seb-api-v-1-applications-by-id-plugins", "get-application-plugin"],
  ["put-seb-api-v-1-applications-by-id-plugins", "update-application-plugin"],
  ["post-seb-api-v-1-applications-by-id-plugins", "create-application-plugin"],
  ["delete-seb-api-v-1-applications-by-id-plugins", "delete-application-plugin"],
  ["get-seb-api-v-1-user-requests", "list-user-requests"],
  ["get-seb-api-v-1-user-requestsbyid", "get-a-user-request"],
  ["post-seb-api-v-1-user-requests-by-id-action", "act-on-a-user-request"],
  ["post-seb-api-v-1-user-requests-by-id-revoke", "revoke-a-user-request"],
].map(([from, to]) => ({
  from: `/access/api/browser-mgmt/${from}`,
  to: `/prisma-browser/api/${to}`,
}));

const config = {
  future: {
    faster: (process.env.DOCUSAURUS_FASTER ?? "true") === "true",
    v4: true
  },
  title: "Develop with Palo Alto Networks (Prisma Browser Beta)",
  tagline:
    "Explore our API Doc, Quickstarts, and Blog or dive right in and play in our sandbox. We have all the tools you needs to make the next big security innovation. SDKs in your favorite languages, detailed walk-throughs for sample apps, and all the resources you’ll need to flourish.",
  url: process.env.GL_PAGES_URL
    ? process.env.GL_PAGES_URL
    : process.env.CI_PAGES_URL ?? "https://pb-browser-beta.web.app",
  baseUrl: baseUrl,
  favicon: "img/PANW_Parent_Glyph_Red.svg",
  organizationName: "PaloAltoNetworks",
  projectName: "pb-browser-pan-dev-beta",
  noIndex: true,
  markdown: { format: "detect", mermaid: true },
  themeConfig: {
    prism: {
      additionalLanguages: ["csharp", "php", "hcl", "json", "bash"],
    },
    languageTabs: [
      {
        highlight: "bash",
        language: "curl",
        logoClass: "curl",
      },
      {
        highlight: "python",
        language: "python",
        logoClass: "python",
      },
      {
        highlight: "go",
        language: "go",
        logoClass: "go",
      },
      {
        highlight: "javascript",
        language: "nodejs",
        logoClass: "nodejs",
      },
      {
        highlight: "csharp",
        language: "csharp",
        logoClass: "csharp",
      },
      {
        highlight: "php",
        language: "php",
        logoClass: "php",
      },
    ],
    colorMode: {
      defaultMode: "light",
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true,
      },
    },
    api: {
      schemaExpansion: {
        enabled: true,
        default: 0,
        max: 4,
        persist: true,
      },
    },
    algolia: {
      apiKey: "6869800b232f5f8362e83901d79110ee",
      appId: "XC7919KOX3",
      indexName: "pan",
      externalUrlRegex:
        "cortex.pan.dev|xsoar.pan.dev|prisma.pan.dev|gallery.pan.dev|panos.pan.dev",
      searchParameters: {
        typoTolerance: false,
        facetFilters: [["tags:pandev"]],
      },
    },
    hideOnScroll: true,
    announcementBar: {
      id: "pb_beta_preview_v2",
      content:
        "<b>Early preview.</b> The new policy APIs are in beta and may introduce breaking changes, follow the <a href='/prisma-browser/release-notes'>release notes</a>.",
      backgroundColor: "#4f46e5",
      textColor: "#ffffff",
      isCloseable: true,
    },
    navbar: {
      title: "",
      logo: {
        alt: "Palo Alto Networks for Developers",
        src: "img/pan_dev_black.svg",
        srcDark: "img/pan_dev_white.svg",
      },
      items: [
        {
          label: "Developer Docs",
          className: "margin-left--lg",
          megaNav: true,
          items: [
            {
              label: "Cloud Native Security",
              to: "#",
              colorclass: "cloud-native-security",
              description:
                "Discover the APIs, tools and techniques necessary for bringing DevOps practices to the cloud.",
              products: [
                {
                  label: "Prisma Cloud Enterprise Edition",
                  to: "#",
                  logoClass: "prisma",
                  apiDocs: [
                    {
                      to: "/prisma-cloud/api",
                      label: "Prisma Cloud API",
                      icon: "api-doc",
                    },
                  ],
                  docs: [
                    {
                      to: "/prisma-cloud/docs",
                      label: "API Workflows",
                      icon: "doc",
                    },
                  ],
                },
                {
                  label: "Prisma Cloud Compute Edition",
                  to: "#",
                  logoClass: "prisma",
                  apiDocs: [
                    {
                      to: "/compute/api/",
                      label: "Compute Edition",
                      icon: "api-doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Security Operations",
              to: "#",
              colorclass: "security-operations",
              description:
                "Browse reference docs, tutorials, the XSOAR Marketplace and more.",
              products: [
                {
                  to: "#",
                  label: "Cortex XSOAR",
                  logoClass: "xsoar",
                  apiDocs: [
                    {
                      label: "XSOAR (Demisto) API",
                      to: "https://xsoar.pan.dev/docs/reference/api/demisto-class",
                      icon: "api-doc",
                    },
                  ],
                  docs: [
                    {
                      label: "Cortex XSOAR Developer Hub",
                      to: "https://xsoar.pan.dev/docs/welcome",
                      icon: "doc",
                    },
                  ],
                },
                {
                  label: "Cortex",
                  to: "#",
                  logoClass: "cortex",
                  docs: [
                    {
                      label: "Cortex Developer Docs",
                      to: "https://docs-cortex.paloaltonetworks.com/",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Network Security",
              to: "#",
              colorclass: "network-security",
              description:
                "Learn how to make the most of the PAN-OS APIs, SDKs, Expedition, Terraform, Ansible, and more.",
              products: [
                {
                  label: "Prisma AIRS",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    
                    {
                      to: "/airs",
                      label: "Prisma AIRS",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "prisma-airs/api/airuntimesecurity/airuntimesecurityapi",
                      label: "Prisma AIRS AI Runtime: API Intercept",
                      icon: "api-doc",
                    },
                    {
                      to: "prisma-airs-redteam/api/ai-integration/introduction",
                      label: "Prisma AIRS AI Red Teaming",
                      icon: "api-doc",
                    },
                    {
                      to: "prisma-airs-model-security/api/aisecuritymodel/aisecuritymodel",
                      label: "Prisma AIRS AI Model Security",
                      icon: "api-doc",
                    },
                  ],
          
                },
                {
                  label: "PAN-OS",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    {
                      label: "APIs, SDKs, & Tutorials",
                      to: "panos/docs",
                      icon: "doc",
                    },
                    {
                      label: "Terraform for VM-Series",
                      to: "swfw",
                      icon: "doc",
                    },
                    {
                      label: "Terraform for PAN-OS",
                      to: "terraform/docs/panos",
                      icon: "doc",
                    },
                    {
                      label: "Ansible",
                      to: "ansible/docs/panos",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      label: "Ansible Module Reference",
                      to: "https://galaxy.ansible.com/ui/repo/published/paloaltonetworks/panos/docs",
                      icon: "api-doc",
                    },
                    {
                      label: "Terraform Provider Reference",
                      to: "https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Cloud NGFW",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    {
                      label: "Introduction",
                      to: "cloudngfw/docs",
                      icon: "doc",
                    },
                    {
                      label: "Terraform - AWS",
                      to: "terraform/docs/cloudngfw",
                      icon: "doc",
                    },
                    {
                      label: "Terraform - Azure",
                      to: "terraform/docs/cloudngfw",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "cloudngfw/aws/api/",
                      label: "Cloud NGFW for AWS API",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Strata Logging Service",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    {
                      label: "Log Forwarding Developer's Guide",
                      to: "cdl/docs/log-forwarding",
                      icon: "doc",
                    },
                    {
                      label: "Log Forwarding Change Log",
                      to: "cdl/docs/logforwarding/release-notes/changelog",
                      icon: "doc",
                    },
                    {
                      label: "Log Forwarding Release Notes",
                      to: "cdl/docs/logforwarding/release-notes/relnotes",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      label: "Log Forwarding",
                      to: "cdl/api/log-forwarding",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Cloud-Delivered Security Services",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    {
                      label: "Cloud-Delivered Security Services",
                      to: "/cdss/docs",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "/aiops-ngfw-bpa/api",
                      label: "AIOps for NGFW Best Practice Assessment API",
                      icon: "api-doc",
                    },
                    {
                      to: "/threat-vault/api",
                      label: "Threat Vault APIs",
                      icon: "api-doc",
                    },
                    {
                      to: "/iot/api",
                      label: "IoT API",
                      icon: "api-doc",
                    },
                    {
                      to: "/dns-security/api",
                      label: "DNS Security API",
                      icon: "api-doc",
                    },
                    {
                      to: "dlp/api",
                      label: "Data Loss Prevention API",
                      icon: "api-doc",
                    },
                    {
                      to: "email-dlp/api",
                      label: "Email Data Loss Prevention API",
                      icon: "api-doc",
                    },
                    {
                      to: "https://docs.paloaltonetworks.com/saas-security/saas-security-admin/saas-security-api",
                      label: "SaaS Security API",
                      icon: "api-doc",
                    },
                    {
                      to: "https://docs.paloaltonetworks.com/wildfire/u-v/wildfire-api",
                      label: "WildFire API",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Expedition",
                  to: "#",
                  logoClass: "panos",
                  docs: [
                    {
                      label: "Expedition",
                      to: "expedition/docs",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [],
                },
              ],
            },
            {
              label: "Strata Cloud Manager",
              to: "#",
              colorclass: "scm",
              description: "Discover Strata Cloud Manager APIs.",
              products: [
                {
                  label: "Strata Cloud Manager",
                  to: "#",
                  logoClass: "scm",
                  docs: [
                    {
                      to: "strata-cloud-manager",
                      label: "Home Page",
                      icon: "doc",
                    },
                    {
                      to: "scm/docs/home",
                      label: "Developer's Guide",
                      icon: "doc",
                    },
                    {
                      to: "scm/docs/api-best-practices",
                      label: "Strata Cloud Manager API Best Practices",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Secure Access Service Edge",
              to: "#",
              colorclass: "sase",
              description:
                "Discover Prisma SASE APIs, including Prisma Access and Prisma SD-WAN.",
              products: [
                {
                  label: "Prisma SASE",
                  to: "#",
                  logoClass: "prisma",
                  docs: [
                    {
                      to: "sase/docs",
                      label: "Prisma SASE Developer's Guide",
                      icon: "doc",
                    },
                    {
                      to: "sase/docs/release-notes/release-notes",
                      label: "Prisma SASE Release Notes",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "sase/api/tenancy",
                      label: "Tenancy Service",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/iam",
                      label: "Identity and Access Management",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/auth",
                      label: "Authentication Service",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/subscription",
                      label: "Subscription Service",
                      icon: "api-doc",
                    },
                    {
                      to: "/access/api/prisma-access-config",
                      label: "Prisma Access Configuration",
                      icon: "api-doc",
                    },
                    {
                      to: "/access/api/ztna/ztna-connector-api",
                      label: "ZTNA Connector",
                      icon: "api-doc",
                    },
                    {
                      to: "sdwan/api",
                      label: "Prisma SD-WAN",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/mt-monitor",
                      label: "Aggregate Monitoring",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/mt-notifications",
                      label: "Multitenant Notifications",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/mt-interconnect/introduction",
                      label: "Service Provider Interconnect",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/pab-msp/pab-msp-api",
                      label: "Prisma Browser for MSPs",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/manage-services-5g/introduction",
                      label: "SASE 5G Manage Services",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/monitor-services-5g/introduction-monitor",
                      label: "SASE 5G Monitor Services",
                      icon: "api-doc",
                    },
                    {
                      to: "/sase/api/introduction",
                      label: "Prisma Access Configuration Orchestration",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/sspm",
                      label: "SaaS Security Posture Management",
                      icon: "api-doc",
                    },
                    {
                      to: "sase/api/identity-sspm",
                      label: "Identity Security Posture Management",
                      icon: "api-doc",
                    },
                    {
                      to: "access/api/adem/introduction",
                      label: "Autonomous DEM",
                      icon: "api-doc",
                    },
                    {
                      label: "Log Forwarding",
                      to: "cdl/api/log-forwarding",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Prisma Access Configuration",
                  to: "#",
                  logoClass: "prisma",
                  docs: [
                    {
                      label: "Prisma Access Configuration Developer's Guide",
                      to: "access/docs/prisma-access-config",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "access/api/prisma-access-config",
                      label: "Prisma Access Configuration",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Prisma Browser Management",
                  to: "/prisma-browser",
                  logoClass: "prisma",
                  // Prisma Browser leads with the guides because the overview
                  // page is the intended entry point. Every other product keeps
                  // the site default of API Reference first.
                  docsFirst: true,
                  docs: [
                    {
                      to: "/prisma-browser",
                      label: "Overview",
                      icon: "doc",
                    },
                    {
                      to: "/prisma-browser/guide/guide-overview",
                      label: "Developer Guide",
                      icon: "doc",
                    },
                    {
                      to: "/prisma-browser/release-notes",
                      label: "Release Notes",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      // ?ref=nav marks this as a navigational entry into the
                      // API section (see portalConfig API_REF_URL).
                      to: "/prisma-browser/api/list-users?ref=nav",
                      label: "Prisma Browser Management",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Prisma Access Insights",
                  to: "#",
                  logoClass: "prisma",
                  docs: [
                    {
                      label: "Get Started 1.0",
                      to: "access/docs/insights/getting_started-10",
                      icon: "doc",
                    },
                    {
                      label: "Get Started 2.0",
                      to: "access/docs/insights/getting_started-20",
                      icon: "doc",
                    },
                    {
                      label: "Get Started 3.0",
                      to: "access/docs/insights/getting_started-30",
                      icon: "doc",
                    },
                    {
                      label: "API FAQs",
                      to: "access/docs/insights/pai-faqs",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "access/api/insights/1.0",
                      label: "Prisma Access Insights 1.0",
                      icon: "api-doc",
                    },
                    {
                      to: "access/api/insights/2.0",
                      label: "Prisma Access Insights 2.0",
                      icon: "api-doc",
                    },
                    {
                      to: "access/api/insights",
                      label: "Prisma Access Insights 3.0",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Prisma SD-WAN",
                  to: "#",
                  logoClass: "prisma",
                  docs: [
                    {
                      label: "Prisma SD-WAN Overview",
                      to: "/sdwan/docs",
                      icon: "doc",
                    },
                  ],
                  apiDocs: [
                    {
                      to: "sdwan/api",
                      label: "Prisma SD-WAN Unified",
                      icon: "api-doc",
                    },
                    {
                      to: "sdwan/api/legacy",
                      label: "Prisma SD-WAN Legacy",
                      icon: "api-doc",
                    },
                  ],
                },
                {
                  label: "Prisma SASE Service Status",
                  to: "#",
                  logoClass: "prisma",
                  docs: [
                    {
                      label: "Prisma SASE Service Status API",
                      to: "sase/docs/saseservicestatusapi",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Partner Integrations",
              to: "#",
              colorclass: "partner-integrations",
              description: "Discover technology partner integrations.",
              products: [
                {
                  label: "Automation",
                  to: "#",
                  docs: [
                    {
                      label: "Terraform for Software NGFW",
                      to: "swfw",
                      icon: "doc",
                    },
                    {
                      label: "Terraform and Palo Alto Networks",
                      to: "terraform",
                      icon: "doc",
                    },
                    {
                      label: "Ansible",
                      to: "ansible",
                      icon: "doc",
                    },
                  ],
                },
                {
                  label: "SIEM",
                  to: "#",
                  docs: [
                    {
                      label: "Splunk App/Add-on",
                      to: "splunk/docs",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Cross-Platform",
              to: "#",
              colorclass: "cross-platform",
              description:
                "Learn about opportunities across Palo Alto Networks platforms.",
              products: [
                {
                  label: "Service Status",
                  to: "#",
                  docs: [
                    {
                      label: "Service Status API",
                      to: "cross-platform/docs/servicestatusapi",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
            {
              label: "Idira",
              to: "#",
              colorclass: "idira",
              description:
                "Explore resources and community content for IDIRA",
              products: [
                {
                  label: "Idira Resources",
                  to: "#",
                  docs: [
                    {
                      label: "Idira Marketplace",
                      to: "https://marketplace.idira.pan.dev/",
                      icon: "doc",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          to: "https://gallery.pan.dev",
          className: "header-github-link",
          position: "right",
        },
        {
          href: "https://medium.com/palo-alto-networks-developer-blog",
          className: "header-blog-link",
          position: "right",
          "aria-label": "Palo Alto Networks Developer Blog",
        },
      ],
    },
    footer: {
      style: "light",
      logo: {
        alt: "Palo Alto Networks for developers",
        src: "img/PANW_Parent_Logo_White.svg",
      },
      copyright: `Copyright © ${new Date().getFullYear()} Palo Alto Networks, Inc.`,
    },
  },
  themes: ["docusaurus-theme-openapi-docs", "@docusaurus/theme-mermaid"],
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: false,
        theme: {
          customCss: [require.resolve("./src/css/custom.scss")],
        },
        // Analytics is deliberately not configured here. pan.dev loads GA
        // through docusaurus-plugin-gtm (see plugins below), which is gated by
        // the cookie-consent banner. The PB custom events in src/theme/Root.js
        // call the window.gtag that plugin installs, so they inherit the same
        // consent gate. Adding a preset gtag here would fire a second,
        // ungated tag.
      },
    ],
  ],
  plugins: [
    [
      "@docusaurus/plugin-client-redirects",
      {
        redirects: [
          // Legacy URLs from the pre-PBPortal browser-mgmt doc page.
          {
            from: "/access/api/browser-mgmt",
            to: "/prisma-browser/guide/guide-overview",
          },
          {
            from: "/access/api/browser-mgmt/browser-mgmt-api",
            to: "/prisma-browser/guide/guide-overview",
          },
          {
            from: "/access/api/browser-mgmt/list-users",
            to: "/prisma-browser/api/list-users",
          },
          ...browserMgmtOperationRedirects,
          // The OpenAPI plugin auto-generates an "Introduction" page from the
          // spec's info block at this long slug. Redirect to the canonical API
          // entry point used by the surface switcher.
          {
            from: "/access/api/browser-mgmt/prisma-browser-management-console-public-api",
            to: "/prisma-browser/api/list-users",
          },
        ],
      },
    ],
    [
      "@docusaurus/plugin-sitemap",
      {
        id: "pan-sitemap",
        changefreq: "weekly",
        priority: 0.5,
      },
    ],
    // Prisma Browser release notes: authored as MDX with structured front matter,
    // rendered by the swizzled blog theme (src/theme/BlogListPage + BlogPostPage)
    // into the PBPortal shell, and published as a native RSS feed.
    [
      "@docusaurus/plugin-content-blog",
      {
        id: "pb-release-notes",
        routeBasePath: "/prisma-browser/release-notes",
        path: "src/components/PBPortal/release-notes",
        blogTitle: "Prisma Browser release notes",
        blogDescription:
          "Every customer-facing change to the Prisma Browser Management API.",
        blogSidebarCount: 0,
        showReadingTime: false,
        postsPerPage: "ALL",
        archiveBasePath: null,
        onUntruncatedBlogPosts: "ignore",
        feedOptions: {
          type: ["rss"],
          title: "Prisma Browser release notes",
          description:
            "Every customer-facing change to the Prisma Browser Management API.",
          copyright: `Copyright © ${new Date().getFullYear()} Palo Alto Networks, Inc.`,
          language: "en",
          // Emit a description that reads cleanly in Slack/Teams/readers (which
          // strip HTML and collapse whitespace): summary, one line per change
          // type, then a link back to the full on-site release note.
          createFeedItems: async ({
            blogPosts,
            defaultCreateFeedItems,
            ...rest
          }) => {
            const items = await defaultCreateFeedItems({ blogPosts, ...rest });
            const TYPE_ORDER = [
              "breaking",
              "new",
              "changed",
              "deprecated",
              "removed",
              "fixed",
            ];
            const TYPE_LABEL = {
              breaking: "Breaking",
              new: "New",
              changed: "Changed",
              deprecated: "Sunset",
              removed: "Removed",
              fixed: "Fixed",
            };
            const stripSlash = (s) => String(s || "").replace(/\/+$/, "");
            const stripHtml = (s) => String(s || "").replace(/<[^>]+>/g, "");
            const esc = (s) =>
              String(s || "")
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;");
            return items.map((item) => {
              const post = blogPosts.find(
                (p) =>
                  item.link &&
                  stripSlash(item.link).endsWith(stripSlash(p.metadata.permalink))
              );
              const fm = post?.metadata?.frontMatter || {};
              const summary = fm.summary || "";
              const changes = Array.isArray(fm.changes) ? fm.changes : [];
              const parts = [];
              if (summary) parts.push(`<p>${esc(summary)}</p>`);
              for (const t of TYPE_ORDER) {
                const texts = changes
                  .filter((c) => c.type === t)
                  .map((c) => stripHtml(c.text));
                if (texts.length) {
                  parts.push(`<p>${esc(`${TYPE_LABEL[t]}: ${texts.join("; ")}`)}</p>`);
                }
              }
              // Link back to the release notes list page (not the individual
              // note). item.id stays the note permalink, so each RSS <guid>
              // remains unique and readers still treat items as distinct.
              const RN_BASE = "/prisma-browser/release-notes";
              let listUrl = item.link || "";
              if (item.link) {
                const idx = item.link.indexOf(RN_BASE);
                if (idx !== -1) {
                  listUrl = item.link.slice(0, idx + RN_BASE.length);
                }
              }
              // Tag the link so RSS-driven visits are attributed in GA4
              // (medium=feed). guid stays item.id (the note permalink), so
              // items remain unique and readers still de-dupe correctly.
              const withUtm = (url) => {
                if (!url) return url;
                const sep = url.includes("?") ? "&" : "?";
                return `${url}${sep}utm_source=rss&utm_medium=feed&utm_campaign=pb-release-notes`;
              };
              const listUrlUtm = withUtm(listUrl);
              if (listUrlUtm) {
                parts.push(
                  `<p><a href="${listUrlUtm}">Read the full release notes</a></p>`
                );
              }
              const html = parts.join("");
              item.content = html;
              item.description = html;
              if (listUrlUtm) item.link = listUrlUtm;
              return item;
            });
          },
        },
      },
    ],
    "docusaurus-plugin-sass",
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "default",
        docsPluginId: "default",
        config: {
          auth: {
            specPath: "openapi-specs/sase/auth",
            outputDir: "products/sase/api/auth",
            proxy: "https://cors.pan.dev",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          },
          scmauth: {
            specPath: "openapi-specs/scm/auth",
            outputDir: "products/scm/api/auth",
            proxy: "https://cors.pan.dev",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          },
          iam: {
            specPath: "openapi-specs/sase/iam",
            outputDir: "products/sase/api/iam",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          scmiam: {
            specPath: "openapi-specs/scm/iam",
            outputDir: "products/scm/api/iam",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          "config-sase-operations": {
            specPath: "openapi-specs/scm/config/sase/operations",
            outputDir: "products/scm/api/config/sase/operations",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-setup": {
            specPath: "openapi-specs/scm/config/sase/setup",
            outputDir: "products/scm/api/config/sase/setup",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-setup-device-onboarding": {
            specPath: "openapi-specs/scm/config/sase/setup/device-onboarding",
            outputDir: "products/scm/api/config/sase/setup/device-onboarding",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-deployment": {
            specPath: "openapi-specs/scm/config/sase/deployment",
            outputDir: "products/scm/api/config/sase/deployment",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-identity": {
            specPath: "openapi-specs/scm/config/sase/identity",
            outputDir: "products/scm/api/config/sase/identity",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-mobileagent": {
            specPath: "openapi-specs/scm/config/sase/mobileagent",
            outputDir: "products/scm/api/config/sase/mobileagent",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-objects": {
            specPath: "openapi-specs/scm/config/sase/objects",
            outputDir: "products/scm/api/config/sase/objects",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-security": {
            specPath: "openapi-specs/scm/config/sase/security",
            outputDir: "products/scm/api/config/sase/security",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-network configurations": {
            specPath: "openapi-specs/scm/config/sase/network/network-services_R3_v1.1.yaml",
            outputDir: "products/scm/api/config/sase/network",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-logical-routers": {
            specPath: "openapi-specs/scm/config/sase/network/logical-routers",
            outputDir: "products/scm/api/config/sase/network/logical-routers",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-virtual-routers": {
            specPath: "openapi-specs/scm/config/sase/network/virtual-routers",
            outputDir: "products/scm/api/config/sase/network/virtual-routers",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-sase-vr-routing-profiles": {
            specPath: "openapi-specs/scm/config/sase/network/vr-routing-profiles",
            outputDir: "products/scm/api/config/sase/network/vr-routing-profiles",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-operations": {
            specPath: "openapi-specs/scm/config/ngfw/operations",
            outputDir: "products/scm/api/config/ngfw/operations",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-operations-api": {
            specPath: "openapi-specs/scm/config/ngfw-operations",
            outputDir: "products/scm/api/config/ngfw-operations",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-setup": {
            specPath: "openapi-specs/scm/config/ngfw/setup",
            outputDir: "products/scm/api/config/ngfw/setup",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-setup-device-onboarding": {
            specPath: "openapi-specs/scm/config/ngfw/setup/device-onboarding",
            outputDir: "products/scm/api/config/ngfw/setup/device-onboarding",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-identity": {
            specPath: "openapi-specs/scm/config/ngfw/identity",
            outputDir: "products/scm/api/config/ngfw/identity",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-device": {
            specPath: "openapi-specs/scm/config/ngfw/device",
            outputDir: "products/scm/api/config/ngfw/device",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-network": {
            specPath: "openapi-specs/scm/config/ngfw/network/network-services_R3_v1.1.yaml",
            outputDir: "products/scm/api/config/ngfw/network",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-logical-routers": {
            specPath: "openapi-specs/scm/config/ngfw/network/logical-routers",
            outputDir: "products/scm/api/config/ngfw/network/logical-routers",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-virtual-routers": {
            specPath: "openapi-specs/scm/config/ngfw/network/virtual-routers",
            outputDir: "products/scm/api/config/ngfw/network/virtual-routers",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-vr-routing-profiles": {
            specPath: "openapi-specs/scm/config/ngfw/network/vr-routing-profiles",
            outputDir: "products/scm/api/config/ngfw/network/vr-routing-profiles",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-objects": {
            specPath: "openapi-specs/scm/config/ngfw/objects",
            outputDir: "products/scm/api/config/ngfw/objects",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-ngfw-security": {
            specPath: "openapi-specs/scm/config/ngfw/security",
            outputDir: "products/scm/api/config/ngfw/security",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-operations": {
            specPath: "openapi-specs/scm/config/cloudngfw/operations",
            outputDir: "products/scm/api/config/cloudngfw/operations",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-setup": {
            specPath: "openapi-specs/scm/config/cloudngfw/setup",
            outputDir: "products/scm/api/config/cloudngfw/setup",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-setup-device-onboarding": {
            specPath: "openapi-specs/scm/config/cloudngfw/setup/device-onboarding",
            outputDir: "products/scm/api/config/cloudngfw/setup/device-onboarding",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-identity": {
            specPath: "openapi-specs/scm/config/cloudngfw/identity",
            outputDir: "products/scm/api/config/cloudngfw/identity",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-objects": {
            specPath: "openapi-specs/scm/config/cloudngfw/objects",
            outputDir: "products/scm/api/config/cloudngfw/objects",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cloudngfw-security": {
            specPath: "openapi-specs/scm/config/cloudngfw/security",
            outputDir: "products/scm/api/config/cloudngfw/security",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-incidents": {
            specPath: "openapi-specs/scm/config/incidents",
            outputDir: "products/scm/api/config/incidents",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "compliance-framework-posture": {
            specPath: "openapi-specs/scm/config/posture-management/compliance-framework",
            outputDir: "products/scm/api/config/posture-management/compliance-framework",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "policy-optimizer-posture": {
            specPath: "openapi-specs/scm/config/posture-management/policy-optimizer",
            outputDir: "products/scm/api/config/posture-management/policy-optimizer",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "posture-checks": {
            specPath: "openapi-specs/scm/config/posture-management/checks",
            outputDir: "products/scm/api/config/posture-management/checks",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-cleanup-posture": {
            specPath: "openapi-specs/scm/config/posture-management/config-cleanup",
            outputDir: "products/scm/api/config/posture-management/config-cleanup",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "config-adnsr": {
            specPath: "openapi-specs/scm/config/adnsr",
            outputDir: "products/scm/api/config/adnsr",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          adem: {
            specPath: "openapi-specs/access/adem",
            outputDir: "products/access/api/adem",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          insights: {
            specPath: "openapi-specs/access/insights/3.0",
            outputDir: "products/access/api/insights",
            sidebarOptions: { groupPathsBy: "tag" },
            version: "3.0",
            label: "v3.0",
            baseUrl: "/access/api/insights/",
            versions: {
              "2.0": {
                specPath: "openapi-specs/access/insights/2.0",
                outputDir: "products/access/api/insights/2.0",
                label: "v2.0",
                baseUrl: "/access/api/insights/2.0",
              },
              "1.0": {
                specPath: "openapi-specs/access/insights/1.0",
                outputDir: "products/access/api/insights/1.0",
                label: "v1.0",
                baseUrl: "/access/api/insights/1.0/",
              },
            },
          },
          mtmonitor: {
            specPath: "openapi-specs/sase/mt-monitor",
            outputDir: "products/sase/api/mt-monitor",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          mtnotifications: {
            specPath: "openapi-specs/sase/mt-notifications",
            outputDir: "products/sase/api/mt-notifications",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          ManageInterconnect: {
            specPath: "openapi-specs/sase/mt-interconnect/Manage",
            outputDir: "products/sase/api/mt-interconnect/Manage",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          MonitorInterconnect: {
            specPath: "openapi-specs/sase/mt-interconnect/Monitor",
            outputDir: "products/sase/api/mt-interconnect/Monitor",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          pabmsp: {
            specPath: "openapi-specs/sase/pab-msp",
            outputDir: "products/sase/api/pab-msp",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          manageservices: {
            specPath: "openapi-specs/sase/manage-services-5g",
            outputDir: "products/sase/api/manage-services-5g",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          monitorservices: {
            specPath: "openapi-specs/sase/monitor-services-5g",
            outputDir: "products/sase/api/monitor-services-5g",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          configorch: {
            specPath: "openapi-specs/sase/config-orch",
            outputDir: "products/sase/api/config-orch",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          sasesspm: {
            specPath: "openapi-specs/sase/sspm",
            outputDir: "products/sase/api/sspm",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          identitysspm: {
            specPath: "openapi-specs/sase/identity-sspm",
            outputDir: "products/sase/api/identity-sspm",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          access: {
            specPath: "openapi-specs/access/prisma-access-config",
            outputDir: "products/access/api/prisma-access-config",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          browsermgmt: {
            // Generate from the synced+normalized copy (see sync-spec.mjs): it
            // strips `additionalProperties: false` from allOf branches so the
            // reference renders full request-body schemas. gen-pb (which runs
            // sync-spec) always executes before gen-all in the start/build flow.
            specPath: "static/spec/prisma-browser-management.yaml",
            outputDir: "products/prisma-browser/api",
            // Two-level nav driven by the spec's x-tagGroups: each group becomes a
            // top-level section and each tag a subsection. The generated info page is
            // off because tagGroup mode repeats it inside every group.
            showInfoPage: false,
            sidebarOptions: { groupPathsBy: "tagGroup" },
          },
          ztna: {
            specPath: "openapi-specs/access/ztna",
            outputDir: "products/access/api/ztna",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          sub: {
            specPath: "openapi-specs/sase/subscription",
            outputDir: "products/sase/api/subscription",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          scmsub: {
            specPath: "openapi-specs/scm/subscription",
            outputDir: "products/scm/api/subscription",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          tenancy: {
            specPath: "openapi-specs/sase/tenancy",
            outputDir: "products/sase/api/tenancy",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          scmtenancy: {
            specPath: "openapi-specs/scm/tenancy",
            outputDir: "products/scm/api/tenancy",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          ngts: {
            specPath: "openapi-specs/scm/config/ngts/tlsprotect-cloud.json",
            outputDir: "products/scm/api/config/ngts",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          ciedss: {
            specPath: "openapi-specs/scm/config/ciedss",
            outputDir: "products/scm/api/config/ciedss",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          cdug: {
            specPath: "openapi-specs/scm/config/cdug",
            outputDir: "products/scm/api/config/ciedss/cdug",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          sdwan: {
            specPath: "openapi-specs/sdwan/unified",
            outputDir: "products/sdwan/api",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
            version: "Unified",
            label: "Unified",
            baseUrl: "/sdwan/api/",
            versions: {
              legacy: {
                specPath: "openapi-specs/sdwan/legacy",
                outputDir: "products/sdwan/api/legacy",
                label: "Legacy",
                baseUrl: "/sdwan/api/legacy/",
              },
            },
          },
          "aiops-ngfw-bpa": {
            specPath: "openapi-specs/aiops-ngfw-bpa/BPAReportAPI.yaml",
            outputDir: "products/aiops-ngfw-bpa/api",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          "email-dlp": {
            specPath: "openapi-specs/email-dlp/EmailDLPAPI.yaml",
            outputDir: "products/email-dlp/api",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          dlp: {
            specPath: "openapi-specs/dlp",
            outputDir: "products/dlp/api",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          cloudngfw: {
            specPath: "openapi-specs/cloudngfw/aws",
            outputDir: "products/cloudngfw/api/aws",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          airuntimesecurity: {
            specPath: "openapi-specs/prisma-airs/scan",
            outputDir: "products/prisma-airs/api/airuntimesecurity/scan",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
          aiintegration: {
            specPath: "openapi-specs/prisma-airs-redteam/data-plane",
            outputDir: "products/prisma-airs-redteam/api/ai-integration/data-plane",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
          //Prisma AIRS Network Broker
          airsnetworkbroker: {
            specPath: "openapi-specs/prisma-airs-redteam/network-broker",
            outputDir: "products/prisma-airs-redteam/api/ai-integration/network-broker",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
           //Prisma AIRS Model Security Management
          aimodelsecurity: {
            specPath: "openapi-specs/prisma-airs-model-security/management",
            outputDir: "products/prisma-airs-model-security/api/aisecuritymodel/management",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
           //Prisma AIRS Model Security DataPlane
          aimsdataplane: {
            specPath: "openapi-specs/prisma-airs-model-security/dataplane",
            outputDir: "products/prisma-airs-model-security/api/aisecuritymodel/dataplane",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
          //Prisma AIRS RedTeam-management as config
          redteammgmt: {
            specPath: "openapi-specs/prisma-airs-redteam/management",
            outputDir: "products/prisma-airs-redteam/api/ai-integration/management",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
          // Add management API as separate config
          airuntimesecuritymgmt: {
            specPath: "openapi-specs/prisma-airs/management",
            outputDir: "products/prisma-airs/api/airuntimesecurity/management",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
          },
          iot: {
            specPath: "openapi-specs/iot/iot.yaml",
            outputDir: "products/iot/api",
          },
          "threat-vault": {
            specPath: "openapi-specs/threat-vault/",
            outputDir: "products/threat-vault/api",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          "dns-security": {
            specPath: "openapi-specs/dns-security/dns-security.yaml",
            outputDir: "products/dns-security/api",
            proxy: "https://cors.pan.dev",
            sidebarOptions: { groupPathsBy: "tag" },
          },
          cdl: {
            specPath: "openapi-specs/cdl/logforwarding",
            outputDir: "products/cdl/api/logforwarding",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          scmciedss: {
            specPath: "openapi-specs/scm/config/ciedss",
            outputDir: "products/scm/api/config/ciedss",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "info" },
          },
          mssp: {
            specPath: "openapi-specs/mssp",
            outputDir: "products/prisma-cloud/api/mssp",
            showExtensions: false,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/prisma-cloud/api/",
            hideSendButton: true,
          },
          "action-plan": {
            specPath: "openapi-specs/action-plan",
            outputDir: "products/prisma-cloud/api/action-plan",
            showExtensions: false,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/prisma-cloud/api/",
            hideSendButton: true,
          },
          cwpp: {
            specPath: "openapi-specs/cwpp",
            outputDir: "products/prisma-cloud/api/cwpp",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/prisma-cloud/api/",
            hideSendButton: true,
          },
          cspm: {
            specPath: "openapi-specs/cspm",
            outputDir: "products/prisma-cloud/api/cspm",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            hideSendButton: true,
          },
          code: {
            specPath: "openapi-specs/code",
            outputDir: "products/prisma-cloud/api/code",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            hideSendButton: true,
          },
          dspm: {
            specPath: "openapi-specs/dspm",
            outputDir: "products/prisma-cloud/api/dspm",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            hideSendButton: true,
          },
          compute: {
            specPath: "openapi-specs/compute",
            outputDir: "products/compute/api",
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            version: "34.04",
            label: "v34.04",
            showExtensions: true,
            hideSendButton: true,
            baseUrl: "/compute/api/",
            versions: {
              33.03: {
                specPath: "openapi-specs/compute/33-03",
                outputDir: "products/compute/api/33-03",
                label: "v33.03",
                baseUrl: "/compute/api/33-03/",
              },
              32.07: {
                specPath: "openapi-specs/compute/32-07",
                outputDir: "products/compute/api/32-07",
                label: "v32.07",
                baseUrl: "/compute/api/32-07/",
              },
            },
          },
          compute_3301: {
            specPath: "openapi-specs/compute/33-01",
            outputDir: "products/compute/api/33-01",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/33-01/",
          },
          compute_3302: {
            specPath: "openapi-specs/compute/33-02",
            outputDir: "products/compute/api/33-02",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/33-02/",
          },
          compute_3303: {
            specPath: "openapi-specs/compute/33-03",
            outputDir: "products/compute/api/33-03",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/33-03/",
          },
          compute_3400: {
            specPath: "openapi-specs/compute/34-00",
            outputDir: "products/compute/api/34-00",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/34-00/",
          },
          compute_3401: {
            specPath: "openapi-specs/compute/34-01",
            outputDir: "products/compute/api/34-01",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/34-01/",
          },
          compute_3402: {
            specPath: "openapi-specs/compute/34-02",
            outputDir: "products/compute/api/34-02",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/34-02/",
          },
          compute_3403: {
            specPath: "openapi-specs/compute/34-03",
            outputDir: "products/compute/api/34-03",
            showExtensions: true,
            sidebarOptions: { groupPathsBy: "tag", categoryLinkSource: "tag" },
            baseUrl: "/compute/api/34-03/",
          },
        },
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "default",
        routeBasePath: "/",
        path: "products",
        sidebarPath: "./sidebars.ts",
        editUrl: "https://github.com/PaloAltoNetworks/pb-browser-pan-dev-beta/tree/master",
        include: ["**/*.{md,mdx}"],
        docItemComponent: "@theme/ApiItem",
      },
    ],
    [
      require.resolve("./docusaurus-plugin-gtm/index.js"),
      {
        gtm: "GTM-PLXD79N",
        // Must match STORAGE_KEY in src/components/CookieConsent/consent.js:
        // the head script reads this to replay a returning visitor's choice
        // before GTM loads.
        storageKey: "cookie-consent-preferences",
      },
    ],
    tailwindPlugin,
  ],
  stylesheets: [
    {
      href: "https://use.fontawesome.com/releases/v6.2.0/css/all.css",
      type: "text/css",
      rel: "stylesheet",
      integrity: "sha384-SOnAn/m2fVJCwnbEYgD4xzrPtvsXdElhOVvR8ND1YjB5nhGNwwf7nBQlhfAwHAZC",
      crossorigin: "anonymous",
    },
    {
      href: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700;800&family=Outfit:wght@300;400;600;700;800&display=swap",
      type: "text/css",
      rel: "stylesheet",
    },
  ],
  onDuplicateRoutes: "warn",
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  trailingSlash: true,
  customFields: {
    errorReporterApiKey: process.env.REACT_APP_ERROR_REPORTER_APIKEY,
  },
};

/*
Takes in list of products to filter based on directory, outputs list of globby include for the doc plugin
*/
function docsPluginInclude(filters) {
  let include = [] as any;
  filters.forEach((product) => {
    let product_include = product + "/**/*.{md,mdx}";
    include.push(product_include);
  });
  return include;
}

async function createConfig() {
  let filters =
    process.env.PRODUCTS_INCLUDE && process.env.PRODUCTS_INCLUDE.split(",");
  if (filters) {
    // Resolve the docs plugin by name rather than by position: this repo adds
    // the client-redirects and release-notes blog plugins ahead of it, so a
    // hard-coded index silently targets the wrong plugin and the build fails
    // with '"include" is not allowed'.
    const docsPlugin = config.plugins.find(
      (plugin) =>
        Array.isArray(plugin) && plugin[0] === "@docusaurus/plugin-content-docs"
    );
    if (!docsPlugin) {
      throw new Error(
        "PRODUCTS_INCLUDE is set but @docusaurus/plugin-content-docs was not found in config.plugins"
      );
    }
    docsPlugin[1]["include"] = docsPluginInclude(filters);
  }
  return config;
}

module.exports = createConfig;
