components:
  schemas:
    DemStatus:
      properties:
        dem_enabled:
          description: "Indicates whether ADEM is enabled for your instance.     \
            \   \n"
          type: boolean
        id:
          description: 'ID of the ADEM instances.

            '
          type: string
        site_id:
          description: 'ID of the remote site.

            '
          type: string
      required:
      - site_id
    DemStatusQueryResponse:
      properties:
        dem_enabled:
          description: 'Indicates whether ADEM is enabled for your instance.

            '
          type: boolean
        id:
          description: "ID of the DEM status.           \n"
          type: string
        site_id:
          description: 'ID of the remote site. More details on the site can be retrieved
            by querying the sites API.

            '
          type: string
      required:
      - site_id
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The count of the query list.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number of queries.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted query IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number of queries.

            '
          format: int64
          type: integer
      type: object
    ListResponse:
      properties:
        count:
          description: 'The number of responses.

            '
          format: int32
          type: integer
        id:
          description: 'The ID of the response.

            '
          type: string
      type: object
info:
  contact: {}
  description: List of APIs used to retrieve the Autonomous DEM status in Prisma SD-WAN.
  title: ADEM
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/demstatus/query:
    post:
      description: Query the status of your ADEM instance.
      operationId: post-sdwan-v2.0-api-demstatus-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemStatusQueryResponse'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemStatusQueryResponse'
                      type: array
                  type: object
          description: Successful operation
      summary: Query ADEM Status (v2.0)
      tags:
      - ADEM
  /sdwan/v2.0/api/sites/{site_id}/demstatus:
    get:
      description: Get all ADEM statuses for all sites.
      operationId: get-sdwan-v2.0-api-sites-site_id-demstatus
      parameters:
      - description: The ADEM enabled site IDs.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/DemStatus'
                      type: array
                  type: object
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get ADEM Status (v2.0)
      tags:
      - ADEM
  /sdwan/v2.0/api/sites/{site_id}/demstatus/{dem_status_id}:
    get:
      description: Get DEM status for a site in Prisma SD-WAN.
      operationId: get-sdwan-v2.0-api-sites-site_id-demstatus-dem_status_id
      parameters:
      - description: The ADEM enabled site IDs.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: The status ID of the ADEM enabled site.
        in: path
        name: dem_status_id
        required: true
        schema:
          description: Dem Status Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemStatus'
          description: Successful operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '404':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: SITE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get ADEM Status for Site (v2.0)
      tags:
      - ADEM
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: ADEM
