components:
  schemas:
    Aggregate:
      properties:
        data:
          description: 'The details of the aggregate data.

            '
          items:
            $ref: '#/components/schemas/AggregateData'
          type: array
        field:
          description: Field
          type: string
        name:
          description: 'The name of the query response.

            '
          type: string
        operator:
          description: Operator
          enum:
          - max
          - count
          - min
          - avg
          - sum
          type: string
        statistic:
          description: 'QoS application aggregate statistics.

            '
          type: string
        unit:
          description: 'The unit.

            '
          type: string
      required:
      - statistic
      - unit
      - name
      - data
    AggregateData:
      properties:
        value:
          description: 'Value of the aggregate data.

            '
          type: number
        view:
          description: "View the aggregate date. \n"
          type: object
      required:
      - value
      - view
    AuditLog:
      properties:
        esp_tenant_id:
          description: 'The audit log MSP tenant ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        id:
          description: 'The audit log ID.

            '
          type: string
        operator_id:
          description: 'The audit log operator ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        operator_tenant_id:
          description: 'The audit log tenant ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        request_body:
          description: 'The audit log request body.

            '
          type: string
        request_content_length:
          description: 'The request content length.

            '
          format: int32
          type: integer
        request_id:
          description: 'The audit log request ID.

            '
          type: string
        request_ts:
          description: Request Ts
          format: int64
          type: integer
        request_type:
          description: 'The audit log request type (GET|POST|PUT|DELETE|PATCH)$).

            '
          type: string
        request_uri:
          description: 'The audit log request URL.

            '
          type: string
        resource_etag:
          description: 'The audit log request Etag.

            '
          format: int64
          type: integer
        resource_id:
          description: 'The audit log resource ID. Max length = 50.

            '
          type: string
        resource_key:
          description: 'The audit log resource key. Max length = 128.

            '
          type: string
        resource_version:
          description: 'The audit log resource version.

            '
          type: string
        response_body:
          description: 'The audit log response body.

            '
          type: string
        response_code:
          description: Response Code
          format: int32
          type: integer
        response_content_length:
          description: 'The audit log response content length.

            '
          format: int32
          type: integer
        response_ts:
          description: Response Ts
          format: int64
          type: integer
        session_key_c:
          description: 'The audit log session key C. Max length = 128.

            '
          type: string
        source_ip:
          description: 'The audit log source IP address. Max length = 128.

            '
          type: string
        time_ms:
          description: Time Ms
          format: int64
          type: integer
      required:
      - request_uri
      - request_type
      - request_id
    AuditLogV2N1:
      properties:
        esp_tenant_id:
          description: 'The audit log MSP tenant ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        id:
          description: 'The audit log ID.

            '
          type: string
        operator_id:
          description: 'The audit log operator ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        operator_tenant_id:
          description: 'The audit log tenant ID. Supported characters; = ^[a-z0-9]{1,50}$).

            '
          type: string
        request_body:
          description: 'The audit log request body.

            '
          type: string
        request_content_length:
          description: 'The request content length.

            '
          format: int32
          type: integer
        request_id:
          description: 'The audit log request ID.

            '
          type: string
        request_ts:
          description: Request Ts
          format: int64
          type: integer
        request_type:
          description: 'The audit log request type (GET|POST|PUT|DELETE|PATCH)$).

            '
          type: string
        request_uri:
          description: 'The audit log request URL.

            '
          type: string
        resource_etag:
          description: 'The audit log request Etag.

            '
          format: int64
          type: integer
        resource_id:
          description: 'The audit log resource ID. Max length = 50.

            '
          type: string
        resource_key:
          description: 'The audit log resource key. Max length = 128.

            '
          type: string
        resource_version:
          description: 'The audit log resource version.

            '
          type: string
        response_body:
          description: 'The audit log response body.

            '
          type: string
        response_code:
          description: Response Code
          format: int32
          type: integer
        response_content_length:
          description: 'The audit log response content length.

            '
          format: int32
          type: integer
        response_ts:
          description: Response Ts
          format: int64
          type: integer
        sdwanapp_id:
          description: 'Sdwanapp Id: Length(max = 128, , min = 0) '
          type: string
        session_key_c:
          description: 'The audit log session key C. Max length = 128.

            '
          type: string
        source_ip:
          description: 'The audit log source IP address. Max length = 128.

            '
          type: string
        time_ms:
          description: Time Ms
          format: int64
          type: integer
      required:
      - request_uri
      - request_type
      - request_id
    BaseQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: 'The aggregate number of queries.

            '
        dest_page:
          description: 'The destination page.

            '
          format: int32
          type: integer
        getDeleted:
          description: 'The number of queries deleted for a time frame.

            '
          type: boolean
        group_by:
          description: 'Group the queries.

            '
          items:
            description: Group By
            type: string
          type: array
        id:
          description: "List the queries by ID.    \n"
          type: string
        last_query_ts:
          description: 'Return the ID of a specified query in the current session.

            '
          format: int64
          type: integer
        limit:
          description: 'The query limit.

            '
          format: int32
          type: integer
        next_query:
          description: 'The  limit.

            '
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: 'Retrieve information from a field.

            '
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: 'List the fields to query.

            '
          type: boolean
        sort_params:
          type: object
        total_count:
          description: 'The total number of query parameters.

            '
          format: int64
          type: integer
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The count of the query list.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number of queries.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted query IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number of queries.

            '
          format: int64
          type: integer
      type: object
    ListResponse:
      properties:
        count:
          description: 'The number of responses.

            '
          format: int32
          type: integer
        id:
          description: 'The ID of the response.

            '
          type: string
      type: object
info:
  contact: {}
  description: List of APIs used to retrieve audit logs.
  title: Auditlogs
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/auditlog:
    get:
      description: List all the audit logs for a specific tenant.
      operationId: get-sdwan-v2.0-api-auditlog
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/AuditLog'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get Audit Logs for Tenant (v2.0)
      tags:
      - Auditlogs
  /sdwan/v2.0/api/auditlog/query:
    post:
      description: Query the audit logs for a given tenant as per specified query
        filters.
      operationId: post-sdwan-v2.0-api-auditlog-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseQuery'
        description: Query fields
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/AuditLog'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_ERROR_0001
                  - code: INVALID_REQUEST_DUPLICATE_KEY
                  - code: AUDITLOG_INVALID_TENANT_ID
                  - code: AUDITLOG_MESSAGE_ID_EMPTY
                  - code: AUDITLOG_MESSAGE_ID_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query Audit Logs for Tenant (v2.0)
      tags:
      - Auditlogs
  /sdwan/v2.0/api/auditlog/{auditlog_id}:
    get:
      description: List the audit logs for given tenant and audit log ID.
      operationId: get-sdwan-v2.0-api-auditlog-auditlog_id
      parameters:
      - description: The audit log ID.
        in: path
        name: auditlog_id
        required: true
        schema:
          description: Auditlog Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLog'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_ERROR_0001
                  - code: INVALID_REQUEST_DUPLICATE_KEY
                  - code: AUDITLOG_INVALID_TENANT_ID
                  - code: AUDITLOG_MESSAGE_ID_EMPTY
                  - code: AUDITLOG_MESSAGE_ID_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get Audit Logs and ID for Tenant (v2.0)
      tags:
      - Auditlogs
  /sdwan/v2.1/api/auditlog:
    get:
      description: List all the audit logs for a specific tenant.
      operationId: get-sdwan-v2.1-api-auditlog
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/AuditLogV2N1'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get Audit Logs for Tenant (v2.1)
      tags:
      - Auditlogs
  /sdwan/v2.1/api/auditlog/query:
    post:
      description: Query the audit logs for a given tenant as per specified query
        filters.
      operationId: post-sdwan-v2.1-api-auditlog-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseQuery'
        description: Query fields
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/AuditLogV2N1'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_ERROR_0001
                  - code: INVALID_REQUEST_DUPLICATE_KEY
                  - code: AUDITLOG_INVALID_TENANT_ID
                  - code: AUDITLOG_MESSAGE_ID_EMPTY
                  - code: AUDITLOG_MESSAGE_ID_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query Audit Logs for Tenant (v2.1)
      tags:
      - Auditlogs
  /sdwan/v2.1/api/auditlog/{auditlog_id}:
    get:
      description: List the audit logs for given tenant and audit log ID.
      operationId: get-sdwan-v2.1-api-auditlog-auditlog_id
      parameters:
      - description: The audit log ID.
        in: path
        name: auditlog_id
        required: true
        schema:
          description: Auditlog Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogV2N1'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_ERROR_0001
                  - code: INVALID_REQUEST_DUPLICATE_KEY
                  - code: AUDITLOG_INVALID_TENANT_ID
                  - code: AUDITLOG_MESSAGE_ID_EMPTY
                  - code: AUDITLOG_MESSAGE_ID_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get Audit Logs and ID for Tenant (v2.1)
      tags:
      - Auditlogs
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Auditlogs
