components:
  schemas:
    BulkResponse:
      properties:
        count:
          description: 'The total number.

            '
          format: int32
          type: integer
        id:
          description: 'The ID.

            '
          type: string
        type:
          description: "The type. \n"
          type: string
    ElementNTP:
      properties:
        description:
          description: 'Description: Size(max = 256, error = NTP_CONFIG_DESCRIPTION_INVALID:
            NTP description is invalid. The maximum length is 256., min = 0) '
          type: string
        id:
          description: Id
          type: string
        name:
          description: 'Name: NotEmpty(error = NTP_CONFIG_NAME_REQD: Name is mandatory
            for NTP configuration.) Size(max = 128, error = NAME_EXCEEDS_LIMIT: Name
            of the resource exceeds limit., min = 0) '
          type: string
        ntp_servers:
          description: 'Ntp Servers: NotEmpty(error = NTP_CONFIG_INVALID_SERVER_SIZE:
            A minimum of 1 and a maximum of 10 NTP servers can be configured.) Size(max
            = 10, error = NTP_CONFIG_INVALID_SERVER_SIZE: A minimum of 1 and a maximum
            of 10 NTP servers can be configured., min = 1) Valid '
          items:
            $ref: '#/components/schemas/NTPServer'
          type: array
        source_interface_ids:
          description: 'Source Interface Ids: ListString(allowDuplicate = false, allowEmpty
            = true, allowNull = true, length = 0, listMaxSize = 10, error = NTP_CONFIG_INVALID_INTERFACE_IDS:
            Source interface ids cannot be empty and should be valid.Interface ids
            should not be port that is part of logical interface group like bypass
            pair., noTrim = false, regex = , required = false) '
          items:
            description: Source Interface Ids
            type: string
          type: array
        tags:
          description: Tags
          items:
            description: Tags
            type: string
          type: array
      required:
      - ntp_servers
      - name
    ElementNTPState:
      properties:
        cts:
          $ref: '#/components/schemas/NTPServerState'
          description: Cts
        description:
          description: Description
          type: string
        disabled:
          description: Disabled
          type: boolean
        disabled_reason:
          description: 'Disabled Reason: Size(max = 5000, DISABLED_REASON_INVALID_0001,
            min = 0) Size(max = 5000, DISABLED_REASON_INVALID_0001, min = 0) '
          type: string
        element_id:
          description: Element Id
          type: string
        id:
          type: string
        inactive:
          description: Inactive
          type: boolean
        inactive_reason:
          description: 'Inactive Reason: Size(max = 5000, INACTIVE_REASON_INVALID_0001,
            min = 0) Size(max = 5000, INACTIVE_REASON_INVALID_0001, min = 0) '
          type: string
        name:
          description: Name
          type: string
        ntp_hash:
          description: 'Ntp Hash: JsonIgnore(value = true) JsonIgnore(value = true) '
          format: int32
          type: integer
        ntp_id:
          description: 'Ntp Id: JsonIgnore(value = true) JsonIgnore(value = true) '
          type: string
        ntp_servers:
          description: Ntp Servers
          items:
            $ref: '#/components/schemas/NTPServerState'
          type: array
        region:
          description: Region
          type: string
        source_interface_ids:
          description: Source Interface Ids
          items:
            description: Source Interface Ids
            type: string
          type: array
        tags:
          description: Tags
          items:
            description: Tags
            type: string
          type: array
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    NTPServer:
      properties:
        host:
          description: 'Host: ValidateHostName(allowNull = false, error = NTP_CONFIG_INVALID_HOST:
            Host can be only domain name or IP address.) '
          type: string
        max_poll:
          description: 'Max Poll: Required(message = required) ValidateDecimal(allowZero
            = false, increment = 0, max = 0, error = NTP_CONFIG_INVALID_MAXPOLL_VALUE:
            The range for maximum poll values is between 4-17., min = 0) '
          format: int32
          type: integer
        min_poll:
          description: 'Min Poll: Required(message = required) ValidateDecimal(allowZero
            = false, increment = 0, max = 0, error = NTP_CONFIG_INVALID_MINPOLL_VALUE:
            The range for minimum poll values is between 4-17., min = 0) '
          format: int32
          type: integer
        version:
          description: 'Version: Required(message = required) ValidateDecimal(allowZero
            = false, increment = 0, max = 0, error = NTP_CONFIG_INVALID_VERSION: Allowed
            versions are 2,3 & 4., min = 0) '
          format: int32
          type: integer
      required:
      - max_poll
      - min_poll
      - version
      - host
    NTPServerError:
      properties:
        message:
          description: Message
          type: string
        time_stamp:
          description: Time Stamp
          type: string
    NTPServerState:
      properties:
        host:
          description: Host
          type: string
        last_error:
          $ref: '#/components/schemas/NTPServerError'
          description: Last Error
        last_polled:
          description: Last Polled
          type: string
        last_selected:
          $ref: '#/components/schemas/NtpLastSelected'
          description: Last Selected
    NTPTemplate:
      properties:
        default_template:
          description: Default Template
          type: boolean
        description:
          description: 'Description: Size(max = 256, error = NTP_CONFIG_DESCRIPTION_INVALID:
            NTP description is invalid. The maximum length is 256., min = 0) '
          type: string
        id:
          description: Id
          type: string
        name:
          description: 'Name: NotEmpty(error = NTP_CONFIG_NAME_REQD: Name is mandatory
            for NTP configuration.) Size(max = 128, error = NAME_EXCEEDS_LIMIT: Name
            of the resource exceeds limit., min = 0) '
          type: string
        ntp_servers:
          description: 'Ntp Servers: NotEmpty(error = NTP_CONFIG_INVALID_SERVER_SIZE:
            A minimum of 1 and a maximum of 10 NTP servers can be configured.) Size(max
            = 10, error = NTP_CONFIG_INVALID_SERVER_SIZE: A minimum of 1 and a maximum
            of 10 NTP servers can be configured., min = 1) Valid '
          items:
            $ref: '#/components/schemas/NTPServer'
          type: array
        tags:
          description: Tags
          items:
            description: Tags
            type: string
          type: array
      required:
      - ntp_servers
      - name
    NtpLastSelected:
      properties:
        delta:
          description: Delta
          format: float
          type: number
        error:
          description: Error
          type: string
        ip:
          description: Ip
          type: string
        old_drift:
          description: Old Drift
          format: float
          type: number
        slop:
          description: Slop
          format: float
          type: number
        stratum:
          description: Stratum
          format: int32
          type: integer
        time_stamp:
          description: Time Stamp
          type: string
        update_after:
          description: Update After
          type: string
        update_before:
          description: Update Before
          type: string
        update_drift:
          description: Update Drift
          format: float
          type: number
info:
  contact: {}
  description: List of APIs used to manage NTP.
  title: NTP
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/elements/{element_id}/ntp:
    get:
      description: Get all element NTP
      operationId: get-sdwan-v2.0-api-elements-element_id-ntp
      parameters:
      - description: Element ID
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/ElementNTP'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get all element NTP (v2.0)
      tags:
      - NTP
  /sdwan/v2.0/api/elements/{element_id}/ntp/{ntp_id}:
    get:
      description: Get specific element NTP
      operationId: get-sdwan-v2.0-api-elements-element_id-ntp-ntp_id
      parameters:
      - description: Element ID
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: NTP ID
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTP'
          description: Successful Operation
      summary: Get specific element NTP (v2.0)
      tags:
      - NTP
    put:
      description: Update an existing element NTP.
      operationId: put-sdwan-v2.0-api-elements-element_id-ntp-ntp_id
      parameters:
      - description: Element ID
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: NTP ID
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElementNTP'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTP'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: NTP_CONFIG_UNSUPPORTED_SWVERSION
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: NTP_CONFIG_INVALID_INTERFACE_IDS
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update an existing element NTP. (v2.0)
      tags:
      - NTP
  /sdwan/v2.0/api/elements/{element_id}/ntp/{ntp_id}/status:
    get:
      description: Get specific element NTP
      operationId: get-sdwan-v2.0-api-elements-element_id-ntp-ntp_id-status
      parameters:
      - description: Element ID
        in: path
        name: element_id
        required: true
        schema:
          description: Element Id
          type: string
      - description: NTP ID
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElementNTPState'
          description: Successful Operation
      summary: Get specific element NTP (v2.0)
      tags:
      - NTP
  /sdwan/v2.0/api/templates/ntp:
    get:
      description: Get all existing NTP Template of tenant.
      operationId: get-sdwan-v2.0-api-templates-ntp
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/NTPTemplate'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get all existing NTP Template of tenant. (v2.0)
      tags:
      - NTP
    post:
      description: Create a new NTP Template
      operationId: post-sdwan-v2.0-api-templates-ntp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NTPTemplate'
        description: Details of the NTP template to be created
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: NTP_CONFIG_DUPLICATE_DEFAULT_TEMPLATE
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create a new NTP Template (v2.0)
      tags:
      - NTP
  /sdwan/v2.0/api/templates/ntp/{ntp_id}:
    delete:
      description: Delete an existing NTP Template
      operationId: delete-sdwan-v2.0-api-templates-ntp-ntp_id
      parameters:
      - description: NTP Id
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '203':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful operation
      summary: Delete an existing NTP Template (v2.0)
      tags:
      - NTP
    get:
      description: Get an existing NTP Template
      operationId: get-sdwan-v2.0-api-templates-ntp-ntp_id
      parameters:
      - description: NTP Id
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
      summary: Get an existing NTP Template (v2.0)
      tags:
      - NTP
    put:
      description: Update an existing NTP Template
      operationId: put-sdwan-v2.0-api-templates-ntp-ntp_id
      parameters:
      - description: NTP Id
        in: path
        name: ntp_id
        required: true
        schema:
          description: Ntp Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NTPTemplate'
        description: Details of the NTP template to be updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NTPTemplate'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
                  - code: NTP_CONFIG_DUPLICATE_DEFAULT_TEMPLATE
                  - code: NTP_CONFIG_INVALID_SERVER_LIST
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update an existing NTP Template (v2.0)
      tags:
      - NTP
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: NTP
