components:
  schemas:
    FolderScreen:
      properties:
        dest_page:
          description: 'The destination page.

            '
          format: int32
          type: integer
        folder:
          description: 'The requested folder name.

            '
          type: string
        id:
          description: 'The ID.

            '
          type: string
        limit:
          description: 'The requested pagination limit.

            '
          format: int32
          type: integer
    ListResponse:
      properties:
        count:
          description: 'The actual count.

            '
          format: int32
          type: integer
        id:
          description: 'The ID.

            '
          type: string
      type: object
    ReportListItem:
      properties:
        id:
          description: 'The ID.

            '
          type: string
        modifiedTime:
          description: 'The folder modified time.

            '
          format: int64
          type: integer
        name:
          description: 'The folder name.

            '
          type: string
        path:
          description: 'The folder path.

            '
          type: string
        size:
          description: 'The folder size.

            '
          format: int64
          type: integer
        type:
          description: 'The folder type.

            '
          type: string
info:
  contact: {}
  description: List of APIs used to generate reports.
  title: Reports
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/reports:
    get:
      description: List all the report files.
      operationId: get-sdwan-v2.0-api-reports
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: binary
                type: string
          description: Successful Operation
      summary: Get Report Files (v2.0)
      tags:
      - Reports
  /sdwan/v2.0/api/reports/query:
    post:
      description: Query all the report files.
      operationId: post-sdwan-v2.0-api-reports-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderScreen'
      responses:
        '200':
          content:
            text/plain:
              schema:
                format: binary
                type: string
          description: Successful Operation
      summary: Query Report Files (v2.0)
      tags:
      - Reports
  /sdwan/v2.0/api/reportsdir:
    get:
      description: List all the report files and folders in a specific folder.
      operationId: get-sdwan-v2.0-api-reportsdir
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/ReportListItem'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get Report Files in Specified Folder (v2.0)
      tags:
      - Reports
  /sdwan/v2.0/api/reportsdir/query:
    post:
      description: Query all the report files and folders in a specific folder.
      operationId: post-sdwan-v2.0-api-reportsdir-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderScreen'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/ReportListItem'
                      type: array
                  type: object
          description: Successful Operation
      summary: Query Report Files in Specified Folder (v2.0)
      tags:
      - Reports
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Reports
