components:
  schemas:
    Aggregate:
      properties:
        data:
          description: Data
          items:
            $ref: '#/components/schemas/AggregateData'
          type: array
        field:
          description: Field
          type: string
        name:
          description: Name
          type: string
        operator:
          description: Operator
          enum:
          - max
          - count
          - min
          - avg
          - sum
          type: string
        statistic:
          description: Statistic
          type: string
        unit:
          description: Unit
          type: string
    AggregateData:
      properties:
        value:
          description: 'Value: JsonInclude(content = ALWAYS, contentFilter = classOf[Void],
            value = ALWAYS, valueFilter = classOf[Void]) '
          type: number
        view:
          type: object
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The actual count.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number.

            '
          format: int64
          type: integer
      type: object
    SnapshotExport:
      properties:
        id:
          description: Id
          type: string
        site_id:
          description: Site Id
          type: string
        snapshot_name:
          description: Snapshot Name
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
        yaml_configuration:
          description: Yaml Configuration
          type: string
    SnapshotExportQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: Aggregate
        dest_page:
          description: Dest Page
          format: int32
          type: integer
        getDeleted:
          description: GetDeleted
          type: boolean
        group_by:
          description: Group By
          items:
            description: Group By
            type: string
          type: array
        id:
          description: Id
          type: string
        isReadPreferenceSecondary:
          description: 'IsReadPreferenceSecondary: JsonIgnore(value = true) '
          type: boolean
        last_query_ts:
          description: Last Query Ts
          format: int64
          type: integer
        limit:
          description: Limit
          format: int32
          type: integer
        next_query:
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: Retrieved Fields
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: Retrieved Fields Mask
          type: boolean
        sort_case_insensitive:
          description: Sort Case Insensitive
          type: boolean
        sort_params:
          type: object
        total_count:
          description: Total Count
          format: int64
          type: integer
    SnapshotExportQueryFilter:
      properties:
        id:
          description: Id
          type: string
        site_id:
          description: Site Id
          type: string
        snapshot_name:
          description: Snapshot Name
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
        yaml_configuration:
          description: Yaml Configuration
          type: string
    SnapshotExportScreen:
      properties:
        id:
          description: Id
          type: string
        snapshot_name:
          description: Snapshot Name
          type: string
    SnapshotExportScreenResponse:
      properties:
        id:
          description: Id
          type: string
        site_id:
          description: Site Id
          type: string
        snapshot_name:
          description: Snapshot Name
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
    SnapshotExportStatus:
      properties:
        id:
          description: Id
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
    SnapshotImport:
      properties:
        id:
          description: Id
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
        yaml_name:
          description: Yaml Name
          type: string
    SnapshotImportQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: Aggregate
        dest_page:
          description: Dest Page
          format: int32
          type: integer
        getDeleted:
          description: GetDeleted
          type: boolean
        group_by:
          description: Group By
          items:
            description: Group By
            type: string
          type: array
        id:
          description: Id
          type: string
        isReadPreferenceSecondary:
          description: 'IsReadPreferenceSecondary: JsonIgnore(value = true) '
          type: boolean
        last_query_ts:
          description: Last Query Ts
          format: int64
          type: integer
        limit:
          description: Limit
          format: int32
          type: integer
        next_query:
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: Retrieved Fields
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: Retrieved Fields Mask
          type: boolean
        sort_case_insensitive:
          description: Sort Case Insensitive
          type: boolean
        sort_params:
          type: object
        total_count:
          description: Total Count
          format: int64
          type: integer
    SnapshotImportQueryFilter:
      properties:
        id:
          description: Id
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
        yaml_name:
          description: Yaml Name
          type: string
    SnapshotImportResponseScreen:
      properties:
        id:
          description: Id
          type: string
        status:
          description: Status
          type: string
        status_description:
          description: Status Description
          type: string
        yaml_configuration:
          description: Yaml Configuration
          type: string
        yaml_name:
          description: Yaml Name
          type: string
    SnapshotImportScreen:
      properties:
        id:
          description: Id
          type: string
        yaml_configuration:
          description: Yaml Configuration
          type: string
info:
  contact: {}
  description: APIs to manage and query site snapshots.
  title: Site Snapshots
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/sites/snapshots/query:
    post:
      description: Get all site exports with filtering and pagination.
      operationId: post-sdwan-v2.0-api-sites-snapshots-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotExportQuery'
        description: Query parameters for filtering exports
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/SnapshotExportQueryFilter'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_PARAM
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query Export Jobs (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sites/{site_id}/snapshots:
    post:
      description: Create or retry a site configuration export to YAML.
      operationId: post-sdwan-v2.0-api-sites-site_id-snapshots
      parameters:
      - description: Site ID.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotExportScreen'
        description: Site export configuration details
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotExportScreenResponse'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON
                  - code: SITE_ID_REQUIRED
                  - code: EXPORT_ALREADY_IN_PROGRESS
                  - code: INVALID_SITEID
                  - code: EXPORT_SNAPSHOT_NOT_ALLOWED_ON_SHELL
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Generate Snapshot Of Site (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sites/{site_id}/snapshots/{id}:
    get:
      description: Get specific site export details by export ID.
      operationId: get-sdwan-v2.0-api-sites-site_id-snapshots-id
      parameters:
      - description: Site ID.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: Export ID.
        in: path
        name: id
        required: true
        schema:
          description: Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotExport'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_PARAM
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Retrieve YAML Configuration By ID (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sites/{site_id}/snapshots/{id}/status:
    get:
      description: Get the current status of the site export job.
      operationId: get-sdwan-v2.0-api-sites-site_id-snapshots-id-status
      parameters:
      - description: The ID of the site.
        in: path
        name: site_id
        required: true
        schema:
          description: Site Id
          type: string
      - description: The snapshot export ID.
        in: path
        name: id
        required: true
        schema:
          description: Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotExportStatus'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_PARAM
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get Snapshot Job Status (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sitesnapshots:
    post:
      description: Import YAML snapshot configuration for deployment.
      operationId: post-sdwan-v2.0-api-sitesnapshots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotImportScreen'
        description: YAML snapshot data for import
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotImportResponseScreen'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_JSON
                  - code: EXPORT_ALREADY_IN_PROGRESS
                  - code: INVALID_YAML_NAME
                  - code: INVALID_YAML
                  - code: YAML_SYNTAX_INVALID
                  - code: RESOURCE_VERSION_UNSUPPORTED
                  - code: SITES_NOT_FOUND
                  - code: SITES_COUNT_INVALID
                  - code: SITE_ADDRESS_MISSING
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create Site Deployment (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sitesnapshots/query:
    post:
      description: Get all snapshot imports with filtering and pagination.
      operationId: post-sdwan-v2.0-api-sitesnapshots-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotImportQuery'
        description: Query parameters for filtering snapshots
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/SnapshotImportQueryFilter'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INPUT_JSON_EMPTY
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query Import Jobs With Filters (v2.0)
      tags:
      - Site Snapshots
  /sdwan/v2.0/api/sitesnapshots/{id}:
    get:
      description: Get specific snapshot import details by ID.
      operationId: get-sdwan-v2.0-api-sitesnapshots-id
      parameters:
      - description: Snapshot Import ID
        in: path
        name: id
        required: true
        schema:
          description: Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotImport'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: INVALID_REQUEST_PARAM
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Retrieve Deployment Status By ID (v2.0)
      tags:
      - Site Snapshots
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Site Snapshots
