components:
  schemas:
    Aggregate:
      properties:
        field:
          description: Field
          type: string
        operator:
          description: Operator
          enum:
          - max
          - count
          - min
          - avg
          - sum
          type: string
    BulkResponse:
      properties:
        count:
          description: 'The total number.

            '
          format: int32
          type: integer
        id:
          description: 'The ID.

            '
          type: string
        type:
          description: "The type. \n"
          type: string
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The count of the query list.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number.

            '
          format: int64
          type: integer
      type: object
    VPLAdminState:
      properties:
        al_id:
          description: Al Id
          type: string
        enabled:
          description: 'The enabled states on a VPN link.

            '
          type: boolean
        id:
          description: 'The ID of the VPN link.

            '
          type: string
    VPLOperations:
      properties:
        action:
          description: 'The actions performed on a VPN link.

            '
          enum:
          - refresh_vpnlink_status
          type: string
        id:
          description: 'The ID of the VPN link.

            '
          type: string
    VPLOperationsScreen:
      properties:
        action:
          description: 'The actions performed on a VPN link.

            '
          enum:
          - refresh_vpnlink_status
          type: string
        id:
          description: 'The ID of the VPN link.

            '
          type: string
    VPLStatus:
      properties:
        common_cipher:
          description: Common Cipher
          type: string
        ep1_cipher:
          description: Ep1 Cipher
          type: string
        ep1_element_id:
          description: Ep1 Element Id
          type: string
        ep1_interface_id:
          description: Ep1 Interface Id
          type: string
        ep1_site_id:
          description: Ep1 Site Id
          type: string
        ep2_cipher:
          description: Ep2 Cipher
          type: string
        ep2_element_id:
          description: Ep2 Element Id
          type: string
        ep2_interface_id:
          description: Ep2 Interface Id
          type: string
        ep2_site_id:
          description: Ep2 Site Id
          type: string
        id:
          description: Id
          type: string
    VPLStatusV2N1:
      properties:
        active:
          description: Active
          type: boolean
        common_cipher:
          description: Common Cipher
          type: string
        ep1_cipher:
          description: Ep1 Cipher
          type: string
        ep1_element_id:
          description: Ep1 Element Id
          type: string
        ep1_interface_id:
          description: Ep1 Interface Id
          type: string
        ep1_keep_alive_failure_count:
          description: Ep1 Keep Alive Failure Count
          type: integer
        ep1_keep_alive_interval:
          description: Ep1 Keep Alive Interval
          type: integer
        ep1_site_id:
          description: Ep1 Site Id
          type: string
        ep2_cipher:
          description: Ep2 Cipher
          type: string
        ep2_element_id:
          description: Ep2 Element Id
          type: string
        ep2_interface_id:
          description: Ep2 Interface Id
          type: string
        ep2_keep_alive_failure_count:
          description: Ep2 Keep Alive Failure Count
          type: integer
        ep2_keep_alive_interval:
          description: Ep2 Keep Alive Interval
          type: integer
        ep2_site_id:
          description: Ep2 Site Id
          type: string
        id:
          description: Id
          type: string
        link_up:
          description: Link Up
          type: boolean
        usable:
          description: Usable
          type: boolean
    VPNLinkQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: 'The aggregate number of VPN links that match the query parameters.

            '
        dest_page:
          description: 'The destination page.

            '
          format: int32
          type: integer
        getDeleted:
          description: 'The number of VPN links deleted for a time frame.

            '
          type: boolean
        group_by:
          description: 'Group the VPN links for the query.

            '
          items:
            description: Group By
            type: string
          type: array
        id:
          description: "Lists the VPN links by ID.    \n"
          type: string
        last_query_ts:
          description: 'Return the ID of a specified query in the current session.

            '
          format: int64
          type: integer
        limit:
          description: 'The query limit.

            '
          format: int32
          type: integer
        next_query:
          description: 'The  limit.

            '
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: 'Retrieve information from a field.

            '
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: 'List the fields to query.

            '
          type: boolean
        sort_params:
          type: object
        total_count:
          description: 'The total number of query parameters.

            '
          format: int64
          type: integer
    WanOverlay:
      properties:
        description:
          description: 'The WAN overlay config description. Max size = 256.

            '
        id:
          description: 'The ID of the WAN overlay.

            '
          type: string
        name:
          description: 'The WAN overlay config name. Max size = 128.

            '
          type: string
        vni:
          description: "The VNI value. \n"
          format: int32
          type: integer
      required:
      - vni
      - name
info:
  contact: {}
  description: List of APIs used to manage the network topology, WAN Overlays, VPN
    Links, and Secure Fabric Links.
  title: Topology
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/vpnlinks/query:
    post:
      description: Query DB for VPN links that match query parameters.
      operationId: post-sdwan-v2.0-api-vpnlinks-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPNLinkQuery'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/VPNLinkQuery'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query DB for VPN Links (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/operations:
    post:
      description: Perform an operation on a VPN link.
      operationId: post-sdwan-v2.0-api-vpnlinks-vpn_link_id-operations
      parameters:
      - description: The ID of the VPN link.
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPLOperationsScreen'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLOperations'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
                  - code: VPNLINK_INVALID_ACTION
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Perform Operation on VPN Link (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/state:
    get:
      description: List the admin state of the VPN link.
      operationId: get-sdwan-v2.0-api-vpnlinks-vpn_link_id-state
      parameters:
      - description: The ID of the VPN link.
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLAdminState'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get VPN Link Admin State (v2.0)
      tags:
      - Topology
    put:
      description: Update the admin state of the VPN link.
      operationId: put-sdwan-v2.0-api-vpnlinks-vpn_link_id-state
      parameters:
      - description: The ID of the VPN link.
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPLAdminState'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLAdminState'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: ANYNET_VPL_ADMINSTATE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update VPN Link Admin State (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/status:
    get:
      description: List the status of the VPN link.
      operationId: get-sdwan-v2.0-api-vpnlinks-vpn_link_id-status
      parameters:
      - description: The ID of the VPN link.
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLStatus'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get VPN Link Status (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/wanoverlays:
    get:
      description: List the app/wan contexts.
      operationId: get-sdwan-v2.0-api-wanoverlays
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/WanOverlay'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get App/WAN Contexts (v2.0)
      tags:
      - Topology
    post:
      description: Create a new app/wan context.
      operationId: post-sdwan-v2.0-api-wanoverlays
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WanOverlay'
        description: Details of the appwan context to be created
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: WANOVERLAY_CONFIG_NAME_REQD
                  - code: NAME_EXCEEDS_LIMIT
                  - code: VNI_REQD
                  - code: INVALID_VNI_VALUE
                  - code: WANOVERLAY_CONFIG_DESCRIPTION_INVALID
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: WAN_CONTEXT_ADD_FAILED
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create App/WAN Context (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/wanoverlays/{wan_overlay_id}:
    delete:
      description: Create a new app/wan context.
      operationId: delete-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: The ID of the WAN overlay.
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: WANOVERLAY_IN_USE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Delete App/WAN Context (v2.0)
      tags:
      - Topology
    get:
      description: List the new app/wan context.
      operationId: get-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: The ID of the WAN overlay.
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: APPWAN_CONTEXT_DOES_NOT_EXIST
                  - code: APPWAN_CONTEXT_NAME_INVALID
                  - code: APPWAN_CONTEXT_DESCRIPTION_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get App/WAN Context (v2.0)
      tags:
      - Topology
    put:
      description: Update a new app/wan context.
      operationId: put-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: The ID of the WAN overlay.
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WanOverlay'
        description: Details of the appwan context to be updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: APPWAN_CONTEXT_DOES_NOT_EXIST
                  - code: WANOVERLAY_CONFIG_NAME_REQD
                  - code: NAME_EXCEEDS_LIMIT
                  - code: VNI_REQD
                  - code: INVALID_VNI_VALUE
                  - code: WANOVERLAY_CONFIG_DESCRIPTION_INVALID
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update App/WAN Context (v2.0)
      tags:
      - Topology
  /sdwan/v2.1/api/vpnlinks/{vpn_link_id}/status:
    get:
      description: List the status of the VPN link.
      operationId: get-sdwan-v2.1-api-vpnlinks-vpn_link_id-status
      parameters:
      - description: The ID of the VPN link.
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLStatusV2N1'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get VPN Link Status (v2.1)
      tags:
      - Topology
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Topology
