components:
  schemas:
    Aggregate:
      properties:
        field:
          description: Field
          type: string
        operator:
          description: Operator
          enum:
          - max
          - count
          - min
          - avg
          - sum
          type: string
    BulkResponse:
      properties:
        count:
          description: 'The total number.

            '
          format: int32
          type: integer
        id:
          description: 'The ID.

            '
          type: string
        type:
          description: "The type. \n"
          type: string
    Error:
      properties:
        _error:
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
    ErrorResponse:
      properties:
        code:
          type: string
        message:
          type: string
    ListQueryResponse:
      properties:
        count:
          description: 'The actual count.

            '
          format: int32
          type: integer
        deleted_count:
          description: 'The deleted number.

            '
          format: int64
          type: integer
        deleted_ids:
          description: 'The deleted IDs.

            '
          items:
            type: string
          type: array
        description:
          description: 'Description of the query. Max size = 256.

            '
        id:
          description: 'The ID.

            '
          type: string
        next_query:
          description: 'Details of the next query.

            '
          type: object
        total_count:
          description: 'Total number.

            '
          format: int64
          type: integer
      type: object
    VPLAdminState:
      properties:
        al_id:
          description: Al Id
          type: string
        enabled:
          description: Enabled
          type: boolean
        id:
          description: Id
          type: string
    VPLOperations:
      properties:
        action:
          description: Action
          enum:
          - refresh_vpnlink_status
          type: string
        id:
          description: Id
          type: string
    VPLOperationsScreen:
      properties:
        action:
          description: Action
          enum:
          - refresh_vpnlink_status
          type: string
        id:
          description: Id
          type: string
    VPLStatus:
      properties:
        common_cipher:
          description: Common Cipher
          type: string
        ep1_cipher:
          description: Ep1 Cipher
          type: string
        ep1_element_id:
          description: Ep1 Element Id
          type: string
        ep1_interface_id:
          description: Ep1 Interface Id
          type: string
        ep1_site_id:
          description: Ep1 Site Id
          type: string
        ep2_cipher:
          description: Ep2 Cipher
          type: string
        ep2_element_id:
          description: Ep2 Element Id
          type: string
        ep2_interface_id:
          description: Ep2 Interface Id
          type: string
        ep2_site_id:
          description: Ep2 Site Id
          type: string
        id:
          description: Id
          type: string
    VPLStatusV2N1:
      properties:
        active:
          description: Active
          type: boolean
        common_cipher:
          description: Common Cipher
          type: string
        ep1_cipher:
          description: Ep1 Cipher
          type: string
        ep1_element_id:
          description: Ep1 Element Id
          type: string
        ep1_interface_id:
          description: Ep1 Interface Id
          type: string
        ep1_keep_alive_failure_count:
          description: Ep1 Keep Alive Failure Count
          type: integer
        ep1_keep_alive_interval:
          description: Ep1 Keep Alive Interval
          type: integer
        ep1_site_id:
          description: Ep1 Site Id
          type: string
        ep2_cipher:
          description: Ep2 Cipher
          type: string
        ep2_element_id:
          description: Ep2 Element Id
          type: string
        ep2_interface_id:
          description: Ep2 Interface Id
          type: string
        ep2_keep_alive_failure_count:
          description: Ep2 Keep Alive Failure Count
          type: integer
        ep2_keep_alive_interval:
          description: Ep2 Keep Alive Interval
          type: integer
        ep2_site_id:
          description: Ep2 Site Id
          type: string
        id:
          description: Id
          type: string
        link_up:
          description: Link Up
          type: boolean
        usable:
          description: Usable
          type: boolean
    VPNLinkQuery:
      properties:
        aggregate:
          $ref: '#/components/schemas/Aggregate'
          description: Aggregate
        dest_page:
          description: Dest Page
          format: int32
          type: integer
        getDeleted:
          description: GetDeleted
          type: boolean
        group_by:
          description: Group By
          items:
            description: Group By
            type: string
          type: array
        id:
          description: Id
          type: string
        last_query_ts:
          description: Last Query Ts
          format: int64
          type: integer
        limit:
          description: Limit
          format: int32
          type: integer
        next_query:
          type: object
        query_params:
          type: object
        retrieved_fields:
          description: Retrieved Fields
          items:
            description: Retrieved Fields
            type: string
          type: array
        retrieved_fields_mask:
          description: Retrieved Fields Mask
          type: boolean
        sort_params:
          type: object
        total_count:
          description: Total Count
          format: int64
          type: integer
    WanOverlay:
      properties:
        description:
          description: 'Description: Size(max = 256, error = WANOVERLAY_CONFIG_DESCRIPTION_INVALID:
            Wan overlay config description invalid., min = 0) '
          type: string
        id:
          description: Id
          type: string
        name:
          description: 'Name: Required(error = WANOVERLAY_CONFIG_NAME_REQD: WAN Overlay
            name required.) Size(max = 128, error = NAME_EXCEEDS_LIMIT: Name of the
            resource exceeds limit., min = 0) '
          type: string
        vni:
          description: 'Vni: Required(error = VNI_REQD: VNI is a mandatory property.)
            Range(max = 64511L, error = INVALID_VNI_VALUE: VNI is invalid. It should
            be between 0 to 64511., min = 0L) '
          format: int32
          type: integer
      required:
      - vni
      - name
info:
  contact: {}
  description: List of APIs used to manage the network topology, WAN Overlays, VPN
    Links, and Secure Fabric Links.
  title: Topology
  version: Latest
openapi: 3.0.0
paths:
  /sdwan/v2.0/api/vpnlinks/query:
    post:
      description: Query db for VPNLinks that match query parameters
      operationId: post-sdwan-v2.0-api-vpnlinks-query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPNLinkQuery'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ListQueryResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/VPNLinkQuery'
                      type: array
                  type: object
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Query db for VPNLinks that match query parameters (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/operations:
    post:
      description: Perform an operation on a VPN link
      operationId: post-sdwan-v2.0-api-vpnlinks-vpn_link_id-operations
      parameters:
      - description: VPN Link Id
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPLOperationsScreen'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLOperations'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
                  - code: VPNLINK_INVALID_ACTION
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Perform an operation on a VPN link (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/state:
    get:
      description: Get the VPNLink admin state
      operationId: get-sdwan-v2.0-api-vpnlinks-vpn_link_id-state
      parameters:
      - description: VPN Link Id
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLAdminState'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get the VPNLink admin state (v2.0)
      tags:
      - Topology
    put:
      description: Change the VPNLink admin state
      operationId: put-sdwan-v2.0-api-vpnlinks-vpn_link_id-state
      parameters:
      - description: VPN Link Id
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPLAdminState'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLAdminState'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: ANYNET_VPL_ADMINSTATE_NOT_FOUND
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Change the VPNLink admin state (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/vpnlinks/{vpn_link_id}/status:
    get:
      description: Get the VPNLink status
      operationId: get-sdwan-v2.0-api-vpnlinks-vpn_link_id-status
      parameters:
      - description: VPN Link Id
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLStatus'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get the VPNLink status (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/wanoverlays:
    get:
      description: Get app/wan contexts
      operationId: get-sdwan-v2.0-api-wanoverlays
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/BulkResponse'
                - properties:
                    items:
                      items:
                        $ref: '#/components/schemas/WanOverlay'
                      type: array
                  type: object
          description: Successful Operation
      summary: Get app/wan contexts (v2.0)
      tags:
      - Topology
    post:
      description: Create a new app/wan context
      operationId: post-sdwan-v2.0-api-wanoverlays
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WanOverlay'
        description: Details of the appwan context to be created
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: WANOVERLAY_CONFIG_NAME_REQD
                  - code: NAME_EXCEEDS_LIMIT
                  - code: VNI_REQD
                  - code: INVALID_VNI_VALUE
                  - code: WANOVERLAY_CONFIG_DESCRIPTION_INVALID
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: WAN_CONTEXT_ADD_FAILED
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Create a new app/wan context (v2.0)
      tags:
      - Topology
  /sdwan/v2.0/api/wanoverlays/{wan_overlay_id}:
    delete:
      description: Delete app/wan context
      operationId: delete-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: WanOverlays ID
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: WANOVERLAY_IN_USE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Delete app/wan context (v2.0)
      tags:
      - Topology
    get:
      description: Get app/wan context
      operationId: get-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: WanOverlays ID
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: APPWAN_CONTEXT_DOES_NOT_EXIST
                  - code: APPWAN_CONTEXT_NAME_INVALID
                  - code: APPWAN_CONTEXT_DESCRIPTION_INVALID
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get app/wan context (v2.0)
      tags:
      - Topology
    put:
      description: Update app/wan context
      operationId: put-sdwan-v2.0-api-wanoverlays-wan_overlay_id
      parameters:
      - description: WanOverlays ID
        in: path
        name: wan_overlay_id
        required: true
        schema:
          description: Wan Overlay Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WanOverlay'
        description: Details of the appwan context to be updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WanOverlay'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: APPWAN_CONTEXT_DOES_NOT_EXIST
                  - code: WANOVERLAY_CONFIG_NAME_REQD
                  - code: NAME_EXCEEDS_LIMIT
                  - code: VNI_REQD
                  - code: INVALID_VNI_VALUE
                  - code: WANOVERLAY_CONFIG_DESCRIPTION_INVALID
                  - code: INVALID_JSON_EXTRA_ATTRIBUTE
                  - code: INVALID_JSON_COMMON_ATTR_MISMATCH
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Update app/wan context (v2.0)
      tags:
      - Topology
  /sdwan/v2.1/api/vpnlinks/{vpn_link_id}/status:
    get:
      description: Get the VPNLink status
      operationId: get-sdwan-v2.1-api-vpnlinks-vpn_link_id-status
      parameters:
      - description: VPN Link Id
        in: path
        name: vpn_link_id
        required: true
        schema:
          description: Vpn Link Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPLStatusV2N1'
          description: Successful Operation
        '400':
          content:
            application/json:
              example:
                value:
                  _error:
                  - code: VPL_NOT_FOUND
                  - code: VPL_ACTION_INSUFFICIENT_VPE
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: Get the VPNLink status (v2.1)
      tags:
      - Topology
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Topology
