module.exports = {
  prismacloudapi: [
    "prisma-cloud/api/api-reference-home",
    {
      type: "category",
      label: "Cloud Security Posture Management",
      collapsed: true,
      items: [
        "prisma-cloud/api/cspm/cspm-api",
        "prisma-cloud/api/cspm/api-urls",
        "prisma-cloud/api/cspm/api-headers",
        "prisma-cloud/api/cspm/rate-limits",
        "prisma-cloud/api/cspm/api-time-range-model",
        "prisma-cloud/api/cspm/api-integration-config",
        "prisma-cloud/api/cspm/api-errors",
        require("./api/cspm/sidebar"),
      ],
    },
    {
      type: "category",
      label: "Cloud Workload Protection",
      collapsed: true,
      items: [
        "prisma-cloud/api/cwpp/cwpp-home",
        "prisma-cloud/api/cwpp/access-api-saas",
        "prisma-cloud/api/cwpp/stable-endpoints",
        require("./api/cwpp/sidebar"),
      ],
    },
    {
      type: "category",
      label: "Cloud Application Security",
      collapsed: true,
      items: [
        "prisma-cloud/api/code/code",
        "prisma-cloud/api/code/basic-request",
        "prisma-cloud/api/code/api-headers",
        require("./api/code/sidebar"),
      ],
    },
  ],
  clouddocs: [
    "prisma-cloud/docs/home",
    {
      type: "category",
      label: "Cloud Security Posture Management",
      items: [
        {
          type: "autogenerated",
          dirName: "prisma-cloud/docs/cspm",
        },
      ],
    },
    {
      type: "category",
      label: "Cloud Workload Protection Platform",
      items: [
        {
          type: "autogenerated",
          dirName: "prisma-cloud/docs/cwpp",
        },
      ],
    },
    {
      type: "category",
      label: "Other Documentation",
      items: [
        {
          type: "link",
          label: "Administrator's Guide (Enterprise Edition - Classic)",
          href: "https://docs.prismacloud.io/en/classic/cspm-admin-guide",
        },
        {
          type: "link",
          label: "Content Collections (Enterprise Edition)",
          href: "https://docs.prismacloud.io/en/enterprise-edition/content-collections",
        },

        {
          type: "link",
          label: "Release Information",
          href: "https://docs.prismacloud.io/en/enterprise-edition/rn",
        },
        {
          type: "link",
          label: "Resource Query Language (RQL)",
          href: "https://docs.prismacloud.io/en/classic/rql-reference",
        },
        "prisma-cloud/docs/twistcli_gs",
        {
          type: "category",
          label: "RQL",
          items: [
            {
              type: "autogenerated",
              dirName: "prisma-cloud/docs/rql",
            },
          ],
        },
        {
          type: "category",
          label: "Terraform Provider",
          items: [
            {
              type: "autogenerated",
              dirName: "prisma-cloud/docs/tf",
            },
          ],
        },
        {
          type: "category",
          label: "Compute 32.00",
          items: [
            {
              type: "link",
              label: "Administrator's Guide",
              href: "https://docs.prismacloud.io/en/compute-edition/32/admin-guide",
            },
            {
              type: "link",
              label: "Release Notes",
              href: "https://docs.prismacloud.io/en/compute-edition/32/rn/release-information/release-notes-32-00",
            },
          ],
        },
        {
          type: "category",
          label: "Compute 31.03",
          items: [
            {
              type: "link",
              label: "Administrator's Guide",
              href: "https://docs.prismacloud.io/en/compute-edition/31/admin-guide",
            },
            {
              type: "link",
              label: "Release Notes",
              href: "https://docs.prismacloud.io/en/compute-edition/31/rn/release-information/release-notes-31-03-update3",
            },
          ],
        },
        {
          type: "category",
          label: "Compute 30.03",
          items: [
            {
              type: "link",
              label: "Administrator's Guide",
              href: "https://docs.prismacloud.io/en/compute-edition/30/admin-guide",
            },
            {
              type: "link",
              label: "Release Notes",
              href: "https://docs.prismacloud.io/en/compute-edition/30/rn/release-information/release-notes-30-03-update3",
            },
          ],
        },
        {
          type: "category",
          label: "CWPP",
          items: [
            {
              type: "link",
              label: "Administrator's Guide",
              href: "https://docs.prismacloud.io/en/enterprise-edition/content-collections",
            },
          ],
        },
      ],
    },
  ],
};
