module.exports = [
  {
    type: "category",
    label: "AddressGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-address-groups",
        label: "Get all address groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-address-groups",
        label: "Create an address group",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-address-groups-id",
        label: "Delete an address group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-address-groups-id",
        label: "Get an address group by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-address-groups-id",
        label: "Edit an address group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Addresses",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-addresses",
        label: "List addresses",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-addresses",
        label: "Create an address",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-addresses-id",
        label: "Delete an address",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-addresses-id",
        label: "Get an address by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-addresses-id",
        label: "Edit an address",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AntiSpywareProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-anti-spyware-profiles",
        label: "List all anti-spyware profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-anti-spyware-profiles",
        label: "Create an anti-spyware profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-anti-spyware-profiles-id",
        label: "Delete an Anti-spyware profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-anti-spyware-profiles-id",
        label: "Get an anti-spyware profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-anti-spyware-profiles-id",
        label: "Edit an Anti-spyware profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AntiSpywareSignatures",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-anti-spyware-signatures",
        label: "List all anti-spyware signatures",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-anti-spyware-signatures",
        label: "Create an anti-spyware signature",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-anti-spyware-signatures-id",
        label: "Delete an Anti-spyware signature",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-anti-spyware-signatures-id",
        label: "Edit an Anti-spyware signature",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ApplicationFilters",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-application-filters",
        label: "List application filters",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-application-filters",
        label: "Create an application filter",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-application-filters-id",
        label: "Delete an application filter",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-application-filters-id",
        label: "Get an application filter by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-application-filters-id",
        label: "Edit an application filter",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ApplicationGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-application-groups",
        label: "List application groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-application-groups",
        label: "Create an application group",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-application-groups-id",
        label: "Delete an application group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-application-groups-id",
        label: "Get an application group by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-application-groups-id",
        label: "Edit an application group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ApplicationOverrideRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-app-override-rules",
        label: "List all application override rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-app-override-rules",
        label: "Create an application override rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-app-override-rules-id",
        label: "Delete an application override rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-app-override-rules-id",
        label: "Get an application override rule by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-app-override-rules-id",
        label: "Edit an application override rule",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-app-override-rules-id-move",
        label: "Move an app override rule",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Applications",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-applications",
        label: "List applications",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-applications",
        label: "Create an application",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-applications-id",
        label: "Delete an application",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-applications-id",
        label: "Get an application by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-applications-id",
        label: "Edit an application",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AuthenticationPortals",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-portals",
        label: "List all authentication portals",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-authentication-portals",
        label: "Create an authentication portal",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-authentication-portals-id",
        label: "Delete a authentication portal",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-authentication-portals-id",
        label: "Edit a authentication portal",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AuthenticationProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-profiles",
        label: "List all authentication profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-authentication-profiles",
        label: "Create an authentication profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-authentication-profiles-id",
        label: "Delete a authentication profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-profiles-id",
        label: "Get an authentication profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-authentication-profiles-id",
        label: "Edit a authentication profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AuthenticationRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-rules",
        label: "List all authentication rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-authentication-rules",
        label: "Create an authentication rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-authentication-rules-id",
        label: "Delete a authentication rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-authentication-rules-id",
        label: "Edit a authentication rule",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-authentication-rules-id-move",
        label: "Move an authentication rule",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "AuthenticationSequences",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-sequences",
        label: "List all authentication sequence",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-authentication-sequences",
        label: "Create an authentication sequence",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-authentication-sequences-id",
        label: "Delete a authentication sequence",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-authentication-sequences-id",
        label: "Get an authentication sequence",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-authentication-sequences-id",
        label: "Edit a authentication sequence",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "AutoTagActions",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-auto-tag-actions",
        label: "Delete auto tag actions",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-auto-tag-actions",
        label: "List auto tag actions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-auto-tag-actions",
        label: "Create auto tag actions",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-auto-tag-actions",
        label: "Edit auto tag actions",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "BandwidthAllocations",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-bandwidth-allocations",
        label: "Delete an aggregated bandwidth region",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-bandwidth-allocations",
        label: "List aggregated bandwidth regions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-bandwidth-allocations",
        label: "Create aggregated bandwidth regions",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-bandwidth-allocations",
        label: "Edit an aggregated bandwidth region",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "CertificateProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-certificate-profiles",
        label: "List certificate profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-certificate-profiles",
        label: "Create certificate profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-certificate-profiles-id",
        label: "Delete a certificate profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-certificate-profiles-id",
        label: "Get a certificate profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-certificate-profiles-id",
        label: "Modify a certificate profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Certificates",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-certificates",
        label: "List certificates",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-certificates",
        label: "Create certificates",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-certificates-id",
        label: "Delete certificates",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-certificates-import",
        label: "Import a certificate",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "ConfigurationManagement",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-config-versions",
        label: "List the candidate configurations",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-config-versions-candidate",
        label: "Rollback to the running configuration",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-config-versions-candidate-push",
        label: "Push the candidate configuration",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-config-versions-running",
        label: "Show the running configuration",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-config-versions-version",
        label: "Get a configuration by version",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-config-versions-load",
        label: "Load a configuration",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-jobs",
        label: "List configuration jobs",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-jobs-id",
        label: "List a configuration job by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-snapshots",
        label: "List configuration snapshots",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "DNSSecurityProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-dns-security-profiles",
        label: "List DNS security profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-dns-security-profiles",
        label: "Create a DNS security profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-dns-security-profiles-id",
        label: "Delete an DNS Security Profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-dns-security-profiles-id",
        label: "Get a DNS security profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-dns-security-profiles-id",
        label: "Edit an DNS Security Profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "DecryptionExclusions",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-exclusions",
        label: "List decryption exclusions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-decryption-exclusions",
        label: "Create a decryption exclusion",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-decryption-exclusions-id",
        label: "Delete a decryption exclusions.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-exclusions-id",
        label: "Get a decryption exclusion by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-decryption-exclusions-id",
        label: "Edit a decryption exclusion",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "DecryptionProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-profiles",
        label: "List decryption profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-decryption-profiles",
        label: "Create a decryption profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-decryption-profiles-id",
        label: "Delete a decryption profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-profiles-id",
        label: "Get a decryption profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-decryption-profiles-id",
        label: "Edit a decryption profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "DecryptionRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-rules",
        label: "List decryption rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-decryption-rules",
        label: "Create a decryption rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-decryption-rules-id",
        label: "Delete a decryption rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-decryption-rules-id",
        label: "Get a decryption rule by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-decryption-rules-id",
        label: "Edit a decryption rule",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-decryption-rules-id-move",
        label: "Move a decryption rule",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "DynamicUserGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-dynamic-user-groups",
        label: "List dynamic user groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-dynamic-user-groups",
        label: "Create a dynamic user group",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-dynamic-user-groups-id",
        label: "Delete a dynamic user group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-dynamic-user-groups-id",
        label: "Get a dynamic user group by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-dynamic-user-groups-id",
        label: "Edit a dynamic user group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ExternalDynamicLists",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-external-dynamic-lists",
        label: "List external dynamic lists",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-external-dynamic-lists",
        label: "Create an external dynamic list",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-external-dynamic-lists-id",
        label: "Delete an external dynamic list.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-external-dynamic-lists-id",
        label: "Get an external dynamic list",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-external-dynamic-lists-id",
        label: "Edit an external dynamic list.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "FileBlockingProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-file-blocking-profiles",
        label: "List file blocking profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-file-blocking-profiles",
        label: "Create a file blocking profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-file-blocking-profiles-id",
        label: "Delete an File-blocking profiles",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-file-blocking-profiles-id",
        label: "Get a file blocking profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-file-blocking-profiles-id",
        label: "Edit an File-blocking profiles",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "HIPObjects",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-hip-objects",
        label: "List hip objects",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-hip-objects",
        label: "Create a hip object",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-hip-objects-id",
        label: "Delete a hip object",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-hip-objects-id",
        label: "Get a HIP object by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-hip-objects-id",
        label: "Edit a hip object",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "HIPProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-hip-profiles",
        label: "List hip profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-hip-profiles",
        label: "Create a hip profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-hip-profiles-id",
        label: "Delete a hip profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-hip-profiles-id",
        label: "Get a HIP profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-hip-profiles-id",
        label: "Edit a hip profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "HTTPHeaderProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-http-header-profiles",
        label: "List HTTP header profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-http-header-profiles",
        label: "Create a HTTP header profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-http-header-profiles-id",
        label: "Delete a http header profiles",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-http-header-profiles-id",
        label: "Get a HTTP header profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-http-header-profiles-id",
        label: "Edit a http header profiles",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "IKECryptoProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ike-crypto-profiles",
        label: "List IKE crypto profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ike-crypto-profiles",
        label: "Create IKE crypto profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ike-crypto-profiles-id",
        label: "Delete a ike crypto profile.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ike-crypto-profiles-id",
        label: "Get an IKE crypto profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ike-crypto-profiles-id",
        label: "Edit a ike crypto profile.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "IKEGateways",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ike-gateways",
        label: "List IKE gateways",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ike-gateways",
        label: "Create IKE gateways",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ike-gateways-id",
        label: "Delete a ike gateway.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ike-gateways-id",
        label: "Get an IKE gateway",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ike-gateways-id",
        label: "Edit a ike gateway.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "IPSecCryptoProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ipsec-crypto-profiles",
        label: "List IPSec crypto profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ipsec-crypto-profiles",
        label: "Create IPSec crypto profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ipsec-crypto-profiles-id",
        label: "Delete a ipsec crypto profile.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ipsec-crypto-profiles-id",
        label: "Get an IPSec crypto profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ipsec-crypto-profiles-id",
        label: "Edit a ipsec crypto profile.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "IPSecTunnels",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ipsec-tunnels",
        label: "List IPSec tunnels",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ipsec-tunnels",
        label: "Create IPSec tunnels",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ipsec-tunnels-id",
        label: "Delete a ipsec tunnel.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ipsec-tunnels-id",
        label: "Get an IPSec tunnel",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ipsec-tunnels-id",
        label: "Edit a ipsec tunnel.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "InfrastructureSettings",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-enable",
        label: "Set up application defaults",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-shared-infrastructure-settings",
        label: "List all infrastructure settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-shared-infrastructure-settings",
        label: "Edit an infrastructure setting",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "InternalDNSServers",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-internal-dns-servers",
        label: "List internal DNS servers",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-internal-dns-servers",
        label: "Create an internal DNS server",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-internal-dns-servers-id",
        label: "Delete an internal DNS server",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-internal-dns-servers-id",
        label: "Get an internal DNS server",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-internal-dns-servers-id",
        label: "Edit an internal DNS server",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "KerberosServerProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-kerberos-server-profiles",
        label: "List all Kerberos server profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-kerberos-server-profiles",
        label: "Create a Kerberos server profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-kerberos-server-profiles-id",
        label: "Delete a kerberos server profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-kerberos-server-profiles-id",
        label: "Get a Kerberos server profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-kerberos-server-profiles-id",
        label: "Edit a kerberos server profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "LDAPServerProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ldap-server-profiles",
        label: "List all LDAP server profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ldap-server-profiles",
        label: "Create an LDAP server profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ldap-server-profiles-id",
        label: "Delete a ldap server profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ldap-server-profiles-id",
        label: "Get an LDAP server profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ldap-server-profiles-id",
        label: "Edit a ldap server profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "LicenseTypes",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-license-types",
        label: "List licenses",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "LocalUserGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-local-user-groups",
        label: "List local user groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-local-user-groups",
        label: "Create local user groups",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-local-user-groups-id",
        label: "Delete a local user group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-local-user-groups-id",
        label: "Get a local user group",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-local-user-groups-id",
        label: "Edit a local user group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "LocalUsers",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-local-users",
        label: "List all local users",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-local-users",
        label: "Create a local user",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-local-users-id",
        label: "Delete a local user",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-local-users-id",
        label: "Get a local user",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-local-users-id",
        label: "Edit a local user",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Locations",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-locations",
        label: "List locations",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "MFAServers",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mfa-servers",
        label: "List all MFA servers",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mfa-servers",
        label: "Create a MFA server",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-mfa-servers-id",
        label: "Delete a mfa server",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mfa-servers-id",
        label: "Get a MFA server",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mfa-servers-id",
        label: "Edit a mfa server",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "MobileAgent",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-mobile-agent-agent-profiles",
        label: "Delete agent profiles",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-agent-profiles",
        label: "Get agent profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-agent-profiles",
        label: "Create agent profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-agent-profiles",
        label: "Change agent profiles",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-agent-versions",
        label: "Get available agent versions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-mobile-agent-authentication-settings",
        label: "Delete authentication settings\n",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-authentication-settings",
        label: "Get authentication settings\n",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-authentication-settings",
        label: "Create authentication settings\n",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-authentication-settings",
        label: "Edit authentication settings\n",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-enable",
        label: "Indicates whether mobile agent is enabled",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-enable",
        label: "Enable mobile agent (GlobalProtect)",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-global-settings",
        label: "Get global settings\n",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-global-settings",
        label: "Edit global settings\n",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-mobile-agent-infrastructure-settings",
        label: "Delete infrastructure settings",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-infrastructure-settings",
        label: "Show infrastructure settings\n",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-infrastructure-settings",
        label: "Create infrastructure settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-infrastructure-settings",
        label: "Edit GlobalProtect infrastructure settings",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-locations",
        label: "Get Prisma Access locations",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-locations",
        label: "Edit Prisma Access locations",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-mobile-agent-tunnel-profiles",
        label: "Delete tunnel profiles",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-mobile-agent-tunnel-profiles",
        label: "Get tunnel profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-tunnel-profiles",
        label: "Create tunnel profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-mobile-agent-tunnel-profiles",
        label: "Update tunnel profiles",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-mobile-agent-user-authentication-move",
        label: "Move authentication settings\n",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "OCSPResponder",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ocsp-responder",
        label: "List OCSP responders",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-ocsp-responder",
        label: "Create OCSP responders",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-ocsp-responder-id",
        label: "Delete an OCSP responder.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-ocsp-responder-id",
        label: "Get an OCSP responder",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-ocsp-responder-id",
        label: "Edit an OCSP responder.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ProfileGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-profile-groups",
        label: "List profile groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-profile-groups",
        label: "Create profile groups",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-profile-groups-id",
        label: "Delete a profile group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-profile-groups-id",
        label: "Get a profile group",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-profile-groups-id",
        label: "Edit a profile group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "QoSPolicyRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-qos-policy-rules",
        label: "List QoS policy rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-qos-policy-rules",
        label: "Create a QoS policy rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-qos-policy-rules-id",
        label: "Delete a qos policy rule.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-qos-policy-rules-id",
        label: "Get a QoS policy rule by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-qos-policy-rules-id",
        label: "Edit a qos policy rule.",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-qos-policy-rules-id-move",
        label: "Move a qos policy rule",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "QoSProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-qos-profiles",
        label: "List QoS profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-qos-profiles",
        label: "Create a QoS profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-qos-profiles-id",
        label: "Delete a QoS profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-qos-profiles-id",
        label: "Get a QoS profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-qos-profiles-id",
        label: "Edit a QoS profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "QuarantinedDevices",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-quarantined-devices",
        label: "Delete quarantined devices",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-quarantined-devices",
        label: "List quarantined devices",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-quarantined-devices",
        label: "Quarantine devices",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "RadiusServerProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-radius-server-profiles",
        label: "List all Radius server profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-radius-server-profiles",
        label: "Create a Radius server profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-radius-server-profiles-id",
        label: "Delete a radius server profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-radius-server-profiles-id",
        label: "Get a Radius server profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-radius-server-profiles-id",
        label: "Edit a radius server profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Regions",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-regions",
        label: "List regions",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-regions",
        label: "Create a region",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-regions-id",
        label: "Delete a region",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-regions-id",
        label: "Get a region by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-regions-id",
        label: "Edit a region",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "RemoteNetworks",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-remote-networks",
        label: "List remote networks",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-remote-networks",
        label: "Create remote networks",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-remote-networks-id",
        label: "Delete a remote network",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-remote-networks-id",
        label: "Get a remote network",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-remote-networks-id",
        label: "Edit a remote network",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "SAMLServerProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-saml-server-profiles",
        label: "List all SAML server profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-saml-server-profiles",
        label: "Create a SAML server profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-saml-server-profiles-id",
        label: "Delete a saml server profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-saml-server-profiles-id",
        label: "Get a SAML server profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-saml-server-profiles-id",
        label: "Edit a saml server profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "SCEPProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-scep-profiles",
        label: "List SCEP profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-scep-profiles",
        label: "Create SCEP profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-scep-profiles-id",
        label: "Delete a SCEP profile.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-scep-profiles-id",
        label: "Get an SCEP profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-scep-profiles-id",
        label: "Edit a SCEP profile.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Schedules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-schedules",
        label: "List schedules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-schedules",
        label: "Create a schedule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-schedules-id",
        label: "Delete a schedule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-schedules-id",
        label: "Get a schedule by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-schedules-id",
        label: "Edit a schedule",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "SecurityRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-security-rules",
        label: "List security rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-security-rules",
        label: "Create a security rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-security-rules-id",
        label: "Delete a security rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-security-rules-id",
        label: "Get a security rule",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-security-rules-id",
        label: "Edit a security rule",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-security-rules-id-move",
        label: "Move a security rule",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "ServiceConnectionGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-connection-groups",
        label: "List service connection groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-service-connection-groups",
        label: "Create service connection groups",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-service-connection-groups-id",
        label: "Delete a service connection group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-connection-groups-id",
        label: "Get a service connection group",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-service-connection-groups-id",
        label: "Edit a service connection group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ServiceConnections",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-bgp-routing",
        label: "Retrieve BGP routing",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-bgp-routing",
        label: "Update BGP routing",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-connections",
        label: "List service connections",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-service-connections",
        label: "Create service connections",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-service-connections-id",
        label: "Delete a service connection",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-connections-id",
        label: "Get a service connection",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-service-connections-id",
        label: "Edit a service connection",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "ServiceGroups",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-groups",
        label: "List service groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-service-groups",
        label: "Create a service group",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-service-groups-id",
        label: "Delete a service group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-service-groups-id",
        label: "Get a service group by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-service-groups-id",
        label: "Edit a service group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Services",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-services",
        label: "List services",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-services",
        label: "Create a service object",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-services-id",
        label: "Delete a service",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-services-id",
        label: "Get a service by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-services-id",
        label: "Edit a service",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "TACACSServerProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tacacs-server-profiles",
        label: "List all TACACS server profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-tacacs-server-profiles",
        label: "Create a TACACS server profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-tacacs-server-profiles-id",
        label: "Delete a tacacs server profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tacacs-server-profiles-id",
        label: "Get a TACACS server profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-tacacs-server-profiles-id",
        label: "Edit a tacacs server profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "TLSServiceProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tls-service-profiles",
        label: "List TLS service profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-tls-service-profiles",
        label: "Create TLS service profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-tls-service-profiles-id",
        label: "Delete a tls service profile.",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tls-service-profiles-id",
        label: "Get a TLS service profile",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-tls-service-profiles-id",
        label: "Edit a tls service profile.",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Tags",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tags",
        label: "List tags",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-tags",
        label: "Create a tag",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-tags-id",
        label: "Delete a tag",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-tags-id",
        label: "Get a tag by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-tags-id",
        label: "Edit a tag",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "TrafficSteeringRules",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-traffic-steering-rules",
        label: "List service connections",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-traffic-steering-rules",
        label: "Create a service connection",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-traffic-steering-rules-id",
        label: "Delete a service connection",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-traffic-steering-rules-id",
        label: "Get a service connection",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-traffic-steering-rules-id",
        label: "Edit a service connection",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "TrustedCertificateAuthorities",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-trusted-certificate-authorities",
        label: "List trusted certificate authorities",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "URLAccessProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-url-access-profiles",
        label: "List URL access profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-url-access-profiles",
        label: "Create a URL access profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-url-access-profiles-id",
        label: "Delete an URL Access Profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-url-access-profiles-id",
        label: "Get a URL access profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-url-access-profiles-id",
        label: "Edit an URL Access Profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "URLCategories",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-url-categories",
        label: "List URL categories",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-url-categories",
        label: "Create a custom URL categories",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-url-categories-id",
        label: "Delete a custom URL Category",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-url-categories-id",
        label: "Get a URL category by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-url-categories-id",
        label: "Edit a custom URL Category",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "URLFilteringCategories",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-url-filtering-categories",
        label: "List URL filtering categories",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "VulnerabilityProtectionProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-vulnerability-protection-profiles",
        label: "List vulnerability protection profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-vulnerability-protection-profiles",
        label: "Create a vulnerability protection profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-vulnerability-protection-profiles-id",
        label: "Delete an vulnerability protection profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-vulnerability-protection-profiles-id",
        label: "Get a vulnerability protection profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-vulnerability-protection-profiles-id",
        label: "Edit an vulnerability protection profile",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "VulnerabilityProtectionSignatures",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-vulnerability-protection-signatures",
        label: "List vulnerability protection signatures",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-vulnerability-protection-signatures",
        label: "Create a vulnerability protection signature",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-vulnerability-protection-signatures-id",
        label: "Delete a vulnerability-protection signature",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-vulnerability-protection-signatures-id",
        label: "Get a vulnerability protection signature by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-vulnerability-protection-signatures-id",
        label: "Edit a vulnerability-protection signature",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "WildFireAntivirusProfiles",
    items: [
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-wildfire-anti-virus-profiles",
        label: "List WildFire antivirus profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/post-sse-config-v-1-wildfire-anti-virus-profiles",
        label: "Create a WildFire antivirus profile",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/delete-sse-config-v-1-wildfire-anti-virus-profiles-id",
        label: "Delete a wildfire and antivirus profile",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/get-sse-config-v-1-wildfire-anti-virus-profiles-id",
        label: "Get a WildFire antivirus profile by ID",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "access/api/prisma-access-config/put-sse-config-v-1-wildfire-anti-virus-profiles-id",
        label: "Edit a wildfire and antivirus profile",
        className: "api-method put",
      },
    ],
  },
];
