components:
  securitySchemes:
    X-DNS-API-APIKEY:
      description: API key to query https://api.dns.service.paloaltonetworks.com
      in: header
      name: X-DNS-API-APIKEY
      type: apiKey
schemas:
  public_apiCategoryHistory:
    properties:
      category:
        description: The history category from PAN-DB.
        type: string
      evidences:
        description: A list of evidences supporting the category.
        items:
          type: string
        type: array
      time:
        description: The time when the category is published.
        type: string
    type: object
  public_apiIpHistory:
    properties:
      asn:
        $ref: '#/schemas/public_apiIpHistoryAsn'
        description: ASN information of the IP
      count:
        description: The number of DNS records that we had seen was resolving the
          given domain in Passive DNS.
        format: uint64
        type: string
      first:
        description: The first seen date time of the DNS record. UTC datetime in "YYYY-mm-dd
          HH:mm:ss" format.
        type: string
      geo:
        $ref: '#/schemas/public_apiIpHistoryGeo'
        description: Country information of the IP
      ip:
        description: DNS record. IPv4 or IPv6.
        type: string
      last:
        description: The last seen date time of the DNS record. UTC datetime in "YYYY-mm-dd
          HH:mm:ss" format.
        type: string
      type:
        description: Type of the DNS record. We only support A(IPv4) and AAAA(IPv6)
          type.
        type: string
    type: object
  public_apiIpHistoryAsn:
    properties:
      ASName:
        type: string
      ASNumber:
        format: int64
        type: string
    type: object
  public_apiIpHistoryGeo:
    properties:
      countryCode:
        type: string
      countryName:
        type: string
    type: object
  public_apiV1DomainHistoryTrafficDomain:
    example:
      domain: google.com
      end: "2022-07-31"
      start: "2022-07-01"
    properties:
      domain:
        description: The domain name to query
        maxLength: 253
        type: string
      end:
        default: Today
        description: The end date for a user-specified date range that the domain
          traffic appear in the customer's DNS traffic. UTC date in YYYY-mm-dd format.
          The start can not be later than end.
        pattern: YYYY-mm-dd
        type: string
      start:
        default: Today - 30 days
        description: The start date for a user-specified date range that the domain
          traffic appear in the customer's DNS traffic. UTC date in YYYY-mm-dd format.
          The start can not be later than end.
        pattern: YYYY-mm-dd
        type: string
    required:
    - domain
    type: object
  public_apiV1DomainHistoryTrafficResponse:
    example:
      customerSupportId: "193870"
      message: ""
      results:
      - count: 123456
        domain: google.com
        end: "2022-07-31"
        start: "2022-07-01"
      success: true
    properties:
      customerSupportId:
        description: The customer support ID of the APIKey owner.
        type: string
      message:
        description: If "success" is true, the message should be empty.
        type: string
      results:
        description: The list of result objects.
        items:
          $ref: '#/schemas/public_apiV1DomainHistoryTrafficResult'
        type: array
      success:
        type: boolean
    type: object
  public_apiV1DomainHistoryTrafficResult:
    properties:
      count:
        description: The count of domain name appear in the customers DNS traffic
          within the date range
        format: int64
        type: string
      domain:
        description: The domain name queried
        type: string
      end:
        description: The user-specified end date in the request
        type: string
      start:
        description: The user-specified start date in the request
        type: string
    type: object
  public_apiV1DomainInfoDomains:
    example:
      domain: onion.top
      firstEnd: "2022-08-31"
      firstStart: "2022-01-01"
      lastEnd: "2022-08-31"
      lastStart: "2022-01-01"
    properties:
      domain:
        description: The domain name you want to query
        maxLength: 253
        type: string
      firstEnd:
        default: No limit
        description: A user-specified end date of the first seen date range in PassiveDNS
          records. UTC date in YYYY-mm-dd format. firstStart cannot be later than
          firstEnd.
        pattern: YYYY-mm-dd
        type: string
      firstStart:
        default: No limit
        description: A user-specified start date of the first seen date range in PassiveDNS
          records. UTC date in YYYY-mm-dd format. firstStart cannot be later than
          firstEnd.
        pattern: YYYY-mm-dd
        type: string
      lastEnd:
        default: Today
        description: A user-specified end date of the last seen date range in PassiveDNS
          records. UTC date in YYYY-mm-dd format. lastStart cannot be later than lastEnd.
        pattern: YYYY-mm-dd
        type: string
      lastStart:
        default: No limit
        description: A user-specified start date of the last seen date range in PassiveDNS
          records. UTC date in YYYY-mm-dd format. lastStart cannot be later than lastEnd.
        pattern: YYYY-mm-dd
        type: string
    required:
    - domain
    type: object
  public_apiV1DomainInfoRequest:
    properties:
      domains:
        description: Provides a list of domain object details by matching it with
          the information contained in the DNS Security cloud database.
        items:
          $ref: '#/schemas/public_apiV1DomainInfoDomains'
        maxItems: 20
        type: array
    type: object
  public_apiV1DomainInfoResponse:
    example:
      message: ""
      results:
      - category: c2
        categoryHistories:
        - category: command-and-control
          evidences:
          - Associated with a malicious sample submitted and analyzed by WildFire
          - Corroborated by intelligence sources
          - Associated with known bad IPs
          time: "2022-06-24T00:07:30Z"
        - category: command-and-control
          evidences: []
          time: "2022-05-14T00:07:30Z"
        dgaScore: 0
        domain: onion.top
        ipHistories:
        - asn:
            ASName: STEADFAST - Steadfast, US
            ASNumber: 32748
          count: 6
          first: "2021-12-18T16:42:49Z"
          geo:
            countryCode: US
            countryName: United States
          ip: 208.100.26.245
          last: "2022-06-23T17:50:16Z"
          type: a
        verdict: 2
      success: true
    properties:
      message:
        description: If "success" is true, the message should be empty.
        type: string
      results:
        description: The list of result objects.
        items:
          $ref: '#/schemas/public_apiV1DomainInfoResult'
        type: array
      success:
        type: boolean
    type: object
  public_apiV1DomainInfoResult:
    properties:
      category:
        description: Domain category from DNS and PAN-DB.
        type: string
      categoryHistories:
        description: A list of history category information from PAN-DB.
        items:
          $ref: '#/schemas/public_apiCategoryHistory'
        title: repeated WhoisRecord whoisRecords = 5 [json_name = "whoisRecords"];
        type: array
      dgaScore:
        description: The score of DGA domain.
        format: double
        type: number
      domain:
        description: The domain name queried.
        type: string
      ipHistories:
        description: A list of history DNS records of the domain from Passive DNS.
        items:
          $ref: '#/schemas/public_apiIpHistory'
        type: array
      verdict:
        description: Verdict number of the domain category.
        format: int64
        type: string
    type: object
host: api.dns.service.paloaltonetworks.com






info:
  title: DNS Security API
  version: Beta
  description: '

    The DNS Security API endpoints require an active subscription to the DNS Security security service. These endpoints can only be accessed using the API key associated with the account that holds the subscription.


    List of DNS Security API endpoints:

    1. Link to [Request Domain Information](dns-security#operation/PublicApi_V1DomainInfo)

    '

paths:


  /domain/info:
    post:
      description: A POST request to retrieve general information about the specified domains, including WHOIS information, Passive DNS, DNS Security / PAN-DB category, and the DGA score. Batch limit is 20 entries.
      operationId: PublicApi_V1DomainInfo
      requestBody:
        content:
          application/json:
            schema:
              properties:
                domains:
                  description: "Provides a list of domain object details by matching it with the information contained in the DNS Security cloud database."
                  items:
                    $ref: '#/schemas/public_apiV1DomainInfoDomains'
                  type: array
                  maxItems: 20
              type: object
        required: true







      responses:
        "200":
          description: Ok
          headers:
            X-Quota-Limit-Remaining:
              description: The remaining number of quota in this window (per day).
                When it drops to 0, return HTTP StatusCode = 429
              type: integer
            X-Quota-Limit-Reset:
              description: The unix timestamp at which the current quota window resets.
                Quota is refreshed every day.
              type: integer
            X-Quota-Limit-Total:
              description: Total number of quota in this window (per day).
              type: integer
          content:
            application/json:
              schema:  
                $ref: '#/schemas/public_apiV1DomainInfoResponse'


        "400":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Error
                        message content., type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Bad Request

        "401":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Unauthorized, type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Unauthorized

        "403":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Forbidden, type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Forbidden

        "404":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Not Found, type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Not Found

        "415":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Unsupported Media Type, type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Unsupported Media Type

        "429":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: Too Many Requests, type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Too Many Requests

        "500":
          content:
            application/json:
              schema:
                properties:
                  message:
                    { description: error message content..., example: error message..., type: string }
                  success:
                    {
                      description: The response status.,
                      example: false,
                      type: boolean,
                    }
                type: object
          description: Internal Error
      security:
      - X-DNS-API-APIKEY: []
      summary: Request Domain Information
produces:
- application/json
schemes:
- https
openapi: 3.0.2
servers:
- {url: 'https://api.dns.service.paloaltonetworks.com/v1/'}

tags:
- name: DNS Security
