module.exports = {
  panosupgradeassurance: [
    "panos-upgrade-assurance/docs/intro",
    "panos-upgrade-assurance/docs/overview",
    "panos-upgrade-assurance/docs/dialect",
    "panos-upgrade-assurance/docs/installation",
    "panos-upgrade-assurance/docs/configuration-details",
    "panos-upgrade-assurance/docs/usage-examples",
    {
      type: "category",
      label: "API reference",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "panos-upgrade-assurance/docs/api",
        },
      ],
    },
  ],
};
