module.exports = {
  iot_api: [
    {
      type: "category",
      label: "IoT API",
      link: {
        type: "generated-index",
        title: "IoT API",
        slug: "/iot/api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "iot/api",
        },
      ],
    },
  ],
};
