components:
  schemas:
    DescribeFileBlockingActionResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/DescribeFileBlockingActionResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/DescribeFileBlockingActionResponse.Result'
          description: 'The API call response status.

            '
      title: DescribeFileBlockingActionResponse
      type: object
    DescribeFileBlockingActionResponse.FileBlockingEntry:
      additionalProperties: false
      properties:
        Action:
          default: alert
          description: 'File blocking action.

            '
          enum:
          - alert
          - block
          - continue
          title: Action
          type: string
        AuditComment:
          description: 'Audit remarks.

            '
          title: Auditcomment
          type: string
        Description:
          description: 'A description of the file blocking action.

            '
          maxLength: 255
          title: Description
          type: string
        Direction:
          default: both
          description: 'Traffic direction.

            '
          enum:
          - upload
          - download
          - both
          title: Direction
          type: string
        UpdateToken:
          default: '1'
          description: 'Refresh the token.

            '
          title: Updatetoken
          type: string
      title: FileBlockingEntry
      type: object
    DescribeFileBlockingActionResponse.ResponseData:
      additionalProperties: false
      properties:
        FileBlockingCandidate:
          $ref: '#/components/schemas/DescribeFileBlockingActionResponse.FileBlockingEntry'
          description: 'The file blocking action candidate.

            '
        FileBlockingRunning:
          $ref: '#/components/schemas/DescribeFileBlockingActionResponse.FileBlockingEntry'
          description: 'The file blocking actions on run state.

            '
        FileType:
          description: "Blocked file type.    \n"
          title: Filetype
          type: string
        RuleStackName:
          description: "Name of the rulestack. \n"
          title: Rulestackname
          type: string
      title: ResponseData
      type: object
    DescribeFileBlockingActionResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: "Default value of a successful response is 0. Any other number\
            \ indicates an error code.  \n\n400\u2014HTTP bad request\n* InvalidRequestException\u2014\
            Operation failed due to invalid request. For example, unsupported parameter\
            \ name or value in the request.\n* LimitExceededException\u2014Operation\
            \ failed due to violation in limit settings.\n* ThrottlingException\u2014\
            Operation failed due to throttling limitations.\n* AccessDeniedException\u2014\
            You do not have sufficient access to perform this action.\n\n500\u2014\
            Bad request \n* InternalServerError\u2014Your request is valid but Cloud\
            \ NGFW could not perform the operation due to a system issue.\n* InsufficientCapacityException\u2014\
            AWS currently does not have enough capacity to fulfill your request.\n"
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
    ListFileBlockingActionResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/ListFileBlockingActionResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/ListFileBlockingActionResponse.Result'
          description: 'The API call response status.

            '
      title: ListFileBlockingActionResponse
      type: object
    ListFileBlockingActionResponse.ResponseData:
      additionalProperties: false
      properties:
        FileBlockingCandidate:
          description: 'File blocking action candidate.

            '
          items:
            type: string
          title: Fileblockingcandidate
          type: array
        FileBlockingRunning:
          description: 'File blocking action on run state.

            '
          items:
            type: string
          title: Fileblockingrunning
          type: array
        FileBlockingUncommitted:
          description: 'Uncommitted file blocking actions.

            '
          items:
            $ref: '#/components/schemas/ListFileBlockingActionResponse.UncommittedFileBlocking'
          title: Fileblockinguncommitted
          type: array
        NextToken:
          description: 'If the number of file blocking actions available for retrieval
            exceeds the maximum you requested, NGFW returns a NextToken value in response.
            To retrieve the next batch of file blocking actions, use this token in
            your next request.

            '
          title: Nexttoken
          type: string
        RuleStackName:
          description: 'Name of the rulestack.

            '
          title: Rulestackname
          type: string
      title: ResponseData
      type: object
    ListFileBlockingActionResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: "Default value of a successful response is 0. Any other number\
            \ indicates an error code.  \n\n400\u2014HTTP bad request\n* InvalidRequestException\u2014\
            Operation failed due to invalid request. For example, unsupported parameter\
            \ name or value in the request.\n* ResourceNotFoundException\u2014Unable\
            \ to locate a resource using the parameters you provided.\n* ThrottlingException\u2014\
            Operation failed due to throttling limitations.\n\n500\u2014Bad request\
            \ \n* InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n"
          title: Errorcode
          type: integer
        Reason:
          description: "The error description. \n"
          title: Reason
          type: string
      title: Result
      type: object
    ListFileBlockingActionResponse.UncommittedFileBlocking:
      additionalProperties: false
      properties:
        Name:
          description: 'Name of the file blocking action.

            '
          title: Name
          type: string
        Operation:
          description: 'File blocking action operation.

            '
          title: Operation
          type: string
      required:
      - Name
      - Operation
      title: UncommittedFileBlocking
      type: object
    UpdateFileBlockingActionRequest:
      additionalProperties: false
      properties:
        Action:
          description: 'File blocking action.

            '
          enum:
          - alert
          - block
          title: Action
          type: string
        AuditComment:
          description: 'Audit remarks.

            '
          title: Auditcomment
          type: string
        Description:
          description: 'A description of the file blocking action.

            '
          maxLength: 255
          title: Description
          type: string
        Direction:
          description: 'Traffic direction.

            '
          enum:
          - upload
          - download
          - both
          title: Direction
          type: string
        UpdateToken:
          description: 'Refresh the token.

            '
          title: Updatetoken
          type: string
      required:
      - Direction
      - Action
      title: UpdateFileBlockingActionRequest
      type: object
    UpdateFileBlockingActionResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/UpdateFileBlockingActionResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/UpdateFileBlockingActionResponse.Result'
          description: 'The API call response status.

            '
      title: UpdateFileBlockingActionResponse
      type: object
    UpdateFileBlockingActionResponse.FileBlockingEntry:
      additionalProperties: false
      properties:
        Action:
          default: alert
          description: 'File blocking action.

            '
          enum:
          - alert
          - block
          - continue
          title: Action
          type: string
        AuditComment:
          description: 'Audit remarks.

            '
          title: Auditcomment
          type: string
        Description:
          description: 'A description of the file blocking action.

            '
          maxLength: 255
          title: Description
          type: string
        Direction:
          default: both
          description: 'Traffic direction.

            '
          enum:
          - upload
          - download
          - both
          title: Direction
          type: string
        UpdateToken:
          default: '1'
          description: "Refresh the token.    \n"
          title: Updatetoken
          type: string
      title: FileBlockingEntry
      type: object
    UpdateFileBlockingActionResponse.ResponseData:
      additionalProperties: false
      properties:
        FileBlockingEntry:
          $ref: '#/components/schemas/UpdateFileBlockingActionResponse.FileBlockingEntry'
          description: 'The file blocking action entry.

            '
        FileType:
          description: "Blocked file type.    \n"
          title: Filetype
          type: string
        RuleStackName:
          description: "Name of the rulestack. \n"
          title: Rulestackname
          type: string
      title: ResponseData
      type: object
    UpdateFileBlockingActionResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: "Default value of a successful response is 0. Any other number\
            \ indicates an error code.  \n\n400\u2014HTTP bad request\n* InvalidRequestException\u2014\
            Operation failed due to invalid request. For example, unsupported parameter\
            \ name or value in the request.\n* LimitExceededException\u2014Operation\
            \ failed due to violation in limit settings.\n* ThrottlingException\u2014\
            Operation failed due to throttling limitations.\n* AccessDeniedException\u2014\
            You do not have sufficient access to perform this action.\n\n500\u2014\
            Bad request \n* InternalServerError\u2014Your request is valid but Cloud\
            \ NGFW could not perform the operation due to a system issue.\n* InsufficientCapacityException\u2014\
            AWS currently does not have enough capacity to fulfill your request.\n"
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
info:
  contact: {}
  description: "File blocking actions allow you to identify specific file types that\
    \ you want to block. \n"
  title: Manage File Blocking Actions
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/config/rulestacks/{rulestackname}/fileblockingprofiles/custom/filetypes:
    get:
      description: 'Retrieves the metadata for the file blocking profile defined for
        a specified rulestack.

        '
      operationId: get-v1-config-rulestacks-rulestackname-fileblockingprofiles-custom-filetypes
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      - description: 'If the number of file blocking actions available for retrieval
          exceeds the maximum you requested, NGFW returns a NextToken value in response.
          To retrieve the next batch of file blocking actions, use this token in your
          next request.

          '
        in: query
        name: nexttoken
        required: false
        schema:
          title: Nexttoken
          type: string
      - description: 'File blocking action candidate.

          '
        in: query
        name: candidate
        required: false
        schema:
          default: true
          title: Candidate
          type: boolean
      - description: 'File blocking actions in run state.

          '
        in: query
        name: running
        required: false
        schema:
          default: false
          title: Running
          type: boolean
      - description: 'Uncommitted file blocking actions.

          '
        in: query
        name: uncommitted
        required: false
        schema:
          default: false
          title: Uncommitted
          type: boolean
      - description: 'The maximum number of file blocking actions that you want NGFW
          to return for this request.

          '
        in: query
        name: maxresults
        required: false
        schema:
          default: 1024
          maximum: 1024
          minimum: 1
          title: Maxresults
          type: integer
      - description: 'Retrieve file blocking action information.

          '
        in: query
        name: describe
        required: false
        schema:
          default: false
          title: Describe
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListFileBlockingActionResponse'
          description: OK
      summary: List File Blocking Actions
      tags:
      - ManageFileBlockingActions
  /v1/config/rulestacks/{rulestackname}/fileblockingprofiles/custom/filetypes/{type}:
    get:
      description: 'Use this command to return the data related to the file blocking
        profile attached to a specified rulestack.

        '
      operationId: get-v1-config-rulestacks-rulestackname-fileblockingprofiles-custom-filetypes-type
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      - description: 'The type of file blocking action.

          '
        in: path
        name: type
        required: true
        schema:
          type: string
      - description: 'File blocking actions in run state.

          '
        in: query
        name: running
        required: false
        schema:
          default: false
          title: Running
          type: boolean
      - description: "File blocking action candidate. \n"
        in: query
        name: candidate
        required: false
        schema:
          default: true
          title: Candidate
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeFileBlockingActionResponse'
          description: OK
      summary: Describe File Blocking Action
      tags:
      - ManageFileBlockingActions
    put:
      description: 'Update the file blocking profile to a specified rulestack.

        '
      operationId: put-v1-config-rulestacks-rulestackname-fileblockingprofiles-custom-filetypes-type
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      - description: 'The type of file blocking action.

          '
        in: path
        name: type
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFileBlockingActionRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateFileBlockingActionResponse'
          description: OK
      summary: Update File Blocking Action
      tags:
      - ManageFileBlockingActions
servers:
- url: https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com
tags:
- name: ManageFileBlockingActions
