module.exports = [
  { type: "doc", id: "compute/api/prisma-cloud-compute-api" },
  {
    type: "category",
    label: "Agentless",
    link: { type: "doc", id: "compute/api/agentless" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-agentless-progress",
        label: "View the Agentless Scan Progress",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-agentless-scan",
        label: "Start Agentless Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-agentless-stop",
        label: "Stop an Ongoing Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-agentless-templates",
        label: "Download Agentless Permission Templates",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Application-Control",
    link: { type: "doc", id: "compute/api/application-control" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-application-control-host",
        label: "Host Application Control Rule",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-application-control-host",
        label: "Update Host Application Control Rules",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/delete-application-control-host-id",
        label: "Delete a Host Application Control Rule",
        className: "api-method delete",
      },
    ],
  },
  {
    type: "category",
    label: "Audits",
    link: { type: "doc", id: "compute/api/audits" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-audits-access",
        label: "Get Docker Access Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-access-download",
        label: "Download Docker Access Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-admission",
        label: "Get Admission Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-admission-download",
        label: "Download Admission Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-agentless",
        label: "Get WAAS Agentless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-agentless-download",
        label: "Download WAAS Agentless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-agentless-timeslice",
        label: "Get WAAS Agentless Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-app-embedded",
        label: "Get WAAS App-embedded Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-app-embedded-download",
        label: "Download WAAS App-embedded Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-app-embedded-timeslice",
        label: "Get WAAS App-embedded Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-container",
        label: "Get WAAS Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-container-download",
        label: "Download WAAS Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-container-timeslice",
        label: "Get WAAS Container Audit Timeslice",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-host",
        label: "Get WAAS Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-host-download",
        label: "Download WAAS Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-host-timeslice",
        label: "Get WAAS Host Audit Timeslice",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-serverless",
        label: "Get WAAS Serverless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-serverless-download",
        label: "Download WAAS Serverless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-app-serverless-timeslice",
        label: "Get WAAS Serverless Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-network-container",
        label: "Get CNNS Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-network-container-download",
        label: "Download CNNS Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-network-host",
        label: "Get CNNS Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-firewall-network-host-download",
        label: "Download CNNS Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-incidents",
        label: "Get Incident Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/patch-audits-incidents-acknowledge-id",
        label: "Archive an Incident Audit Event",
        className: "api-method patch",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-incidents-download",
        label: "Download Incident Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-kubernetes",
        label: "Get Kubernetes Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-kubernetes-download",
        label: "Download Kubernetes Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-mgmt",
        label: "Get Management Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-mgmt-download",
        label: "Download Management Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-mgmt-filters",
        label: "Get Management Audit Event Filters",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-app-embedded",
        label: "Get Runtime App-embedded Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-app-embedded-download",
        label: "Download Runtime App-embedded Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-container",
        label: "Get Runtime Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-container-download",
        label: "Download Runtime Container Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-container-timeslice",
        label: "Get Runtime Container Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-file-integrity",
        label: "Get Runtime File Integrity Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-file-integrity-download",
        label: "Download Runtime File Integrity Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-host",
        label: "Get Runtime Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-host-download",
        label: "Download Runtime Host Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-host-timeslice",
        label: "Get Runtime Host Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-log-inspection",
        label: "Get Runtime Log Inspection Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-log-inspection-download",
        label: "Download Runtime Log Inspection Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-serverless",
        label: "Get Runtime Serverless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-serverless-download",
        label: "Download Serverless Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-runtime-serverless-timeslice",
        label: "Get Runtime Serverless Audit Events for a Timeframe",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-trust",
        label: "Get Trust Audit Events",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-audits-trust-download",
        label: "Download Trust Audit Events",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Authenticate",
    link: { type: "doc", id: "compute/api/authenticate" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-authenticate",
        label: "Get User Authentication Access Token",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Authenticate-Client",
    link: { type: "doc", id: "compute/api/authenticate-client" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-authenticate-client",
        label: "Get Client Authentication Access Token",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Certs",
    link: { type: "doc", id: "compute/api/certs" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-certs-ca-pem",
        label: "Get CA PEM Certificate File",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-certs-server-certs-sh",
        label: "Get Server Certificates",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Cloud",
    link: { type: "doc", id: "compute/api/cloud" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-cloud-discovery",
        label: "Get Cloud Discovery Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-cloud-discovery-download",
        label: "Download Cloud Discovery Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-cloud-discovery-entities",
        label: "Get Discovered Cloud Entities",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-cloud-discovery-scan",
        label: "Start a Cloud Discovery Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-cloud-discovery-stop",
        label: "Stop a Cloud Discovery Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-cloud-discovery-vms",
        label: "Get Discovered VMs",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Coderepos-Ci",
    link: { type: "doc", id: "compute/api/coderepos-ci" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-coderepos-ci-evaluate",
        label: "Resolve Code Repos",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Collections",
    link: { type: "doc", id: "compute/api/collections" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-collections",
        label: "Get Collections",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-collections",
        label: "Add a New Collection",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/delete-collections-id",
        label: "Delete an Existing Collection",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/put-collections-id",
        label: "Update an Existing Collection",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-collections-id-usages",
        label: "Get Policies for a Collection",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Containers",
    link: { type: "doc", id: "compute/api/containers" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-containers",
        label: "Get Container Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-containers-count",
        label: "Get Containers Count",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-containers-download",
        label: "Download Container Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-containers-names",
        label: "Get Container Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-containers-scan",
        label: "Start a Container Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Credentials",
    link: { type: "doc", id: "compute/api/credentials" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-credentials",
        label: "Get All Credentials",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-credentials",
        label: "Add Credentials",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/delete-credentials-id",
        label: "Delete a Credential",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/get-credentials-id-usages",
        label: "Get Credential Usages",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Current",
    link: { type: "doc", id: "compute/api/current" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-current-collections",
        label: "User Collections",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-current-projects",
        label: "User Projects",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Custom-Compliance",
    link: { type: "doc", id: "compute/api/custom-compliance" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-custom-compliance",
        label: "Get Custom Compliance Checks",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-custom-compliance",
        label: "Update Custom Compliance Checks",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/delete-custom-compliance-id",
        label: "Delete a Custom Compliance Check",
        className: "api-method delete",
      },
    ],
  },
  {
    type: "category",
    label: "Custom-Rules",
    link: { type: "doc", id: "compute/api/custom-rules" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-custom-rules",
        label: "Get Custom Rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/delete-custom-rules-id",
        label: "Delete a Custom Rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/put-custom-rules-id",
        label: "Update a Custom Rule",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Defenders",
    link: { type: "doc", id: "compute/api/defenders" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-defenders",
        label: "Get Deployed Defenders",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-app-embedded",
        label: "Generate a Docker File for App-embedded Defender",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-daemonset-yaml",
        label: "Generate Daemonset Deployment YAML File",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-download",
        label: "Download Deployed Defenders",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-fargate-json",
        label: "Generate a Protected JSON Fargate Task Definition",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-fargate-yaml",
        label: "Generate a Protected YAML Fargate Task Definition",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-helm-twistlock-defender-helm-tar-gz",
        label: "Generate a Helm Deployment Chart for Defender",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-image-name",
        label: "Get Docker Image Name for Defender",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-install-bundle",
        label: "Get Certificate Bundle for Defender",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-names",
        label: "Get Defender Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-serverless-bundle",
        label: "Generate Serverless Bundle for Defender",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-summary",
        label: "Get Defenders Summary",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-defenders-tas-cloud-controller-address",
        label: "Defenders Tas Cloud Controller Address",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-upgrade",
        label: "Upgrade Connected Single Linux Defenders",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/delete-defenders-id",
        label: "Delete a Defender",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-id-features",
        label: "Update Defender Configuration",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-id-restart",
        label: "Restart a Defender",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-defenders-id-upgrade",
        label: "Upgrade a Defender",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Feeds",
    link: { type: "doc", id: "compute/api/feeds" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-feeds-custom-custom-vulnerabilities",
        label: "Get Custom Vulnerability Feed",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-feeds-custom-custom-vulnerabilities",
        label: "Update Custom Vulnerability Feed",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-feeds-custom-malware",
        label: "Get Custom Malware Feed",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-feeds-custom-malware",
        label: "Update Custom Malware Feed",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Groups",
    link: { type: "doc", id: "compute/api/groups" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-groups",
        label: "Get Groups",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-groups",
        label: "Add a Group",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-groups-names",
        label: "Get Group Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/delete-groups-id",
        label: "Delete a Group",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/put-groups-id",
        label: "Update a Group",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Hosts",
    link: { type: "doc", id: "compute/api/hosts" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-hosts",
        label: "Get Host Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-hosts-download",
        label: "Download Host Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-hosts-evaluate",
        label: "Resolve Hosts",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-hosts-info",
        label: "Get Host Information",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-hosts-scan",
        label: "Start a Host Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Images",
    link: { type: "doc", id: "compute/api/images" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-images",
        label: "Get Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-images-download",
        label: "Download Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-images-evaluate",
        label: "Resolve Images",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-images-names",
        label: "Get Image Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-images-scan",
        label: "Start Image Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-images-twistlock-defender-app-embedded-tar-gz",
        label: "Download App Embedded Defender",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-images-twistlock-defender-layer-zip",
        label: "Download Serverless Layer Bundle",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Policies",
    link: { type: "doc", id: "compute/api/policies" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-ci-images",
        label: "Get Continuous Integration (CI) Image Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-compliance-ci-images",
        label: "Update Continuous Integration (CI) Image Compliance Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-ci-serverless",
        label: "Get Continuous Integration (CI) Serverless Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-compliance-ci-serverless",
        label:
          "Update Continuous Integration (CI) Serverless Compliance Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-container",
        label: "Get Container Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-compliance-container",
        label: "Update Container Compliance Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-container-impacted",
        label: "Get Impacted Container Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-host",
        label: "Get Host Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-compliance-host",
        label: "Update Host Compliance Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-serverless",
        label: "Get Serverless Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-compliance-serverless",
        label: "Update Serverless Compliance Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-compliance-vms-impacted",
        label: "Get Impacted VMs Compliance Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-agentless",
        label: "Get Agentless App Firewall Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-agentless",
        label: "Set Agentless App Firewall Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-agentless-impacted",
        label: "Get Agentless App Firewall Policy Impacted",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-agentless-resources",
        label: "Get Agentless App Firewall Policy Resources",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-agentless-state",
        label: "Get Agentless App Firewall Policy State",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-firewall-app-apispec",
        label: "Generate a WAAS API Specification Object",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-app-embedded",
        label: "Get WAAS App-embedded Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-app-embedded",
        label: "Update WAAS App-embedded Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-container",
        label: "Get WAAS Container Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-container",
        label: "Update WAAS Container Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-container-impacted",
        label: "Container App Firewall Policy Impacted",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-host",
        label: "Get WAAS Host Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-host",
        label: "Update WAAS Host Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-host-impacted",
        label: "Host App Firewall Policy Impacted",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-network-list",
        label: "Get WAAS Network List",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-firewall-app-network-list",
        label: "Add WAAS Network List",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-network-list",
        label: "Update WAAS Network List",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/delete-policies-firewall-app-network-list-id",
        label: "Delete WAAS Network List",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-out-of-band",
        label: "Get Out-of-Band WAAS Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-out-of-band",
        label: "Update Out-of-Band WAAS Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-out-of-band-impacted",
        label: "Get Impacted Resources for Out-of-Band WAAS Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-app-serverless",
        label: "Get WAAS Serverless Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-app-serverless",
        label: "Update WAAS Serverless Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-firewall-network",
        label: "Get CNNS Container and Host Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-firewall-network",
        label: "Update CNNS Container and Host Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-runtime-app-embedded",
        label: "Get Runtime App-embedded Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-runtime-app-embedded",
        label: "Add Runtime App-embedded Policy",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-runtime-app-embedded",
        label: "Update Runtime App-embedded Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-runtime-container",
        label: "Get Runtime Container Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-runtime-container",
        label: "Update Runtime Container Policy",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-runtime-container",
        label: "Set Container Runtime Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-runtime-container-impacted",
        label: "Update Runtime Impacted Container Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-runtime-host",
        label: "Get Runtime Host Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-runtime-host",
        label: "Update Runtime Host Policy",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-runtime-host",
        label: "Set Host Runtime Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-runtime-serverless",
        label: "Get Runtime Serverless Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-runtime-serverless",
        label: "Update Runtime Serverless Policy",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-runtime-serverless",
        label: "Set Serverless Runtime Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-base-images",
        label: "Get Base Images Rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-policies-vulnerability-base-images",
        label: "Add Base Images Rule",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-base-images-download",
        label: "Download Base Images Rules",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/delete-policies-vulnerability-base-images-id",
        label: "Delete Base Images Rule",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-ci-images",
        label: "Get CI Image Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-vulnerability-ci-images",
        label: "Update CI Image Vulnerability Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-ci-serverless",
        label: "Get CI Serverless Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-vulnerability-ci-serverless",
        label: "Update CI Serverless Vulnerability Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-host",
        label: "Get Host Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-vulnerability-host",
        label: "Update Host Vulnerability Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-host-impacted",
        label: "Get Impacted Host Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-images",
        label: "Get Image Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-vulnerability-images",
        label: "Update Image Vulnerability Policy",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-images-impacted",
        label: "Get Impacted Image Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-policies-vulnerability-serverless",
        label: "Get Serverless Vulnerability Policy",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-policies-vulnerability-serverless",
        label: "Update Serverless Vulnerability Policy",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Profiles",
    link: { type: "doc", id: "compute/api/profiles" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-profiles-app-embedded",
        label: "Get App-embedded Profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-profiles-app-embedded-download",
        label: "Download App-embedded Profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-profiles-container",
        label: "Get Runtime Container Profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-profiles-container-download",
        label: "Download Runtime Container Profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-profiles-container-learn",
        label: "Learn Runtime Container Profiles",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-profiles-host",
        label: "Get Runtime Host Profiles",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-profiles-host-download",
        label: "Download Runtime Host Profiles",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Registry",
    link: { type: "doc", id: "compute/api/registry" },
    items: [
      {
        type: "doc",
        id: "compute/api/delete-registry-webhook-webhook",
        label: "Delete a Registry Webhook",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/post-registry-webhook-webhook",
        label: "Registry Webhook",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-registry",
        label: "Get Registry Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-registry-download",
        label: "Download Registry Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-registry-names",
        label: "Get Registry Image Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-registry-progress",
        label: "View Registry Scan Progress",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-registry-scan",
        label: "Start a Registry Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-registry-scan-select",
        label: "Scan Registries",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-registry-stop",
        label: "Stop a Registry Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-registry-stop-id",
        label: "Stop a Registry spec Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Sandbox",
    link: { type: "doc", id: "compute/api/sandbox" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-sandbox",
        label: "AddSandboxScanResult",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Sbom",
    link: { type: "doc", id: "compute/api/sbom" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-sbom-download-cli-images",
        label: "Download SBOM CI Images",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-cli-serverless",
        label: "Download SBOM CLI Serverless",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-hosts",
        label: "Download SBOM Hosts",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-images",
        label: "Download SBOM Images",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-registry",
        label: "Download SBOM Registry",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-serverless",
        label: "Download SBOM Serverless",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-sbom-download-vms",
        label: "Download SBOM VMs",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Scans",
    link: { type: "doc", id: "compute/api/scans" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-scans",
        label: "Get All CI Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-scans",
        label: "Add CLI Scan Result",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-scans-download",
        label: "Download CI Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-scans-id",
        label: "Get CI Image Scan Results",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Serverless",
    link: { type: "doc", id: "compute/api/serverless" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-serverless",
        label: "Get Serverless Function Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-serverless-download",
        label: "Download Serverless Function Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-serverless-evaluate",
        label: "Resolve Functions",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-serverless-names",
        label: "Get Serverless Function Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-serverless-scan",
        label: "Start Serverless Function Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-serverless-stop",
        label: "Stop Serverless Function Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Settings",
    link: { type: "doc", id: "compute/api/settings" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-settings-certificates",
        label: "Add Certificate Settings for Clients Accessing a Custom CA",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-certs",
        label: "Get Certificate Settings for Prisma Cloud Compute",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-certs",
        label: "Add Certificate Settings for Prisma Cloud Compute",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-console-certificate",
        label:
          "Add Certificate Settings for Clients Accessing Prisma Cloud Compute",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-custom-labels",
        label: "Get Alert Labels",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-custom-labels",
        label: "Add Alert Labels",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-defender",
        label: "Get Advanced Defender Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-intelligence",
        label: "Get Intelligence Stream Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-intelligence",
        label: "Add Intelligence Stream Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-ldap",
        label: "Get LDAP Integration Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-ldap",
        label: "Add LDAP Integration Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-license",
        label: "Get Prisma Cloud Compute License",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-license",
        label: "Add Prisma Cloud Compute License",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-logging",
        label: "Get Logging Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-logging",
        label: "Add Logging Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-logon",
        label: "Get Logon Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-logon",
        label: "Add Logon Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-oauth",
        label: "Get OAuth Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-oauth",
        label: "Add OAuth Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-oidc",
        label: "Get Open ID Connect Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-oidc",
        label: "Add Open ID Connect Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-proxy",
        label: "Get Proxy Settings of Prisma Cloud Compute",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-proxy",
        label: "Add Proxy Settings for Prisma Cloud Compute",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-registry",
        label: "Get Registry Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-registry",
        label: "Add Registry Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-settings-registry",
        label: "Update Registry Settings",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-saml",
        label: "Get SAML Settings of Prisma Cloud Compute",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-saml",
        label: "Add SAML Settings for Prisma Cloud Compute",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-scan",
        label: "Get Global Scan Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-scan",
        label: "Add Global Scan Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-tas",
        label: "Get TAS Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-tas",
        label: "Add TAS Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-telemetry",
        label: "Get Telemetry Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-telemetry",
        label: "Enable or Disable Telemetry Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-trusted-certificate",
        label: "Add a Certificate to a Trusted Certificate List",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-settings-trusted-certificates",
        label: "Add Trusted Certificate Settings",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-vm",
        label: "Get VM Image Scan Settings",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-settings-vm",
        label: "Update VM Image Scan Settings",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/get-settings-wildfire",
        label: "Wild Fire Settings",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Signup",
    link: { type: "doc", id: "compute/api/signup" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-signup",
        label: "Create Admin Account",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Stats",
    link: { type: "doc", id: "compute/api/stats" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-stats-app-firewall-count",
        label: "Application Firewall Count",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-compliance",
        label: "Get Compliance Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-compliance-download",
        label: "Download Compliance Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-stats-compliance-refresh",
        label: "Refresh Compliance Stats",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-daily",
        label: "Get Daily Compliance Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-dashboard",
        label: "Get Dashboard Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-events",
        label: "Get Event Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-license",
        label: "Get Event Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-vulnerabilities",
        label: "Get Vulnerability (CVEs) Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-vulnerabilities-download",
        label: "Download Vulnerability (CVEs) Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-vulnerabilities-impacted-resources",
        label: "Get Impacted Resources Vulnerability (CVE) Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-stats-vulnerabilities-impacted-resources-download",
        label: "Download Impacted Resources Vulnerability (CVE) Stats",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-stats-vulnerabilities-refresh",
        label: "Refresh Vulnerability Stats",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Statuses",
    link: { type: "doc", id: "compute/api/statuses" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-statuses-buildah",
        label: "Buildah Feature Status returns the buildah feature status",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-statuses-registry",
        label: "Get Registry Scan Status",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Tags",
    link: { type: "doc", id: "compute/api/tags" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-tags",
        label: "Get Tags",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-tags",
        label: "Add Tags",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/delete-tags-id",
        label: "Delete a Tag",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/put-tags-id",
        label: "Update a Tag",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/delete-tags-id-vuln",
        label: "Delete Tag Vulnerability Metadata",
        className: "api-method delete",
      },
      {
        type: "doc",
        id: "compute/api/post-tags-id-vuln",
        label: "Set Tag Vulnerability Metadata",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Tas-Droplets",
    link: { type: "doc", id: "compute/api/tas-droplets" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-tas-droplets",
        label: "Get TAS Droplets",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-tas-droplets-addresses",
        label: "TAS Cloud Controller Addresses",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-tas-droplets-download",
        label: "Download TAS Droplets",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-tas-droplets-progress",
        label: "View TAS Droplets Scan Progress",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-tas-droplets-scan",
        label: "Scan TAS Droplets",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-tas-droplets-stop",
        label: "Stop TAS Droplets Ongoing Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Trust",
    link: { type: "doc", id: "compute/api/trust" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-trust-data",
        label: "Get Trusted Repository, Image, and Registry",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/put-trust-data",
        label: "Update Trusted Repository, Image, and Registry",
        className: "api-method put",
      },
    ],
  },
  {
    type: "category",
    label: "Users",
    link: { type: "doc", id: "compute/api/users" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-users",
        label: "Get Users",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-users",
        label: "Add Users",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/put-users",
        label: "Update Users",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/put-users-password",
        label: "Update User Password",
        className: "api-method put",
      },
      {
        type: "doc",
        id: "compute/api/delete-users-id",
        label: "Delete Users",
        className: "api-method delete",
      },
    ],
  },
  {
    type: "category",
    label: "Util",
    link: { type: "doc", id: "compute/api/util" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-util-prisma-cloud-jenkins-plugin-hpi",
        label: "Download Jenkins Plugin for Prisma Cloud Compute",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-tas-tile",
        label: "Download VMware TAS Tile for Prisma Cloud Compute",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-arm-64-twistcli",
        label: "Download ARM64 twistcli for Linux OS",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-osx-arm-64-twistcli",
        label: "Download ARM64 twistcli for MacOS",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-osx-twistcli",
        label: "Download twistcli for MacOS",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-twistcli",
        label: "Download twistcli for Linux OS",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-util-windows-twistcli-exe",
        label: "Download twistcli for Microsoft Windows",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Version",
    link: { type: "doc", id: "compute/api/version" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-version",
        label: "Get Prisma Cloud Compute Version",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "Vms",
    link: { type: "doc", id: "compute/api/vms" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-vms",
        label: "Get VM Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-vms-download",
        label: "Download VM Image Scan Results",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-vms-labels",
        label: "Get VM Image Tags",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/get-vms-names",
        label: "Get VM Image Names",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "compute/api/post-vms-scan",
        label: "Start VM Image Scan",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "compute/api/post-vms-stop",
        label: "Stop VM Image Scan",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "Waas",
    link: { type: "doc", id: "compute/api/waas" },
    items: [
      {
        type: "doc",
        id: "compute/api/post-waas-openapi-scans",
        label: "Scan OpenAPI Specification File for WAAS Observations",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "_Ping",
    link: { type: "doc", id: "compute/api/ping" },
    items: [
      {
        type: "doc",
        id: "compute/api/get-ping",
        label: "Ping",
        className: "api-method get",
      },
    ],
  },
];
