components:
  schemas:
    access_policy_list:
      title: List Type for access_policy
      type: object
      properties:
        id:
          type: string
          example: 9d5104a0-1b0e-4f1d-be40-87f7810327e9
        role:
          description: role name
          type: string
          example: superuser
        inherited_from:
          description: lowest level tsg access policy belongs too
          type: string
          example: '1234567890'
        resource:
          description: 'prn:tsg_id:app_id:region_id:instance_id:resource_scope

            '
          type: string
          example: 'prn:123::::'
        principal:
          description: identity email
          type: string
          example: user@paloaltonetworks.com
        principal_type:
          description: identity
          type: string
          example: user
        principal_display_name:
          description: 'firstname lastname OR

            firstname OR

            username'
          type: string
          example: firstname lastname
    access_policy:
      title: Root Type for access_policy
      type: object
      properties:
        role:
          description: role name
          type: string
          example: superuser
        resource:
          description: 'prn:tsg_id:app_id:region_id:instance_id:resource_scope

            '
          type: string
          example: 'prn:123::::'
        principal:
          description: identity email
          type: string
          example: username@paloaltonetworks.com
        principal_type:
          description: user
          type: string
          example: user
        principal_display_name:
          description: 'firstname lastname OR

            firstname OR

            username'
          type: string
          example: username
    _pagination:
      required:
      - count
      - items
      type: object
      properties:
        count:
          description: Total count of the items
          type: integer
    access_policy_create_required:
      title: Root Type for access_policy
      required:
      - role
      - principal
      - resource
      type: object
      properties:
        role:
          description: 'The [role](/sase-services/docs/all-roles) that you are using
            for this access policy.

            '
          type: string
          example: superuser
        resource:
          description: "The PAN Resource Name that identifies the TSG for which you\
            \ are assigning\nthis access policy. It follows this format:\n\n  `prn:TSG_ID::::`\n"
          type: string
          example: 'prn:123::::'
        principal:
          description: "The email address for the user or \n[service account](/sase-services/docs/service-accounts)\
            \ to which you are assigning\nthis access policy. \n"
          type: string
          example: user@paloaltonetworks.com
    access_policy_create:
      title: Root Type for access_policy
      type: object
      properties:
        id:
          type: string
          example: 9d5104a0-1b0e-4f1d-be40-87f7810327e9
        role:
          description: role name
          type: string
          example: superuser
        resource:
          description: 'prn:tsg_id:app_id:region_id:instance_id:resource_scope

            '
          type: string
          example: 'prn:123::::'
        principal:
          description: identity email
          type: string
          example: user@paloaltonetworks.com
  responses:
    access_policy_list:
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/_pagination'
            - example:
                count: 1
                items:
                - id: 9d5104a0-1b0e-4f1d-be40-87f7810327e9
                  role: superuser
                  inherited_from: '1234567890'
                  resource: 'prn:123::::'
                  principal: user@paloaltonetworks.com
                  principal_type: user
                  principal_display_name: firstname lastname
            - type: object
              properties:
                items:
                  type: array
                  items:
                    allOf:
                    - $ref: '#/components/schemas/access_policy_list'
      description: Successful response.
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
openapi: 3.0.2
paths:
  /iam/v1/access_policies:
    post:
      requestBody:
        description: 'Specifies the role to be assigned to the principal for the specified

          resource.

          '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/access_policy_create_required'
        required: true
      tags:
      - AccessPolicies
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy_create'
          description: Successful response.
      operationId: createaccess_policy
      summary: Assign an access policy
      description: "Assign an access policy to a user or a service account. If the\n\
        email address supplied to the `principal` request body field is not\nknown\
        \ to the IAM service, a new user account is create to track that\nemail address.\
        \ However, no validation is performed to ensure that the\nnew user email address\
        \ corresponds to an email address used for a\nPalo Alto Networks customer\
        \ service account.\n\nIf the `principal` email address corresponds to a service\
        \ account, \nthe the specified [role](/sase-services/docs/roles) is applied\n\
        to that service account. Service account email addresses conform \nto the\
        \ following format:\n\n  `<service_account_name@<tsg_id>.iam.panServiceAccounts.com`\n"
      parameters: []
      security:
      - Bearer: []
    get:
      tags:
      - AccessPolicies
      parameters:
      - name: role
        description: role name
        schema:
          type: string
        in: query
      - name: principal
        description: principal (email)
        schema:
          type: string
        in: query
      responses:
        '200':
          $ref: '#/components/responses/access_policy_list'
      operationId: getaccess_policies
      summary: List all access policies
      description: 'List all access policies.

        '
      security:
      - Bearer: []
  /iam/v1/access_policies/{id}:
    get:
      tags:
      - AccessPolicies
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy'
          description: Successful response - returns a single `access_policy`.
      operationId: getaccess_policy
      summary: Get an access policy
      description: 'Get an access policy.

        '
      parameters:
      - name: id
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
    delete:
      tags:
      - AccessPolicies
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_policy'
          description: Successful Response
      operationId: deleteaccess_policy
      summary: Delete an access policy
      description: 'Delete an access policy.

        '
      parameters:
      - name: id
        schema:
          type: string
        in: path
        required: true
      security:
      - Bearer: []
info:
  title: Access Policies
  version: beta
  description: 'Access policies description.

    '
  contact: {}
tags:
- name: AccessPolicies
