components:
  schemas:
    RequestBody_UpgradesList:
      properties:
        filter:
          allOf:
          - {$ref: '#/components/schemas/UpgradeListFilter'}
          - {description: filter json object}
        properties:
          description: List of property json objects
          items: {$ref: '#/components/schemas/UpgradeListProperty'}
          type: array
      required: [properties, filter]
      type: object
    TimeFilter:
      properties:
        operator: {description: Filter operator that is one of the example values
            and is run on the property field, example: 'gt, lt, last_n_minutes, last_n_hours,
            last_n_days', type: string}
        property: {description: Filter property field that is one of the example values,
          example: 'event_time, update_time, updated_time', type: string}
        values:
          description: Filter property value
          example: minute, hour or day counts if property is event_time
          items: {type: string}
          type: array
      type: object
    UpgradeListFilter:
      description: "Upgrade list filter. Consists of a required operator and an array\
        \ of rules objects. \n"
      properties:
        operator: {description: "Must be `AND`. \n", type: string}
        rules:
          description: 'See [TimeFilter](/sase/docs/filters#timefilter).

            '
          items: {$ref: '#/components/schemas/TimeFilter'}
          type: array
      required: [operator]
      type: object
    UpgradeListProperty:
      properties:
        alias: {type: string}
        property: {description: "Upgrade list property. See [UpgradeListProperty](/sase/docs/filters#upgradelistproperty).\
            \   \n", example: 'sub_tenant_id, amiversion, current_software_version,
            last_upgrade_date,next_upgrade_scheduled_str, status, error, next_upgrade_scheduled',
          type: string}
      type: object
  securitySchemes:
    Bearer: {scheme: bearer, type: http}
info:
  contact: {}
  description: 'Use the Insights Resource API for retrieving the upgrade status.

    '
  title: Insights Resource API
  version: '1.0'
openapi: 3.0.2
paths:
  /mt/monitor/v1/agg/upgrades/list:
    post:
      description: "Retrieve an aggregated upgrade list across tenants.          \
        \          \n"
      operationId: post-mt-monitor-v1-agg-upgrades-list
      parameters:
      - description: "Must be `tenant`. Using the query parameter returns all the\
          \ aggregated responses for the current parent tenant and its child tenants.\
          \ If not used, the results for just the current tenant are returned. \n"
        example: tenant
        in: query
        name: agg_by
        schema: {type: string}
      - description: "Must be one of the following: `de`, `americas`, `europe`, `uk`,\
          \ `sg`, `ca`, `jp`, `au`, `in`. Returns details from the Cortex Data Lake\
          \ (CDL) region specified. If no region is specified, the default response\
          \ is `americas` CDL region.                                            \
          \           \n"
        example: americas
        in: header
        name: X-PANW-Region
        schema: {type: string}
      requestBody:
        content:
          application/json:
            examples:
              Upgrade List:
                value:
                  filter:
                    operator: AND
                    rules:
                    - operator: equals
                      property: start_date
                      values:
                      - ['2023-05-01T01:00:00.000Z']
                    - operator: equals
                      property: end_date
                      values:
                      - ['2023-05-01T01:00:00.000Z']
                  properties:
                  - {property: tenant_id}
                  - {property: sub_tenant_id}
                  - {property: current_version}
                  - {property: candidate_release_list}
                  - {property: customer_onboarded_locations}
                  - {property: upgrade_ts}
                  - {property: time_window}
                  - {property: compute_timezone}
                  - {property: upgrade_ts}
                  - {property: upgrade_type}
                  - {property: upgrade_version}
                  - {property: status}
            schema: {$ref: '#/components/schemas/RequestBody_UpgradesList'}
      responses:
        '200':
          content:
            application/json:
              examples:
                Upgrade List:
                  value:
                  - {tenant_id: <tenant_id>}
                  - {sub_tenant_id: <sub_tenant_id>}
                  - {current_version: <amiversion>}
                  - {candidate_release_list: <candidate_release_list>}
                  - {customer_onboarded_locations: <customer_onboarded_locations>}
                  - {upgrade_ts: <upgrade_ts>}
                  - {time_window: <time_window>}
                  - {compute_timezone: <compute_timezone>}
                  - {upgrade_ts: <upgrade_ts>}
                  - {upgrade_type: <upgrade_type>}
                  - {upgrade_version: <upgrade_version>}
                  - {status: <status>}
          description: Success
        '400': {description: Bad Request}
        '500': {description: Server Error}
      security:
      - Bearer: []
      summary: List upgrades
      tags: [InsightsResources]
servers:
- {url: 'https://api.sase.paloaltonetworks.com'}
tags:
- {name: InsightsResources}
