components:
  schemas:
    LicenseDetails:
      properties:
        expiry_ts: {description: License expiry timestamp in UTC, format: int64, type: integer}
        issue_ts: {description: License issuance timestamp in UTC, format: int64,
          type: integer}
        license_allocated_unit: {description: Units which is Mbps or no units at all
            (for MU), type: string}
        license_units: {description: Number of license units associated with the license,
          format: int32, type: integer}
        sku: {description: License Edition SKU, type: string}
      required: [license_units, expiry_ts, issue_ts, sku, license_allocated_unit]
      type: object
    LicenseQuota:
      properties:
        licenseDetails:
          additionalProperties: {$ref: '#/components/schemas/LicenseDetails'}
          description: Map of <Resource Name, License Details>, where Resource Name
            can be one of MU, RN, CDL
          type: object
        sub_tenant_id: {description: CDL Tenant Id, type: string}
        support:
          allOf:
          - {$ref: '#/components/schemas/Support'}
          - {description: 'Tenant Ids and Region info used for opening a support ticket

              '}
        tsg_id: {description: TSG Id, type: string}
      required: [tsg_id, sub_tenant_id, licenseDetails, support]
      type: object
    LicenseUtilization:
      properties:
        license_unit: {description: Units which can be Kbps or Mbps or no units at
            all (for MU), type: string}
        license_units: {description: Number of license units allocated to the tenant,
          format: double, type: number}
        license_units_used: {description: Number of license units used by the tenant,
          format: double, type: number}
        license_used_unit: {description: Units which can be Kbps or Mbps or no units
            at all (for MU), type: string}
        product_type: {description: 'Product Resource Type which is one of the following:
            RN, MU', type: string}
        sub_tenant_id: {description: CDL Tenant Id, type: string}
        utilization_percentage: {description: Utilization Percentage, format: double,
          type: number}
      required: [sub_tenant_id, utilization_percentage, product_type, license_units_used,
        license_used_unit, license_units, license_unit]
      type: object
    ServiceSetupStatus:
      properties:
        cdl_tenant_id: {description: CDL Tenant Id, type: string}
        operational_status: {description: 'Operational status which can be any one
            of the following values: No License, Warning, Error, Complete, Activating',
          type: string}
        service_setup_status: {description: 'Licensed service setup status which can
            be any one of the following values: No License, License Allocated, License
            Activated, Components Configured', type: string}
        tsg_id: {description: TSG Id, type: string}
      required: [tsg_id, cdl_tenant_id, operational_status, service_setup_status]
      type: object
    Support:
      properties:
        cdl_tenant_id: {description: CDL Tenant Id, type: string}
        cdl_tenant_region: {description: CDL Tenant Region, type: string}
        fawkes_tenant_id: {description: Fawkes Tenant Id, type: string}
        fawkes_tenant_region: {description: Fawkes Tenant Region, type: string}
        pa_tenant_id: {description: PA Tenant Id, type: string}
        pa_tenant_region: {description: PA Tenant Region, type: string}
        panorama_tenant_id: {description: Panorama Tenant Id, type: string}
        panorma_tenant_region: {description: Panorama Tenant Region, type: string}
      required: [cdl_tenant_id, pa_tenant_id, fawkes_tenant_id, panorama_tenant_id,
        cdl_tenant_region, pa_tenant_region, fawkes_tenant_region, panorma_tenant_region]
      type: object
  securitySchemes:
    Bearer: {scheme: bearer, type: http}
info:
  contact: {}
  description: 'Use the License Resource API for retrieving aggregated lists across
    tenants for license quotas, setup status, and utilization.

    '
  title: License Resource API
  version: '1.0'
openapi: 3.0.2
paths:
  /mt/monitor/v1/agg/custom/license/quota:
    get:
      description: 'Retrieve an aggregated list of license quotas across tenants.

        '
      operationId: get-mt-monitor-v1-agg-custom-license-quota
      parameters:
      - description: "Must be `tenant`. Using the query parameter returns all the\
          \ aggregated responses for the current parent tenant and its child tenants.\
          \ If not used, the results for just the current tenant are returned. \n"
        example: tenant
        in: query
        name: agg_by
        schema: {type: string}
      - description: "Must be one of the following: `de`, `americas`, `europe`, `uk`,\
          \ `sg`, `ca`, `jp`, `au`, `in`. Returns details from the Cortex Data Lake\
          \ (CDL) region specified. If no region is specified, the default response\
          \ is `americas` CDL region.                              \n"
        example: americas
        in: header
        name: X-PANW-Region
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/LicenseQuota'}
          description: Success
        '400': {description: Bad Request}
        '500': {description: Server Error}
      security:
      - Bearer: []
      summary: List license quota
      tags: [LicenseResources]
  /mt/monitor/v1/agg/custom/license/setup/status:
    get:
      description: 'Retrieve an aggregated list of all license service setup statuses
        across tenants.

        '
      operationId: get-mt-monitor-v1-agg-custom-license-setup-status
      parameters:
      - description: "Must be `tenant`. Using the query parameter returns all the\
          \ aggregated responses for the current parent tenant and its child tenants.\
          \ If not used, the results for just the current tenant are returned. \n"
        example: tenant
        in: query
        name: agg_by
        schema: {type: string}
      - description: "Must be one of the following: `de`, `americas`, `europe`, `uk`,\
          \ `sg`, `ca`, `jp`, `au`, `in`. Returns details from the Cortex Data Lake\
          \ (CDL) region specified. If no region is specified, the default response\
          \ is `americas` CDL region.                              \n"
        example: americas
        in: header
        name: X-PANW-Region
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ServiceSetupStatus'}
          description: Success
        '400': {description: Bad Request}
        '500': {description: Server Error}
      security:
      - Bearer: []
      summary: List license service setup status
      tags: [LicenseResources]
  /mt/monitor/v1/agg/custom/license/utilization:
    get:
      description: 'Retrieve an aggregated list of all license utilization across
        tenants.

        '
      operationId: get-mt-monitor-v1-agg-custom-license-utilization
      parameters:
      - description: "Must be `tenant`. Using the query parameter returns all the\
          \ aggregated responses for the current parent tenant and its child tenants.\
          \ If not used, the results for just the current tenant are returned. \n"
        example: tenant
        in: query
        name: agg_by
        schema: {type: string}
      - description: This is the time upto which user wants to see the data
        example: 98765432
        in: query
        name: end_time
        schema: {format: int64, type: integer}
      - description: This is the time from which user wants to see the data
        example: 123456789
        in: query
        name: start_time
        schema: {format: int64, type: integer}
      - description: The value can be MU(Mobile Users), RN(Remote Networks)
        example: MU,RN
        in: query
        name: product_type
        schema: {type: string}
      - description: This value is the license utilization threshold. It can be any
          integer number, default is -1
        example: -1
        in: query
        name: threshold
        schema: {format: double, type: number}
      - description: This is the time range for which user wants to see the data.The
          value can be last 15m, 1h, 3h, 24h, 7d, 30d
        example: 1h
        in: query
        name: time_period
        schema: {type: string}
      - description: This will be one of the 9 supported regions(americas, europe,
          au,de, jp, ca, sg, uk, in)
        example: americas
        in: header
        name: X-PANW-Region
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/LicenseUtilization'}
          description: Success
        '400': {description: Bad Request}
        '500': {description: Server Error}
      security:
      - Bearer: []
      summary: List license utilization
      tags: [LicenseResources]
servers:
- {url: 'https://api.sase.paloaltonetworks.com'}
tags:
- {name: LicenseResources}
