components:
  schemas:
    TenantHierarchy:
      properties:
        cdlTenantId: {description: CDL Tenant Id, type: string}
        children:
          description: List of Child Tenants which are of type Tenant Hierarchy
          items: {$ref: '#/components/schemas/TenantHierarchy'}
          type: array
        display_name: {description: Tenant Display Name, type: string}
        id: {description: TSG Id, type: string}
        license_activated: {description: License Activation Flag, type: boolean}
        region:
          description: Set of CDL regions which can be any one of  us01, eu01, au01,
            de01, jp01, ca01, sg01, uk01
          items: {type: string}
          type: array
          uniqueItems: true
        tenantLicenseType: {description: 'Tenant License Type which can be any one
            of PA_ONLY, SDWAN_ONLY, SASE, PA_SDWAN', type: string}
        vertical: {description: Customer Vertical, type: string}
      required: [cdlTenantId, display_name, id, license_activated, tenantLicenseType,
        vertical]
      type: object
  securitySchemes:
    Bearer: {scheme: bearer, type: http}
info:
  contact: {}
  description: 'Use the Tenant Resource API to list all tenants in the hierarchy.

    '
  title: Tenant Resources API
  version: '1.0'
openapi: 3.0.2
paths:
  /mt/monitor/v1/agg/custom/tenant/hierarchy:
    get:
      description: 'Retrieve an aggregated list of all tenants in the hierarchy.

        '
      operationId: get-mt-monitor-v1-agg-custom-tenant-hierarchy
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/TenantHierarchy'}
          description: Success
        '400': {description: Bad Request}
        '500': {description: Server Error}
      security:
      - Bearer: []
      summary: List tenant hierarchy
      tags: [TenantResources]
servers:
- {url: 'https://api.sase.paloaltonetworks.com'}
tags:
- {name: TenantResources}
