components:
  schemas:
    ScanContentResponse:
      properties:
        data_pattern_rule_1_verdict:
          enum:
          - MATCHED
          - NOT_EVALUATED
          - NOT_MATCHED
          type: string
        data_pattern_rule_2_verdict:
          enum:
          - MATCHED
          - NOT_EVALUATED
          - NOT_MATCHED
          type: string
        data_profile_name:
          description: Profile of the detection rules
          type: string
        file_name:
          description: Name of the scanned file
          type: string
        report_id:
          description: ID of the retrieved report
          type: string
        scanContentRawReport:
          description: List of report data
          type: string
        tenant_id:
          description: DLP tenant ID
          type: string
      title: ScanContentResponse
      type: object
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
info:
  contact: {}
  description: "Retrieve and analyze DLP scan reports containing comprehensive metadata\
    \ and detection information \nabout files and payloads. Reports provide detailed\
    \ insights into pattern matches, detection techniques, \nand sensitive content\
    \ findings without including unique incident information.\n"
  license:
    name: MIT
    url: https://opensource.org/license/mit
  title: Reports API
  version: 1.0.0
openapi: 3.0.2
paths:
  /v1/public/report/{reportId}:
    get:
      description: "Retrieve detailed information about a specific DLP report. A report\
        \ contains metadata and detection \ninformation about a file or payload, such\
        \ as pattern matches, but does not include unique incident \ninformation.\
        \ For user, application, URL, and channel information, refer to the Get Incident\
        \ Details endpoint.\n\nA single report can contain multiple incidents. You\
        \ can optionally retrieve snippets in the response. \nSnippets are evidence\
        \ or identifiable information associated with a pattern match. For example,\
        \ if you \nspecified a data pattern of \"Credit Card Number\", the API returns\
        \ the actual credit card number as the \nmatched snippet.\n\nFor more information,\
        \ see [Set Up Enterprise Data Loss Prevention](https://docs.paloaltonetworks.com/enterprise-dlp/enterprise-dlp-admin/set-up-enterprise-data-loss-prevention).\n"
      operationId: get-v1-public-report-reportid
      parameters:
      - description: The unique identifier of the DLP report to retrieve.
        in: path
        name: reportId
        required: true
        schema:
          type: string
      - description: (Optional) Boolean field when set to true, retrieves snippets
          from the DLP report.
        in: query
        name: fetchSnippets
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              examples:
                report with snippets:
                  value:
                    action: block
                    data_pattern_rule_1_verdict: MATCHED
                    data_profile_id: '11995044'
                    data_profile_name: PII
                    data_profile_version: 1
                    detection_time: 02/10/2024 23:34:14 GMT
                    extracted_file_size_in_bytes: 937
                    fileSha: a4d58aa3caeb73b56028f597de2b3263d64e2835f277f31c97be53bc76a29e47
                    file_name: SSNpattern
                    file_size_in_bytes: 930
                    file_type: pdf
                    report_id: '163570374'
                    scanContentRawReport:
                      data_pattern_rule_1_results:
                      - data_pattern_id: 6374e1b4dee31d91c40b179d
                        detection_frequency: 7
                        detections:
                        - detection: '*******00'
                          left: "\n\n\n\n\n\n tax id number ***-**-**99 abs cupp\n\
                            IBAN CH9300762011623852957 cusip "
                          origOffSet: 75
                          original_text: '*******00'
                          right: " | *****0BG4 DEA *****3839 | *****5341 CLIA 24C3872984\
                            \ | 05D0911402\nHETU number ******-856E | *******0490\L\
                            \nCPF | **************1-30 CNPJ\L\n*-****-****-6246 SHAKAI\
                            \ HOSH\u014C ZEI BANG\u014C SEIDO MAINANBA ****-**"
                          textLength: 0
                        - detection: '*******55'
                          left: "HOSH\u014C ZEI BANG\u014C SEIDO MAINANBA ****-****-6333\n\
                            UK Tax UTR ******1030 ******1031 NINO GP 32 76 63 *****280B\
                            \ Germany Tax ID *******1827 *******8911 *******8796 visa\
                            \ 4556501518562241 4929091695478411 aba "
                          origOffSet: 446
                          original_text: '*******55'
                          right: ' *****3532 ssn 098-07-33 16 480-33-1945 Canada SIN
                            *** *** 425 *****3197 Australia Tax ID 45322 1716 98754015
                            Access Key ID 022QF06E7MXBSH9DHM02 AWS Secret Key kWcrlUX5JEDGM/LtmEENI/
                            aVmYvHNif5zB+d9+c'
                          textLength: 0
                        - detection: '***-**-**99'
                          left: "\n\n\n\n\n\n tax id number "
                          origOffSet: 21
                          original_text: '***-**-**99'
                          right: " abs cupp\nIBAN CH9300762011623852957 cusip *******00\
                            \ | *****0BG4 DEA *****3839 | *****5341 CLIA 24C3872984\
                            \ | 05D0911402\nHETU number ******-856E | *******0490\L\
                            \nCPF | **************1-30 CNPJ\L\n*-****-***"
                          textLength: 0
                        edm_columns: []
                        high_confidence_detections: {}
                        high_confidence_frequency: 7
                        low_confidence_detections: {}
                        low_confidence_frequency: 7
                        matched_confidence_level: high
                        medium_confidence_detections: {}
                        medium_confidence_frequency: 0
                        name: National Id - US Social Security Number - SSN
                        proximity_detection_frequency: 7
                        state: EVALUATED
                        strict_detection_frequency: 0
                        technique: regex
                        type: predefined
                        unique_checksum_detection_frequency: 0
                        unique_detection_frequency: 7
                        unique_high_confidence_frequency: 7
                        unique_low_confidence_frequency: 7
                        unique_medium_confidence_frequency: 0
                        unique_proximity_detection_frequency: 7
                        unique_strict_detection_frequency: 0
                        version: 1
                        weighted_frequency: 0
                    tenant_id: '5886928188517009408'
                    txn_id: '163570374'
                    type: basic
                sample report:
                  value:
                    data_pattern_rule_1_verdict: MATCHED
                    data_profile_id: '11995014'
                    data_profile_name: Sensitive Content
                    detection_time: 10/15/2020 21:16:24 UTC
                    extracted_file_size_in_bytes: 1005635
                    fileSha: 90d068df2381ebd8342c99cf59907e7c9fc7ab3d7c4c6fdc2a3d814eb7ed374f
                    file_name: google_finance_template_1mb.txt
                    file_size_in_bytes: 1005626
                    file_type: txt
                    report_id: '483332512'
                    scanContentRawReport:
                      data_pattern_rule_1_results:
                      - data_pattern_id: 5ee3c51c99025d000161ab9a
                        detection_frequency: 0
                        high_confidence_frequency: 0
                        low_confidence_frequency: 0
                        medium_confidence_frequency: 0
                        name: Bank - American Bankers Association Routing Number -
                          ABA
                        proximity_detection_frequency: 0
                        state: EVALUATED
                        strict_detection_frequency: 0
                        technique: regex
                        type: predefined
                        unique_checksum_detection_frequency: 0
                        unique_detection_frequency: 0
                        unique_high_confidence_frequency: 0
                        unique_low_confidence_frequency: 0
                        unique_medium_confidence_frequency: 0
                        unique_proximity_detection_frequency: 0
                        unique_strict_detection_frequency: 0
                        version: 1
                        weighted_frequency: 0
                      - data_pattern_id: 5ee3c51c99025d000161aba6
                        detection_frequency: 0
                        high_confidence_frequency: 0
                        low_confidence_frequency: 0
                        medium_confidence_frequency: 0
                        name: Voyager Credit Card
                        proximity_detection_frequency: 0
                        state: EVALUATED
                        strict_detection_frequency: 0
                        technique: regex
                        type: predefined
                        unique_checksum_detection_frequency: 0
                        unique_detection_frequency: 0
                        unique_high_confidence_frequency: 0
                        unique_low_confidence_frequency: 0
                        unique_medium_confidence_frequency: 0
                        unique_proximity_detection_frequency: 0
                        unique_strict_detection_frequency: 0
                        version: 1
                        weighted_frequency: 0
                      - data_pattern_id: 5ee3c51d99025d000161ac52
                        detection_frequency: 3
                        high_confidence_frequency: 3
                        low_confidence_frequency: 3
                        matched_confidence_level: high
                        medium_confidence_frequency: 0
                        name: NationalId - US Social Security Number - SSN
                        proximity_detection_frequency: 3
                        state: EVALUATED
                        strict_detection_frequency: 0
                        technique: regex
                        type: predefined
                        unique_checksum_detection_frequency: 0
                        unique_detection_frequency: 3
                        unique_high_confidence_frequency: 3
                        unique_low_confidence_frequency: 3
                        unique_medium_confidence_frequency: 0
                        unique_proximity_detection_frequency: 3
                        unique_strict_detection_frequency: 0
                        version: 1
                        weighted_frequency: 0
                    tenant_id: '7830962012064884736'
                    txn_id: '483332512'
                    type: basic
              schema:
                $ref: '#/components/schemas/ScanContentResponse'
          description: OK
        '400':
          description: Bad Request. Got an invalid JSON.
        '401':
          description: Unauthorized access. An issue occurred during authentication.
            This can indicate an incorrect key, ID, or other invalid authentication
            parameters.
        '403':
          description: Forbidden access. The provided API Key does not have the required
            permissions to run this API.
        '500':
          description: Internal server error. A unified status for API communication
            type errors.
      security:
      - Bearer: []
      summary: Retrieve Report Details
      tags:
      - Reports API
servers:
- url: https://api.dlp.paloaltonetworks.com
tags:
- name: Reports API
