/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the api folder structure
    //   openApiSidebar: require("./api/sidebar").sidebar,
    saseauth: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/auth', // '.' means the current docs folder
        },
    ],
    saseiam: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/iam', // '.' means the current docs folder
        },
    ],
    saseinsights: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/insights', // '.' means the current docs folder
        },
    ],
    sasemt: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/mt-monitor', // '.' means the current docs folder
        },
    ],
    saseprismaaccess: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/prisma-access-config', // '.' means the current docs folder
        },
    ],
    sasesubscription: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/subscription', // '.' means the current docs folder
        },
    ],
    sasetenancy: [
        {
          type: 'autogenerated',
          dirName: 'sase/api/tenancy', // '.' means the current docs folder
        },
    ],
  };
  
  module.exports = sidebars;