openapi: 3.0.2
info:
  title: Subscription Service
  description: Manages subscriptions.
  version: '1.0'
  contact: {}
tags:
- name: Instance
paths:
  '/subscription/v1/instances':
    get:
      tags:
      - Instance
      parameters:
        - name: with_children
          description: |
            This parameter with any value causes this request to also
            return `instances` belonging to descendent TSGs.
            If this parameter is not used, then this API returns 
            `instances` for just the TSG identified in the access token
            used to authorize this request.
          schema:
            type: string
            enum: ['true', 'false']
          in: query
          required: false
      security:
        - Bearer: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/instance'
          description: Successful response - returns an array of `instance` entities.
      operationId: getinstances
      summary: List instances
      description: |
        Retrieves a list of all `instances` that belong to the 
        TSG identified in the access token used to authorize this request.
        Optionally retrieves a list of all `instances` belonging to
        this TSG's descendents.


components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    instance:
      title: Root Type for instance
      description: ''
      type: object
      properties:
        instance_id:
          type: string
        tsg_id:
          type: string
        app_id:
          type: string
        region:
          type: string
        created_by:
          type: string
        serial_number:
          type: string
        sku:
          type: string
        auth_code:
          type: string
        associations:
          type: array
          items:
            type: object
            properties:
              app_id:
                type: string
              tenant_id:
                type: string
              region:
                type: string
              serial_number:
                type: string
        url:
          type: string
        tenant_instance_name:
          type: string
        developer_defined_fields:
          type: object
          properties:
            name1:
              type: string
            name2:
              type: string
        description:
          type: string
        provisioning_message:
          type: string
        provisioning_status:
          type: string
        status:
          type: string
        message:
          type: string
        extra:
          type: object
          properties:
            purchased_size:
              format: int32
              type: integer
            wildfire_api_key:
              type: string
            app_display_name:
              type: string
            data_size:
              format: int32
              type: integer
            license_status:
              type: string
            channel_platform:
              type: string
            sales_account_name:
              type: string
            sales_account_id:
              type: string
            use_pubsub:
              type: boolean
            is_trial:
              type: boolean
            entitlement_group_id:
              type: string
            any_extra_field:
              type: string
        license_quota_id:
          description: ''
          type: string
      example:
        instance_id: D68FKGiM0V4NEbJbIfWHh
        tsg_id: jXe6iXutrmINurbNrjVun
        app_id: logging_service
        region: americas
        created_by: user@company.com
        serial_number: '55667788'
        sku: LGS1T
        auth_code: I886699
        associations:
        -
          app_id: prisma_access
          instance_id: '1122334455'
          region: americas
          serial_number: '5566778899'
        url: 'https://mylgs.logging-service.paloaltonetworks.com'
        tenant_instance_name: My CDL US
        support_account_name: Pepsi
        developer_defined_fields:
          name1: value1
          name2: value2
        description: This is an instance for demo
        provisioning_message: Recepter provisioning faild
        provisioning_status: complete
        status: running
        message: Temporarily unavailable
        extra:
          purchased_size: 1
          wildfire_api_key: fd995d5eb7c6d1ee0b97b9e0004dc5c815373312b1b579e4993d652b789776c6
          app_display_name: Cortex Data Lake
          data_size: 10
          license_status: ACTIVE
          channel_platform: INTERNAL
          sales_account_name: Palo Alto Networks
          sales_account_id: 0011000000oKIiiAAA
          use_pubsub: true
          is_trial: true
          entitlement_group_id: 0472e9ce-9c19-460f-a938-45b0165410fb
          any_extra_field: any extra value

    
