runtime: python27
api_version: "1"
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /(.*)/$
    static_files: www/\1/index.html
    upload: www/(.*)
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
