runtime: python27
api_version: "1"
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    application_readable: false
    static_files: index.html
    require_matching_file: false
    upload: index.html
  - url: /(.*)/$
    application_readable: false
    static_files: \1/index.html
    require_matching_file: false
    upload: .*/index.html
  - url: /(.+)
    application_readable: false
    static_files: \1
    require_matching_file: false
    upload: (.*)
