runtime: python27
api_version: "1"
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    static_files: index.html
    upload: index.html
  - url: /(.*)/$
    static_files: \1/index.html
    upload: (.*)
  - url: /(.*)
    static_files: \1
    upload: /(.*)
