module.exports = [
  {
    type: "category",
    label: "DataResources",
    link: { type: "doc", id: "sase/api/mt-monitor/data-resource-api" },
    items: [
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-alerts",
        label: "List alert count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-alerts-list",
        label: "List alerts by source",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-applicationusage",
        label: "List application usage by type",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-applications",
        label: "List application count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-applications-list",
        label: "List applications",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-applications-source",
        label: "List applications by source",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-applications-summary",
        label: "List app summary",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-incidents-count",
        label: "Get incident count by severity",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-incidents-impactedlist",
        label: "Get list of impacted objects",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-incidents-list",
        label: "Get list of incidents",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-incidents-tenants",
        label: "Get top tenants by incidents count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-incidents-trends",
        label:
          "Get incident trends(open critical, open warning, closed incidents)",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-location-list",
        label: "Get Location List",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-locationstenants",
        label: "Get number of tenants at location",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-locationsusers",
        label: "Get number of users at location(s)",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-resource",
        label: "List network inventory count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-serviceconnectivity",
        label: "List RN and SC site status count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-serviceconnectivity-cdlstatus",
        label: "List CDL connectivity status",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-serviceconnectivity-gatewaystatus",
        label: "List mobile gateway connection status",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-serviceconnectivity-licenseallocated",
        label: "Get total GP licenses allocated",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-serviceconnectivity-topoutliers",
        label: "List top outliers",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-serviceconnectivity-uniqueusers",
        label: "List unique GP users",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-threats",
        label: "List threat count",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-threats-list",
        label: "List threats",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-threats-source",
        label: "List threats by source",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-threats-summary",
        label: "List threat summary",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-url-summary",
        label: "List URL count summary",
        className: "api-method post",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-urllogs",
        label: "List top tenants with risky URLs",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "InsightsResources",
    link: { type: "doc", id: "sase/api/mt-monitor/insights-resource-api" },
    items: [
      {
        type: "doc",
        id: "sase/api/mt-monitor/post-mt-monitor-v-1-agg-upgrades-list",
        label: "List upgrades",
        className: "api-method post",
      },
    ],
  },
  {
    type: "category",
    label: "LicenseResources",
    link: { type: "doc", id: "sase/api/mt-monitor/license-resource-api" },
    items: [
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-custom-license-quota",
        label: "List license quota",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-custom-license-setup-status",
        label: "List license service setup status",
        className: "api-method get",
      },
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-custom-license-utilization",
        label: "List license utilization",
        className: "api-method get",
      },
    ],
  },
  {
    type: "category",
    label: "TenantResources",
    link: { type: "doc", id: "sase/api/mt-monitor/tenant-resources-api" },
    items: [
      {
        type: "doc",
        id: "sase/api/mt-monitor/get-mt-monitor-v-1-agg-custom-tenant-hierarchy",
        label: "List tenant hierarchy",
        className: "api-method get",
      },
    ],
  },
];
