components:
  schemas:
    tenant_service_group_create:
      type: object
      allOf:
      - required:
        - display_name
        type: object
        properties:
          parent_id:
            description: 'The TSG ID for this tenant service group''s parent.

              '
            allOf:
            - $ref: '#/components/schemas/_reference_id'
          display_name:
            description: 'The tenant service group''s display name.

              '
            type: string
            example: AT&T
          vertical:
            description: 'A token that identifies the business vertical supported
              by the SASE

              products managed by this TSG.

              '
            type: string
            enum:
            - High Tech
            - Education
            - Manufacturing
            - Hospitality
            - Professional & Legal Services
            - Wholesale & Retail
            - Finance
            - Telecommunications
            - State & Local Government
            - Transportation & Logistics
            - Federal Government
            - Media & Entertainment
            - Nonclassifiable Establishments
            - Healthcare
            - Utilities & Energy
            - Insurance
            - Agriculture
            - Pharma & Life Sciences
            - Construction
            - Aerospace & Defense
            - Real Estate
            - Restaurant/Food Industry
            - Other
            example: High Tech
    tenant_service_group_with_children:
      type: object
      allOf:
      - $ref: '#/components/schemas/tenant_service_group'
      - properties:
          children:
            type: array
            items:
              $ref: '#/components/schemas/tenant_service_group_with_children'
            readOnly: true
    _reference_id:
      type: string
      allOf:
      - $ref: '#/components/schemas/_id'
      readOnly: false
      example: 1995877003
    tenant_service_group_update:
      type: object
      properties:
        display_name:
          description: 'The tenant service group''s display name.

            '
          type: string
          example: AT&T
        vertical:
          description: 'A token that identifies the business vertical supported by
            the SASE

            products managed by this TSG.

            '
          type: string
          enum:
          - High Tech
          - Education
          - Manufacturing
          - Hospitality
          - Professional & Legal Services
          - Wholesale & Retail
          - Finance
          - Telecommunications
          - State & Local Government
          - Transportation & Logistics
          - Federal Government
          - Media & Entertainment
          - Nonclassifiable Establishments
          - Healthcare
          - Utilities & Energy
          - Insurance
          - Agriculture
          - Pharma & Life Sciences
          - Construction
          - Aerospace & Defense
          - Real Estate
          - Restaurant/Food Industry
          - Other
          example: High Tech
    _id:
      description: A unique identifier.
      maxLength: 10
      minLength: 10
      pattern: ^1[0-9]+$
      type: string
      readOnly: true
      example: '1378242802'
    tenant_service_group:
      type: object
      allOf:
      - required:
        - id
        type: object
        properties:
          id:
            description: The tenant service group's ID.
            allOf:
            - $ref: '#/components/schemas/_id'
            readOnly: true
          parent_id:
            description: 'The TSG ID for this tenant service group''s parent.

              '
            allOf:
            - $ref: '#/components/schemas/_reference_id'
          display_name:
            description: 'The tenant service group''s display name.

              '
            type: string
            example: AT&T
          vertical:
            description: 'A token that identifies the business vertical supported
              by the SASE

              products managed by this TSG.

              '
            type: string
            enum:
            - High Tech
            - Education
            - Manufacturing
            - Hospitality
            - Professional & Legal Services
            - Wholesale & Retail
            - Finance
            - Telecommunications
            - State & Local Government
            - Transportation & Logistics
            - Federal Government
            - Media & Entertainment
            - Nonclassifiable Establishments
            - Healthcare
            - Utilities & Energy
            - Insurance
            - Agriculture
            - Pharma & Life Sciences
            - Construction
            - Aerospace & Defense
            - Real Estate
            - Restaurant/Food Industry
            - Other
            example: High Tech
  parameters:
    tsg_id:
      name: tsg_id
      description: 'A unique identifier for the tenant service group.

        '
      schema:
        $ref: '#/components/schemas/_id'
      in: path
      required: true
  responses:
    tenant_service_group_response:
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/tenant_service_group'
      description: Successful response.
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
openapi: 3.0.2
paths:
  /tenancy/v1/tenant_service_groups/{tsg_id}:
    get:
      tags:
      - TenantServiceGroup
      responses:
        '200':
          $ref: '#/components/responses/tenant_service_group_response'
      operationId: get-tenancy-v1-tenant_service_groups-tsg_id
      summary: Get a tenant service group
      parameters:
      - $ref: '#/components/parameters/tsg_id'
      security:
      - Bearer: []
      description: 'Get a tenant service group by TSG ID.

        '
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tenant_service_group_update'
        required: true
      tags:
      - TenantServiceGroup
      responses:
        '200':
          $ref: '#/components/responses/tenant_service_group_response'
      operationId: put-tenancy-v1-tenant_service_groups-tsg_id
      summary: Update a tenant service group
      parameters:
      - $ref: '#/components/parameters/tsg_id'
      security:
      - Bearer: []
      description: "Update a tenant service group. If the TSG ID supplied \nin this\
        \ API's path does not match the TSG ID contained in\nthe access token used\
        \ to authenticate this request, this \nrequest will fail.\n"
    delete:
      tags:
      - TenantServiceGroup
      responses:
        '200':
          $ref: '#/components/responses/tenant_service_group_response'
      operationId: delete-tenancy-v1-tenant_service_groups-tsg_id
      summary: Delete a tenant service group
      parameters:
      - $ref: '#/components/parameters/tsg_id'
      security:
      - Bearer: []
      description: 'Delete a tenant service group. If the TSG ID supplied

        in this API''s path does not match the TSG ID contained in

        the access token used to authenticate this request, this

        request will fail.

        '
  /tenancy/v1/tenant_service_groups:
    post:
      tags:
      - TenantServiceGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tenant_service_group_create'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/tenant_service_group_response'
      operationId: post-tenancy-v1-tenant_service_groups
      summary: Create a tenant service group
      description: 'Create a tenant service group.

        The service account used to authenticate this request

        is granted `msp_superuser` access to the new tenant

        service group.

        '
      security:
      - Bearer: []
    get:
      tags:
      - TenantServiceGroup
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tenant_service_group_with_children'
              examples:
                hierarchy=true:
                  value:
                  - id: '1739543876'
                    display_name: parentTSG
                    children:
                    - id: '1435787597'
                      name: childTSG
                      parent_id: '1739543876'
                      vertical: High Tech
                  - id: '1335787596'
                    display_name: parent2
                hierarchy=false:
                  value:
                  - id: '1739543876'
                    display_name: parentTSG
                  - id: '1335787596'
                    display_name: parent2
                  - id: '1435787597'
                    name: childTSG
                    parent_id: '1739543876'
                    vertical: High Tech
          description: success response
      operationId: get-tenancy-v1-tenant_service_groups
      summary: List all tenant service groups
      description: 'Get a list of all the tenant service groups

        that are available to the service account used to

        authenticate this request.

        '
      parameters:
      - name: hierarchy
        description: 'Indicates whether the response structure lists groups in

          their hierarchy, or as an array of TSGs without regard to

          hierarchy. Default is false (don''t show hierarchy).


          If false, the order of the TSGs in the result array is not

          guaranteed.

          '
        schema:
          type: boolean
        in: query
      security:
      - Bearer: []
  /tenancy/v1/tenant_service_groups/{tsg_id}/operations/list_children:
    post:
      tags:
      - TenantServiceGroup
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tenant_service_group_with_children'
              examples:
                list_children:
                  value:
                  - id: '0'
                    display_name: string
                    parent_id: string
                  - id: '1'
                    display_name: string
                    parent_id: string
                list_children_with_id_field_only:
                  value:
                  - id: '0'
                  - id: '1'
                list_children_with_hierarchy:
                  value:
                  - id: '0'
                    display_name: string
                    parent_id: string
                    children:
                    - id: '2'
                      name: string
                      parent_id: '0'
                  - id: '1'
                    display_name: string
                list_children_with_hierarchy_and_id_field_only:
                  value:
                  - id: '0'
                    children:
                    - id: '2'
                  - id: '1'
          description: success response
      operationId: post-tenancy-v1-tenant_service_groups-tsg_id-operations-list_children
      summary: List tenant service group children
      parameters:
      - $ref: '#/components/parameters/tsg_id'
      - name: hierarchy
        description: 'If `true`, return the entire descendent hierarchy.

          If `false`, return only the immediate children of the

          TSG identified in this call''s path. Default is

          `false`.

          '
        schema:
          type: boolean
        in: query
      - name: include_self
        description: 'Indicates if the TSG used to generate this hierarchy is

          included in the resulting TSG list. `true` to include

          self. Default is `false`.

          '
        schema:
          type: boolean
        in: query
        required: false
      security:
      - Bearer: []
      description: 'List the child tenants of the tenant service group

        specified in this request. If the TSG ID supplied

        in this API''s path does not match the TSG ID contained in

        the access token used to authenticate this request, this

        request will fail.

        '
  /tenancy/v1/tenant_service_groups/{tsg_id}/operations/list_ancestors:
    post:
      tags:
      - TenantServiceGroup
      parameters:
      - name: sort
        description: 'Identifies the response structure''s sort order:


          * `asc` : From root to leaf.

          * `desc` : From leaf to root.

          '
        schema:
          enum:
          - asc
          - desc
          type: string
        in: query
        required: false
      - name: include_self
        description: 'Indicates if the TSG used to generate this hierarchy is

          included in the resulting TSG list. `true` to include

          self. Default is `false`.

          '
        schema:
          type: boolean
        in: query
        required: false
      - $ref: '#/components/parameters/tsg_id'
      - name: fields
        description: 'Provide a comma-separated list of fields you want returned.

          '
        schema:
          type: string
        in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tenant_service_group'
          description: Successful response.
      operationId: post-tenancy-v1-tenant_service_groups-tsg_id-operations-list_ancestors
      summary: List tenant service group ancestors
      security:
      - Bearer: []
      description: 'List the ancestor tenants of the tenant service group

        specified in this request. If the TSG ID supplied

        in this API''s path does not match the TSG ID contained in

        the access token used to authenticate this request, this

        request will fail.

        '
info:
  title: Tenant Service Group
  version: '1.0'
  description: 'Manages tenant service groups.

    '
  contact: {}
tags:
- name: TenantServiceGroup
