components:
  examples:
    create_instance_request:
      value:
        app_id: directory_sync
        is_eula_accepted: true
        region: americas
        support_account_id: 123456
        support_account_name: ABC inc
    create_instance_response:
      value:
        app_id: directory_sync
        job_id: 8dcad25f-3629-473b-9964-51bcbed53bb1
        status: initializing
        tenant_id: 123456789
        tenant_instance_name: Cloud Identity Engine
    instance_error_response:
      value:
        application_code: SUB_SERVICE_1004
        application_error: license_not_found_in_db
        error: Bad Request
        message: SUB_SERVICE_1004:license_not_found_in_db
        statusCode: 400
    onboard_instance_request:
      value:
      - allocation:
        - allocation_size: 1000
          app_id: prisma_access_edition
          license_type: LICENSE-SKU
        - allocation_size: 1000
          app_id: prisma_access_edition
          license_type: LICENSE-SKU
        allocation_type: SHARED
        app_id: prisma_access
        eula_accepted: true
        license_id: 123456789
        platform_region: americas
        tsg_name: tsg1
      - allocation:
        - allocation_size: 1
          app_id: logging_service
          license_type: LICENSE-SKU
        allocation_type: SHARED
        app_id: logging_service
        eula_accepted: true
        license_id: 123456789
        platform_region: americas
      - app_id: directory_sync
        tenant_id: 123456789
    onboard_instance_response:
      value:
        job_id: 8dcad25f-3629-473b-9964-51bcbed53bb1
  schemas:
    create_instance:
      description: ''
      properties:
        app_id:
          description: 'Application name.

            '
          type: string
        is_eula_accepted:
          description: 'Specify `True` to accept the EULA.

            '
          type: boolean
        region:
          description: 'Identifies the region where this instance will be provisioned.

            '
          example: americas
          type: string
        support_account_id:
          description: 'The support account ID used for this free license.

            '
          type: string
        support_account_name:
          description: 'The support account used for this free license.

            '
          type: string
      required:
      - app_id
      - support_account_id
      - support_account_name
      - region
      - is_eula_accepted
      title: Root Type for create free app instance Payload
      type: object
    create_instance_response:
      description: ''
      properties:
        job_id:
          type: string
        status:
          type: string
        tenant_id:
          type: string
        tenant_instance_name:
          type: string
      title: Create free instance response
      type: object
    instance:
      description: ''
      example:
        app_id: logging_service
        associations:
        - app_id: prisma_access
          instance_id: '1122334455'
          region: americas
          serial_number: '5566778899'
        auth_code: I886699
        created_by: user@company.com
        description: This is an instance for demo
        developer_defined_fields:
          name1: value1
          name2: value2
        extra:
          any_extra_field: any extra value
          app_display_name: Cortex Data Lake
          channel_platform: INTERNAL
          data_size: 10
          entitlement_group_id: 0472e9ce-9c19-460f-a938-45b0165410fb
          is_trial: true
          license_status: ACTIVE
          purchased_size: 1
          sales_account_id: 0011000000oKIiiAAA
          sales_account_name: Palo Alto Networks
          use_pubsub: true
          wildfire_api_key: fd995d5eb7c6d1ee0b97b9e0004dc5c815373312b1b579e4993d652b789776c6
        instance_id: D68FKGiM0V4NEbJbIfWHh
        message: Temporarily unavailable
        provisioning_message: Recepter provisioning faild
        provisioning_status: complete
        region: americas
        serial_number: '55667788'
        sku: LGS1T
        status: running
        support_account_name: Pepsi
        tenant_instance_name: My CDL US
        tsg_id: jXe6iXutrmINurbNrjVun
        url: https://mylgs.logging-service.paloaltonetworks.com
      properties:
        app_id:
          type: string
        associations:
          items:
            properties:
              app_id:
                type: string
              region:
                type: string
              serial_number:
                type: string
              tenant_id:
                type: string
            type: object
          type: array
        auth_code:
          type: string
        created_by:
          type: string
        description:
          type: string
        developer_defined_fields:
          properties:
            name1:
              type: string
            name2:
              type: string
          type: object
        extra:
          properties:
            any_extra_field:
              type: string
            app_display_name:
              type: string
            channel_platform:
              type: string
            data_size:
              format: int32
              type: integer
            entitlement_group_id:
              type: string
            is_trial:
              type: boolean
            license_status:
              type: string
            purchased_size:
              format: int32
              type: integer
            sales_account_id:
              type: string
            sales_account_name:
              type: string
            use_pubsub:
              type: boolean
            wildfire_api_key:
              type: string
          type: object
        instance_id:
          type: string
        license_quota_id:
          description: ''
          type: string
        message:
          type: string
        provisioning_message:
          type: string
        provisioning_status:
          type: string
        region:
          type: string
        serial_number:
          type: string
        sku:
          type: string
        status:
          type: string
        tenant_instance_name:
          type: string
        tsg_id:
          type: string
        url:
          type: string
      title: Root Type for instance
      type: object
    instance_error_response:
      description: ''
      properties:
        application_code:
          type: string
        application_error:
          type: string
        error:
          type: string
        message:
          type: string
        statusCode:
          type: string
      title: Instance error response
      type: object
    onboard_instance:
      description: ''
      items:
        properties:
          allocation:
            items:
              properties:
                allocation_size:
                  description: Number of license units to allocate.
                  type: string
                app_id:
                  description: Application name.
                  type: string
                license_type:
                  description: 'License SKU.

                    '
                  type: string
              type: object
            type: array
          allocation_type:
            description: 'Indicates whether the license allocation is full or shared.

              '
            enum:
            - FULL
            - SHARED
            type: string
          app_id:
            description: 'Application name.

              '
            type: string
          is_eula_accepted:
            description: 'Specify `True` to accept the EULA.

              '
            type: boolean
          license_id:
            description: 'The ID of the license you want to allocate. You can obtain
              license

              IDs using [GET /subscription/v1/licenses](/scm/api/subscription/get-subscription-v-1-licenses/).

              '
            type: string
          platform_region:
            description: 'Identifies the region where this instance will be provisioned.

              '
            example: americas
            type: string
          tenant_id:
            description: 'CIE tenant ID that this tenant will use.

              '
            type: string
          tsg_name:
            description: 'Identifies the child TSG to which this license is allocated.

              '
            type: string
        required:
        - app_id
        type: object
      title: Root Type for onboard instance Payload
      type: array
    onboard_instance_response:
      description: ''
      properties:
        job_id:
          type: string
      title: Onboard instance response
      type: object
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
info:
  contact: {}
  description: 'Manage application instances.

    '
  title: Instances
  version: '1.0'
openapi: 3.0.2
paths:
  /subscription/v1/instances:
    get:
      description: 'Retrieves a list of all `instances` that belong to the TSG identified
        in the access

        token used to authorize this request. Optionally retrieves a list of all `instances`

        belonging to this TSG''s descendents.


        An `instance` is a tenant with an allocated license.

        '
      operationId: get-subscription-v1-instances
      parameters:
      - description: 'This parameter with any value causes this request to also

          return `instances` belonging to descendent TSGs.

          If this parameter is not used, then this API returns

          `instances` for just the TSG identified in the access token

          used to authorize this request

          '
        in: query
        name: with_children
        required: false
        schema:
          enum:
          - 'true'
          - 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/instance'
                type: array
          description: Successful response - returns an array of `instance` entities.
      security:
      - Bearer: []
      summary: List instances
      tags:
      - Instance
    post:
      description: "Create an instance that is a child of the TSG identified in the\
        \ access\ntoken used to authorize this request. That is, use this API to allocate\
        \ a license to a child\ntenant.\n\nBefore you can allocate a license using\
        \ this call, you must first manually \n[claim or activate](https://docs.paloaltonetworks.com/common-services/subscription-and-tenant-management/get-started)\
        \ \nthe license. How you do this is determined by whether you are a multitenant\
        \ or single tenant user.\n\nThis API is asynchronous. It creates a provisioning\
        \ job. You cannot configure your instance until the provisioning\nis complete.\
        \ Use\n[GET /subscription/v1/instances](/scm/api/subscription/get-subscription-v-1-instances/)\n\
        to check the instance's provisioning status.\n"
      operationId: post-subscription-v1-instances
      requestBody:
        content:
          application/json:
            examples:
              create_instance_request:
                $ref: '#/components/examples/create_instance_request'
              onboard_instance_request:
                $ref: '#/components/examples/onboard_instance_request'
            schema:
              oneOf:
              - $ref: '#/components/schemas/create_instance'
              - $ref: '#/components/schemas/onboard_instance'
        description: Payload for create instances action
      responses:
        '200':
          content:
            application/json:
              examples:
                create_instance_response:
                  $ref: '#/components/examples/create_instance_response'
                onboard_instance_response:
                  $ref: '#/components/examples/onboard_instance_response'
              schema:
                oneOf:
                - $ref: '#/components/schemas/create_instance_response'
                - $ref: '#/components/schemas/onboard_instance_response'
          description: Successful
        '400':
          content:
            application/json:
              examples:
                instance_error_response:
                  $ref: '#/components/examples/instance_error_response'
              schema:
                $ref: '#/components/schemas/instance_error_response'
          description: Unsuccessful
      security:
      - Bearer: []
      summary: Create an instance
      tags:
      - Instance
servers:
- url: https://api.sase.paloaltonetworks.com
tags:
- name: Instance
