components:
  schemas:
    DeleteTokensRequest:
      additionalProperties: false
      properties: {}
      title: DeleteTokensRequest
      type: object
    DeleteTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/DeleteTokensResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/DeleteTokensResponse.Result'
          description: 'The API call response status.

            '
      title: DeleteTokensResponse
      type: object
    DeleteTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        TokenId:
          description: 'The unique ID of the token.

            '
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    DeleteTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: 'Default value of a successful response is 0. Any other number
            indicates an error code.

            '
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
    DescribeProgrammaticAccessRequest:
      additionalProperties: false
      properties: {}
      title: DescribeProgrammaticAccessRequest
      type: object
    DescribeProgrammaticAccessResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/DescribeProgrammaticAccessResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/DescribeProgrammaticAccessResponse.Result'
          description: 'The API call response status.

            '
      title: DescribeProgrammaticAccessResponse
      type: object
    DescribeProgrammaticAccessResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          description: 'Describes whether programmatic access is enabled for your
            account.

            '
          title: Enabled
          type: boolean
        MaxExpiryTime:
          description: 'The maximum expiry time of the token.

            '
          maximum: 1440
          minimum: 480
          title: Maxexpirytime
          type: integer
      title: ResponseData
      type: object
    DescribeProgrammaticAccessResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: 'Default value of a successful response is 0. Any other number
            indicates an error code.

            '
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudFirewallAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse.Result'
          description: 'The API call response status.

            '
      title: GetCloudFirewallAdminTokensResponse
      type: object
    GetCloudFirewallAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          description: 'Describes whether programmatic access is enabled for your
            account.

            '
          title: Enabled
          type: boolean
        ExpiryTime:
          description: 'The expiry time of the token.

            '
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          description: 'Your subscription key.

            '
          title: Subscriptionkey
          type: string
        TokenId:
          description: 'The unique ID of the token.

            '
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudFirewallAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: 'Default value of a successful response is 0. Any other number
            indicates an error code.

            '
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudGlobalRulestackAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse.Result'
          description: 'The API call response status.

            '
      title: GetCloudGlobalRulestackAdminTokensResponse
      type: object
    GetCloudGlobalRulestackAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          description: 'Describes whether programmatic access is enabled for your
            account.

            '
          title: Enabled
          type: boolean
        ExpiryTime:
          description: 'The expiry time of the token.

            '
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          description: 'Your subscription key.

            '
          title: Subscriptionkey
          type: string
        TokenId:
          description: 'The unique ID of the token.

            '
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudGlobalRulestackAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: 'Default value of a successful response is 0. Any other number
            indicates an error code.

            '
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudRulestackAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse.ResponseData'
          description: 'The API call response.

            '
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse.Result'
          description: 'The API call response status.

            '
      title: GetCloudRulestackAdminTokensResponse
      type: object
    GetCloudRulestackAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          description: 'Describes whether programmatic access is enabled for your
            account.

            '
          title: Enabled
          type: boolean
        ExpiryTime:
          description: 'The expiry time of the token.

            '
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          description: 'Your subscription key.

            '
          title: Subscriptionkey
          type: string
        TokenId:
          description: 'The unique ID of the token.

            '
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudRulestackAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          description: 'Default value of a successful response is 0. Any other number
            indicates an error code.

            '
          title: Errorcode
          type: integer
        Reason:
          description: 'The error description.

            '
          title: Reason
          type: string
      title: Result
      type: object
info:
  contact: {}
  description: "Generate JSON Web Token (JWT) to get programmatic access to authenticate\
    \ API calls.  \n\nCloud NGFW Programmatic access allows you to create and manage\
    \ NGFWs and rulestacks using REST APIs. Using these APIs, you can invoke actions\
    \ on Cloud NGFW resources (NGFW and rulestacks) through an application or third-party\
    \ tool.  \n\nCloud NGFW Programmatic access is disabled by default.  \n\nFor more\
    \ information, see [Enable Programmatic Access for Cloud NGFW](/cloudngfw/aws/api).\
    \  \n\nFor information about roles and permissions, see [Cloud NGFW roles and\
    \ permissions](https://docs.paloaltonetworks.com/cloud-ngfw/aws/cloud-ngfw-on-aws/getting-started-with-cloud-ngfw-for-aws/invite-users)\
    \ table.\n"
  title: Manage API Tokens
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/mgmt/tokens:
    get:
      description: "Retrieve the programmatic access information of your account.\
        \ \n\n>This service is available for Tenant Admins only."
      operationId: get-v1-mgmt-tokens
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeProgrammaticAccessRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeProgrammaticAccessResponse'
          description: OK
      summary: Describe programmatic access
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudfirewalladmin:
    get:
      description: "Fetch the JSON Web Token (JWT) to enable programmatic access for\
        \ a cloud firewall admin role.             \n"
      operationId: get-v1-mgmt-tokens-cloudfirewalladmin
      parameters:
      - description: ''
        in: query
        name: expirytime
        required: false
        schema:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudFirewallAdmin
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudglobalrulestackadmin:
    get:
      description: 'Fetch the JSON Web Token (JWT) to enable programmatic access for
        a cloud global rulestack admin role.

        '
      operationId: get-v1-mgmt-tokens-cloudglobalrulestackadmin
      parameters:
      - description: ''
        in: query
        name: expirytime
        required: false
        schema:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudGlobalRulestackAdmin
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudrulestackadmin:
    get:
      description: 'Fetch the JSON Web Token (JWT) to enable programmatic access for
        a cloud local rulestack admin role.

        '
      operationId: get-v1-mgmt-tokens-cloudrulestackadmin
      parameters:
      - description: ''
        in: query
        name: expirytime
        required: false
        schema:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudRulestackAdmin
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/{TokenId}:
    delete:
      description: "Revoke the JSON Web Token (JWT) used for programmatic access.\
        \ This is considered as logout. \n"
      operationId: delete-v1-mgmt-tokens-TokenId
      parameters:
      - description: 'The unique ID of the token.

          '
        in: path
        name: TokenId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTokensRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTokensResponse'
          description: OK
      summary: Delete programmatic access token
      tags:
      - ManageAPITokens
servers:
- url: https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com
tags:
- name: ManageAPITokens
