components:
  schemas:
    ListURLPredefinedCategoriesResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/ListURLPredefinedCategoriesResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/ListURLPredefinedCategoriesResponse.Result',
          description: 'The API call response status.

            '}
      title: ListURLPredefinedCategoriesResponse
      type: object
    ListURLPredefinedCategoriesResponse.PredefinedURLCategory:
      additionalProperties: false
      properties:
        Action: {description: 'Predefined URL category action.

            ', title: Action, type: string}
        Name: {description: 'Name of the predefined URL category.

            ', title: Name, type: string}
      required: [Action, Name]
      title: PredefinedURLCategory
      type: object
    ListURLPredefinedCategoriesResponse.ResponseData:
      additionalProperties: false
      properties:
        CategoriesRunning:
          description: 'Predefined URL categories in run state.

            '
          items: {$ref: '#/components/schemas/ListURLPredefinedCategoriesResponse.PredefinedURLCategory'}
          title: Categoriesrunning
          type: array
        NextToken: {description: 'If the number of predefined URLs available for retrieval
            exceeds the maximum you requested, NGFW returns a NextToken value in response.
            To retrieve the next batch of URLs, use this token in your next request.

            ', title: Nexttoken, type: string}
      title: ResponseData
      type: object
    ListURLPredefinedCategoriesResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidRequestException\u2014Operation failed due to invalid\
            \ request. For example, unsupported parameter name or value in the request.\n\
            * ResourceNotFoundException\u2014Unable to locate a resource using the\
            \ parameters you provided.\n* ThrottlingException\u2014Operation failed\
            \ due to throttling limitations.\n\n500\u2014Bad request \n* InternalServerError\u2014\
            Your request is valid but Cloud NGFW could not perform the operation due\
            \ to a system issue.\n", title: Errorcode, type: integer}
        Reason: {description: 'The error description.

            ', title: Reason, type: string}
      title: Result
      type: object
info:
  contact: {}
  description: 'Use predefined URL categories in security rules to block or allow
    access to websites.


    ### Permission Policies


    | Action                            | Local Firewall Administrator | Local Rulestack
    Administrator | Global Rulestack Administrator|

    | --------------------------------- | :--------------------------: | :---------------------------:
    | :---------------------------: |

    | List pre-defined URL Categories   | **&#9745;**                  | **&#9745;**                   |
    **&#9745;**                   |

    '
  title: Manage Predefined URL Categories
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/config/urlcategories:
    get:
      description: 'View the predefined URL categories.

        '
      operationId: get-v1-config-urlcategories
      parameters:
      - description: 'If the number of predefined URL categories available for retrieval
          exceeds the maximum you requested, NGFW returns a NextToken value in response.
          To retrieve the next batch of URL categories, use this token in your next
          request.

          '
        in: query
        name: nexttoken
        required: false
        schema: {title: Nexttoken, type: string}
      - description: 'The maximum number of predefined URL categories that you want
          NGFW to return for this request.

          '
        in: query
        name: maxresults
        required: false
        schema: {default: 1024, maximum: 1024, minimum: 1, title: Maxresults, type: integer}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ListURLPredefinedCategoriesResponse'}
          description: OK
      summary: List Pre-defined URL Categories
      tags: [ManagePredefinedURLCategories]
servers:
- {url: 'https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com'}
tags:
- {name: ManagePredefinedURLCategories}
