components:
  schemas:
    FirewallListTagsForResourceRequest:
      additionalProperties: false
      properties:
        AccountId: {description: 'The unique ID of the account.

            ', title: Accountid, type: string}
        MaxResults: {default: 1024, description: "The maximum number of tags that\
            \ you want NGFW to return for this request. \n", maximum: 1024, minimum: 1,
          title: Maxresults, type: integer}
        NextToken: {description: 'If the number of tags available for retrieval exceeds
            the maximum you requested, NGFW returns a NextToken value in response.
            To retrieve the next batch of tags, use this token in your next request.

            ', title: Nexttoken, type: string}
      required: [AccountId]
      title: FirewallListTagsForResourceRequest
      type: object
    FirewallListTagsForResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/FirewallListTagsForResourceResponse.ResponseData'}
        ResponseStatus: {$ref: '#/components/schemas/FirewallListTagsForResourceResponse.Result'}
      title: FirewallListTagsForResourceResponse
      type: object
    FirewallListTagsForResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        AccountId: {description: 'The unique ID of the account.

            ', title: Accountid, type: string}
        FirewallName: {description: 'Name of the NGFW, unique in a region for each
            customer.

            ', title: Firewallname, type: string}
        NextToken: {description: 'If the number of tags available for retrieval exceeds
            the maximum you requested, NGFW returns a NextToken value in response.
            To retrieve the next batch of tags, use this token in your next request.

            ', title: Nexttoken, type: string}
        Tags:
          description: 'The tags associated with the firewall.

            '
          items: {$ref: '#/components/schemas/FirewallListTagsForResourceResponse.TagEntry'}
          title: Tags
          type: array
      title: ResponseData
      type: object
    FirewallListTagsForResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "400\u2014HTTP bad request\n* InvalidOperationException\u2014\
            Operation failed because it is not valid. For example, when you delete\
            \ an NGFW or rulestack in use.\n* InvalidRequestException\u2014Operation\
            \ failed due to invalid request. For example, unsupported parameter name\
            \ or value in the request.\n* LimitExceededException\u2014Operation failed\
            \ due to violation in limit settings.\n* ResourceNotFoundException\u2014\
            Unable to locate a resource using the parameters you provided.\n* ThrottlingException\u2014\
            Operation failed due to throttling limitations.   \n\n500\u2014Bad request\
            \ \n* InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: "The error description.\n         \n", title: Reason,
          type: string}
      title: Result
      type: object
    FirewallListTagsForResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    FirewallTagResourceRequest:
      additionalProperties: false
      properties:
        AccountId: {description: 'The unique ID of the account.

            ', title: Accountid, type: string}
        Tags:
          description: 'The tags associated with the firewall.

            '
          items: {$ref: '#/components/schemas/FirewallTagResourceRequest.TagEntry'}
          maxItems: 50
          title: Tags
          type: array
      required: [AccountId, Tags]
      title: FirewallTagResourceRequest
      type: object
    FirewallTagResourceRequest.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            .

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    FirewallTagResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/FirewallTagResourceResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/FirewallTagResourceResponse.Result',
          description: 'The API call response status.

            '}
      title: FirewallTagResourceResponse
      type: object
    FirewallTagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        FirewallName: {description: 'Name of the NGFW, unique in a region for each
            customer.

            ', title: Firewallname, type: string}
        Tags:
          description: 'The tags associated with the firewall.

            '
          items: {$ref: '#/components/schemas/FirewallTagResourceResponse.TagEntry'}
          title: Tags
          type: array
      title: ResponseData
      type: object
    FirewallTagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: "The error description. \n            \n", title: Reason,
          type: string}
      title: Result
      type: object
    FirewallTagResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    FirewallUntagResourceRequest:
      additionalProperties: false
      properties:
        AccountId: {description: 'The unique ID of the account.

            ', title: Accountid, type: string}
        TagKeys:
          description: 'A unique identifier in the key-value pair.

            '
          items: {maxLength: 128, minLength: 1, pattern: ^.*$, type: string}
          maxItems: 50
          title: Tagkeys
          type: array
      required: [AccountId, TagKeys]
      title: FirewallUntagResourceRequest
      type: object
    FirewallUntagResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/FirewallUntagResourceResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/FirewallUntagResourceResponse.Result',
          description: 'The API call response status.

            '}
      title: FirewallUntagResourceResponse
      type: object
    FirewallUntagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        AccountId: {description: "The unique ID of the account.        \n", title: Accountid,
          type: string}
        FirewallName: {description: 'Name of the NGFW, unique in a region for each
            customer.

            ', title: Firewallname, type: string}
        TagKeys:
          description: 'A unique identifier in the key-value pair.

            '
          items: {type: string}
          title: Tagkeys
          type: array
      title: ResponseData
      type: object
    FirewallUntagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: 'The error description.

            ', title: Reason, type: string}
      title: Result
      type: object
info:
  contact: {}
  description: 'Apply tags to help search and filter your firewall resources.

    '
  title: Manage Cloud NGFW Tags
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/config/ngfirewalls/{ngfirewallname}/tags:
    delete:
      description: 'Remove the tags associated with an NGFW resource.

        '
      operationId: delete-v1-config-ngfirewalls-ngfirewallname-tags
      parameters:
      - description: 'The name of the NGFW.

          '
        in: path
        name: ngfirewallname
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/FirewallUntagResourceRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/FirewallUntagResourceResponse'}
          description: OK
      summary: Firewall Untag Resource
      tags: [ManageNGFWTags]
    get:
      description: 'Retrieve the tags associated with an NGFW resource.

        '
      operationId: get-v1-config-ngfirewalls-ngfirewallname-tags
      parameters:
      - description: 'The name of the NGFW.

          '
        in: path
        name: ngfirewallname
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/FirewallListTagsForResourceRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/FirewallListTagsForResourceResponse'}
          description: OK
      summary: List Firewall Tags
      tags: [ManageNGFWTags]
    post:
      description: 'Add tags to an NGFW resource. You can tag the resources that you
        manage through NGFW policies.

        '
      operationId: post-v1-config-ngfirewalls-ngfirewallname-tags
      parameters:
      - description: 'The name of the NGFW.

          '
        in: path
        name: ngfirewallname
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/FirewallTagResourceRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/FirewallTagResourceResponse'}
          description: OK
      summary: Firewall Tag Resource
      tags: [ManageNGFWTags]
servers:
- {url: 'https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com'}
tags:
- {name: ManageNGFWTags}
