components:
  schemas:
    DescribeProgrammaticAccessRequest:
      additionalProperties: false
      properties: {}
      title: DescribeProgrammaticAccessRequest
      type: object
    DescribeProgrammaticAccessResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/DescribeProgrammaticAccessResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/DescribeProgrammaticAccessResponse.Result'
      title: DescribeProgrammaticAccessResponse
      type: object
    DescribeProgrammaticAccessResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          title: Enabled
          type: boolean
        MaxExpiryTime:
          maximum: 1440
          minimum: 480
          title: Maxexpirytime
          type: integer
      title: ResponseData
      type: object
    DescribeProgrammaticAccessResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudFirewallAdminTokensRequest:
      additionalProperties: false
      properties:
        ExpiryTime:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      title: GetCloudFirewallAdminTokensRequest
      type: object
    GetCloudFirewallAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse.Result'
      title: GetCloudFirewallAdminTokensResponse
      type: object
    GetCloudFirewallAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          title: Enabled
          type: boolean
        ExpiryTime:
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          title: Subscriptionkey
          type: string
        TokenId:
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudFirewallAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudGlobalRulestackAdminTokensRequest:
      additionalProperties: false
      properties:
        ExpiryTime:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      title: GetCloudGlobalRulestackAdminTokensRequest
      type: object
    GetCloudGlobalRulestackAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse.Result'
      title: GetCloudGlobalRulestackAdminTokensResponse
      type: object
    GetCloudGlobalRulestackAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          title: Enabled
          type: boolean
        ExpiryTime:
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          title: Subscriptionkey
          type: string
        TokenId:
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudGlobalRulestackAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
    GetCloudRulestackAdminTokensRequest:
      additionalProperties: false
      properties:
        ExpiryTime:
          default: 30
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
      title: GetCloudRulestackAdminTokensRequest
      type: object
    GetCloudRulestackAdminTokensResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse.Result'
      title: GetCloudRulestackAdminTokensResponse
      type: object
    GetCloudRulestackAdminTokensResponse.ResponseData:
      additionalProperties: false
      properties:
        Enabled:
          title: Enabled
          type: boolean
        ExpiryTime:
          maximum: 1440
          minimum: 5
          title: Expirytime
          type: integer
        SubscriptionKey:
          title: Subscriptionkey
          type: string
        TokenId:
          title: Tokenid
          type: string
      title: ResponseData
      type: object
    GetCloudRulestackAdminTokensResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
info:
  contact: {}
  description: 'Generate JSON Web Token (JWT) to get programmatic access and authenticate
    API calls.

    '
  title: Manage API Tokens
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/mgmt/tokens:
    get:
      description: ''
      operationId: get-v1-mgmt-tokens
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeProgrammaticAccessRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeProgrammaticAccessResponse'
          description: OK
      summary: Describe programmatic access
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudfirewalladmin:
    get:
      description: ''
      operationId: get-v1-mgmt-tokens-cloudfirewalladmin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCloudFirewallAdminTokensRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudFirewallAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudFirewallAdmin
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudglobalrulestackadmin:
    get:
      description: ''
      operationId: get-v1-mgmt-tokens-cloudglobalrulestackadmin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudGlobalRulestackAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudGlobalRulestackAdmin
      tags:
      - ManageAPITokens
  /v1/mgmt/tokens/cloudrulestackadmin:
    get:
      description: ''
      operationId: get-v1-mgmt-tokens-cloudrulestackadmin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCloudRulestackAdminTokensRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCloudRulestackAdminTokensResponse'
          description: OK
      summary: Get programmatic access token for CloudRulestackAdmin
      tags:
      - ManageAPITokens
servers:
- url: https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com
tags:
- name: ManageAPITokens
