components:
  schemas:
    RulestackListTagsForResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/RulestackListTagsForResourceResponse.ResponseData'}
        ResponseStatus: {$ref: '#/components/schemas/RulestackListTagsForResourceResponse.Result'}
      title: RulestackListTagsForResourceResponse
      type: object
    RulestackListTagsForResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        NextToken: {description: 'If the number of tags available for retrieval exceeds
            the maximum you requested, Cloud NGFW returns a NextToken value in response.
            To retrieve the next batch of tags, use this token in your next request.

            ', title: Nexttoken, type: string}
        RuleStackName: {description: 'Name of the rulestack.

            ', title: Rulestackname, type: string}
        Tags:
          description: 'The tags associated with the rulestack.

            '
          items: {$ref: '#/components/schemas/RulestackListTagsForResourceResponse.TagEntry'}
          title: Tags
          type: array
      title: ResponseData
      type: object
    RulestackListTagsForResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: 'The error description.

            ', title: Reason, type: string}
      title: Result
      type: object
    RulestackListTagsForResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    RulestackTagResourceRequest:
      additionalProperties: false
      properties:
        Tags:
          description: 'The tags associated with the rulestack.

            '
          items: {$ref: '#/components/schemas/RulestackTagResourceRequest.TagEntry'}
          maxItems: 50
          title: Tags
          type: array
      required: [Tags]
      title: RulestackTagResourceRequest
      type: object
    RulestackTagResourceRequest.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            .

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    RulestackTagResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/RulestackTagResourceResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/RulestackTagResourceResponse.Result',
          description: 'The API call response status.

            '}
      title: RulestackTagResourceResponse
      type: object
    RulestackTagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        RuleStackName: {title: Rulestackname, type: string}
        Tags:
          description: 'The tags associated with the rulestack.

            '
          items: {$ref: '#/components/schemas/RulestackTagResourceResponse.TagEntry'}
          title: Tags
          type: array
      title: ResponseData
      type: object
    RulestackTagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: "The error description. \n", title: Reason, type: string}
      title: Result
      type: object
    RulestackTagResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key: {description: 'A unique identifier in the key-value pair. The constant
            that defines the data set.

            ', title: Key, type: string}
        Value: {description: 'The variable that belongs to the data set.

            ', title: Value, type: string}
      required: [Key, Value]
      title: TagEntry
      type: object
    RulestackUntagResourceRequest:
      additionalProperties: false
      properties:
        TagKeys:
          description: 'Keys and values of the tags.

            '
          items: {maxLength: 128, minLength: 1, pattern: ^.*$, type: string}
          maxItems: 50
          title: Tagkeys
          type: array
      required: [TagKeys]
      title: RulestackUntagResourceRequest
      type: object
    RulestackUntagResourceResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/RulestackUntagResourceResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/RulestackUntagResourceResponse.Result',
          description: 'The API call response status.

            '}
      title: RulestackUntagResourceResponse
      type: object
    RulestackUntagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        RuleStackName: {description: 'Name of the rulestack.

            ', title: Rulestackname, type: string}
        TagKeys:
          description: "A unique identifier in the key-value pair.      \n"
          items: {type: string}
          title: Tagkeys
          type: array
      title: ResponseData
      type: object
    RulestackUntagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: "The error description.            \n", title: Reason,
          type: string}
      title: Result
      type: object
info:
  contact: {}
  description: "Apply tags to help search and filter your rulestack resources.\n\n\
    ### Permission Policies\n\n| Action                         | Local Firewall Administrator\
    \  | Local Rulestack Administrator | Global Rulestack Administrator |\n| ------------------------------\
    \ | :---------------------------: | :---------------------------: | :----------------------------:\
    \ |\n| Tag Resource                   | **&#9745;**                   | **&#9745;**\
    \                   | **&#9745;**                    | \n| Untag Resource    \
    \             | **&#9745;**                   | **&#9745;**                  \
    \ | **&#9745;**                    |                      \n| List Firewall Tags\
    \             | &#9744;                       | **&#9745;**                  \
    \ | **&#9745;**                    |\n"
  title: Manage Rulestack Tags
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/config/rulestacks/{rulestackname}/tags:
    delete:
      description: 'Remove tags with specified keys from a specified rulestack resource.

        '
      operationId: delete-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/RulestackUntagResourceRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/RulestackUntagResourceResponse'}
          description: OK
      summary: Rulestack Untag Resource
      tags: [ManageRulestackTags]
    get:
      description: 'Retrieve the tags associated with a specified rulestack resource.

        '
      operationId: get-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema: {type: string}
      - description: "The maximum number of tags that you want NGFW to return for\
          \ this request. \n"
        in: query
        name: maxresults
        required: false
        schema: {default: 1024, maximum: 1024, minimum: 1, title: Maxresults, type: integer}
      - description: 'If the number of tags available for retrieval exceeds the maximum
          you requested, Cloud NGFW returns a NextToken value in response. To retrieve
          the next batch of tags, use this token in your next request.

          '
        in: query
        name: nexttoken
        required: false
        schema: {title: Nexttoken, type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/RulestackListTagsForResourceResponse'}
          description: OK
      summary: List Rulestack Tags
      tags: [ManageRulestackTags]
    post:
      description: 'Add tags to a specific rulestack resource. You can tag the AWS
        resources that you manage through rulestacks.

        '
      operationId: post-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/RulestackTagResourceRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/RulestackTagResourceResponse'}
          description: OK
      summary: Rulestack Tag Resource
      tags: [ManageRulestackTags]
servers:
- {url: 'https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com'}
tags:
- {name: ManageRulestackTags}
