components:
  schemas:
    RulestackListTagsForResourceResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/RulestackListTagsForResourceResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/RulestackListTagsForResourceResponse.Result'
      title: RulestackListTagsForResourceResponse
      type: object
    RulestackListTagsForResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        NextToken:
          title: Nexttoken
          type: string
        RuleStackName:
          title: Rulestackname
          type: string
        Tags:
          items:
            $ref: '#/components/schemas/RulestackListTagsForResourceResponse.TagEntry'
          title: Tags
          type: array
      title: ResponseData
      type: object
    RulestackListTagsForResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
    RulestackListTagsForResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key:
          title: Key
          type: string
        Value:
          title: Value
          type: string
      required:
      - Key
      - Value
      title: TagEntry
      type: object
    RulestackTagResourceRequest:
      additionalProperties: false
      properties:
        Tags:
          items:
            $ref: '#/components/schemas/RulestackTagResourceRequest.TagEntry'
          maxItems: 50
          title: Tags
          type: array
      required:
      - Tags
      title: RulestackTagResourceRequest
      type: object
    RulestackTagResourceRequest.TagEntry:
      additionalProperties: false
      properties:
        Key:
          title: Key
          type: string
        Value:
          title: Value
          type: string
      required:
      - Key
      - Value
      title: TagEntry
      type: object
    RulestackTagResourceResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/RulestackTagResourceResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/RulestackTagResourceResponse.Result'
      title: RulestackTagResourceResponse
      type: object
    RulestackTagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        RuleStackName:
          title: Rulestackname
          type: string
        Tags:
          items:
            $ref: '#/components/schemas/RulestackTagResourceResponse.TagEntry'
          title: Tags
          type: array
      title: ResponseData
      type: object
    RulestackTagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
    RulestackTagResourceResponse.TagEntry:
      additionalProperties: false
      properties:
        Key:
          title: Key
          type: string
        Value:
          title: Value
          type: string
      required:
      - Key
      - Value
      title: TagEntry
      type: object
    RulestackUntagResourceRequest:
      additionalProperties: false
      properties:
        TagKeys:
          items:
            maxLength: 128
            minLength: 1
            pattern: ^.*$
            type: string
          maxItems: 50
          title: Tagkeys
          type: array
      required:
      - TagKeys
      title: RulestackUntagResourceRequest
      type: object
    RulestackUntagResourceResponse:
      additionalProperties: false
      properties:
        Response:
          $ref: '#/components/schemas/RulestackUntagResourceResponse.ResponseData'
        ResponseStatus:
          $ref: '#/components/schemas/RulestackUntagResourceResponse.Result'
      title: RulestackUntagResourceResponse
      type: object
    RulestackUntagResourceResponse.ResponseData:
      additionalProperties: false
      properties:
        RuleStackName:
          title: Rulestackname
          type: string
        TagKeys:
          items:
            type: string
          title: Tagkeys
          type: array
      title: ResponseData
      type: object
    RulestackUntagResourceResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode:
          default: 0
          title: Errorcode
          type: integer
        Reason:
          title: Reason
          type: string
      title: Result
      type: object
info:
  contact: {}
  description: "Apply tags to help search and filter your rulestack resources.\n\n\
    ### Permission Policies\n\n| Action                         | Local Firewall Administrator\
    \  | Local Rulestack Administrator | Global Rulestack Administrator |\n| ------------------------------\
    \ | :---------------------------: | :---------------------------: | :----------------------------:\
    \ |\n| Tag Resource                   | **&#9745;**                   | **&#9745;**\
    \                   | **&#9745;**                    | \n| Untag Resource    \
    \             | **&#9745;**                   | **&#9745;**                  \
    \ | **&#9745;**                    |                      \n| List Firewall Tags\
    \             | &#9744;                       | **&#9745;**                  \
    \ | **&#9745;**                    |\n"
  title: Manage Rulestack Tags
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/config/rulestacks/{rulestackname}/tags:
    delete:
      description: 'Remove tags with specified keys from a specified resource.

        '
      operationId: delete-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RulestackUntagResourceRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RulestackUntagResourceResponse'
          description: OK
      summary: Remove tags with specified keys from a specified resource.
      tags:
      - ManageRulestackTags
    get:
      description: 'Retrieve the tags associated with a specified resource.

        '
      operationId: get-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      - description: ''
        in: query
        name: maxresults
        required: false
        schema:
          default: 1024
          maximum: 1024
          minimum: 1
          title: Maxresults
          type: integer
      - description: ''
        in: query
        name: nexttoken
        required: false
        schema:
          title: Nexttoken
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RulestackListTagsForResourceResponse'
          description: OK
      summary: Retrieve the tags associated with a specified resource.
      tags:
      - ManageRulestackTags
    post:
      description: 'Add tags to a specific resource. You can tag the AWS resources
        that you manage through rulestacks.

        '
      operationId: post-v1-config-rulestacks-rulestackname-tags
      parameters:
      - description: 'The name of the rulestack.

          '
        in: path
        name: rulestackname
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RulestackTagResourceRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RulestackTagResourceResponse'
          description: OK
      summary: Create Add tags to a specific resource. You can tag the AWS resources
        that you manage through rul...
      tags:
      - ManageRulestackTags
servers:
- url: https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com
tags:
- name: ManageRulestackTags
