components:
  schemas:
    DescribeLinkAccountRequest:
      additionalProperties: false
      properties: {}
      title: DescribeLinkAccountRequest
      type: object
    DescribeLinkAccountResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/DescribeLinkAccountResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/DescribeLinkAccountResponse.Result',
          description: 'The API call response status.

            '}
      title: DescribeLinkAccountResponse
      type: object
    DescribeLinkAccountResponse.AccountTableEntryStatus:
      description: An enumeration.
      enum: [Success, Pending, Deleting, OffBoarding, DeleteFailed]
      title: AccountTableEntryStatus
      type: string
    DescribeLinkAccountResponse.ResponseData:
      additionalProperties: false
      properties:
        AccountId: {description: 'The unique ID of the account.

            ', maxLength: 12, pattern: '^$|^[0-9]+$', title: Accountid, type: string}
        CloudFormationTemplateURL: {description: 'The CFT URL.

            ', title: Cloudformationtemplateurl, type: string}
        ExternalId: {description: 'A randomly generated UUID used to enable trust
            relationship in the role''s policy.

            ', title: Externalid, type: string}
        OnboardingStatus:
          allOf:
          - {$ref: '#/components/schemas/DescribeLinkAccountResponse.AccountTableEntryStatus'}
          default: Pending
          description: 'The status of account onboarding.

            '
        ServiceAccountId: {description: 'The unique ID of the dedicated service account.

            ', maxLength: 12, pattern: '^$|^[0-9]+$', title: Serviceaccountid, type: string}
        SnsTopicArn: {description: 'The SNS topic ARN.

            ', title: Snstopicarn, type: string}
      title: ResponseData
      type: object
    DescribeLinkAccountResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: 'The error description

            ', title: Reason, type: string}
      title: Result
      type: object
    ListLinkAccountsRequest:
      additionalProperties: false
      properties: {}
      title: ListLinkAccountsRequest
      type: object
    ListLinkAccountsResponse:
      additionalProperties: false
      properties:
        Response: {$ref: '#/components/schemas/ListLinkAccountsResponse.ResponseData',
          description: 'The API call response.

            '}
        ResponseStatus: {$ref: '#/components/schemas/ListLinkAccountsResponse.Result',
          description: 'The API call response status.

            '}
      title: ListLinkAccountsResponse
      type: object
    ListLinkAccountsResponse.ResponseData:
      additionalProperties: false
      properties:
        AccountIds:
          description: 'Account IDs list.

            '
          items: {maxLength: 12, pattern: '^$|^[0-9]+$', type: string}
          title: Accountids
          type: array
      title: ResponseData
      type: object
    ListLinkAccountsResponse.Result:
      additionalProperties: false
      properties:
        ErrorCode: {default: 0, description: "Default value of a successful response\
            \ is 0. Any other number indicates an error code.  \n\n400\u2014HTTP bad\
            \ request\n* InvalidOperationException\u2014Operation failed because it\
            \ is not valid. For example, when you delete an NGFW or rulestack in use.\n\
            * InvalidRequestException\u2014Operation failed due to invalid request.\
            \ For example, unsupported parameter name or value in the request.\n*\
            \ LimitExceededException\u2014Operation failed due to violation in limit\
            \ settings.\n* ResourceNotFoundException\u2014Unable to locate a resource\
            \ using the parameters you provided.\n* ThrottlingException\u2014Operation\
            \ failed due to throttling limitations.   \n\n500\u2014Bad request \n\
            * InternalServerError\u2014Your request is valid but Cloud NGFW could\
            \ not perform the operation due to a system issue.\n", title: Errorcode,
          type: integer}
        Reason: {description: 'The error description.

            ', title: Reason, type: string}
      title: Result
      type: object
info:
  contact: {}
  description: "Cloud NGFW requires you to onboard an AWS account to create and manage\
    \ the resources required by Cloud NGFW. The Cloud NGFW service uses a Cloud Formation\
    \ Template (CFT) stack to create these roles needed for Cloud NGFW to access resources\
    \ in your AWS environment.  \n\nA link account is an unverified account used to\
    \ onboard an AWS account to a cloud NGFW service based on your input. A link account\
    \ is required to run the CFT.  \n\n>**Note:** You can add only one link account\
    \ per subscription.\n"
  title: User Onboarding using Link Account
  version: 1.0.0
openapi: 3.0.3
paths:
  /v1/mgmt/linkaccounts:
    get:
      description: 'List all accounts linked with the an FMS account.

        '
      operationId: get-v1-mgmt-linkaccounts
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/ListLinkAccountsRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ListLinkAccountsResponse'}
          description: OK
      summary: List Link Accounts
      tags: [UserOnboarding-LinkAccounts]
  /v1/mgmt/linkaccounts/{accountid}:
    get:
      description: 'View the details of the account IDs associated with the FMS account.

        '
      operationId: get-v1-mgmt-linkaccounts-accountid
      parameters:
      - description: 'The unique ID of the account.

          '
        in: path
        name: accountid
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/DescribeLinkAccountRequest'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/DescribeLinkAccountResponse'}
          description: OK
      summary: Describe Link Account
      tags: [UserOnboarding-LinkAccounts]
servers:
- {url: 'https://api.us-east-1.aws.cloudngfw.paloaltonetworks.com'}
tags:
- {name: UserOnboarding-LinkAccounts}
