export const SPEC_URL = "/spec/prisma-browser-management.yaml";
// LLM-ready guide bundles, generated by scripts/prisma-browser/build-guide-index.mjs
// and served as static assets.
export const LLMS_FULL_URL = "/prisma-browser/llms-full.txt";
export const LLMS_TXT_URL = "/prisma-browser/llms.txt";
export const LLMS_DOWNLOAD_NAME = "prisma-browser-api-guide.md";
// Per-page Markdown files live at `${LLMS_PAGE_MD_BASE}/<slug>.md`, where <slug>
// is the last segment of the guide route (e.g. /prisma-browser/guide/authentication).
export const LLMS_PAGE_MD_BASE = "/prisma-browser/guide-md";
// Placeholder: the Prisma Browser Terraform provider is not published yet.
// Wire this up (and flip the `comingSoon` flags below) once it ships.
export const TERRAFORM_URL = "";
// The API reference has no standalone landing page, so entering the section
// defaults to the list-users endpoint. Tag that navigational entry with
// ?ref=nav so analytics can separate "entered the API section" from genuine
// interest in list-users (bookmarks, deep links, and sidebar clicks hit the
// untagged URL).
export const API_REF_URL = "/prisma-browser/api/list-users?ref=nav";

export const PORTAL_TABS = [
  { surface: "overview", label: "Overview", to: "/prisma-browser" },
  {
    surface: "guide",
    label: "Developer guide",
    to: "/prisma-browser/guide/guide-overview",
  },
  { surface: "api", label: "API reference", to: API_REF_URL },
  {
    surface: "release-notes",
    label: "Release notes",
    to: "/prisma-browser/release-notes",
  },
  {
    surface: "terraform",
    label: "Terraform",
    // Provider not yet published; keep the tab visible but disabled.
    comingSoon: true,
  },
];

export const OVERVIEW_CONTENT = {
  title: "Prisma Browser Developer Docs",
  description:
    "Automate Prisma Browser with the Management API: policy, controls, applications, users, groups, devices, and safe configuration rollout over REST.",
  hero: {
    heading: "Automate Your Prisma Browser Configuration",
    subheading:
      "One REST API to manage and safely roll out everything you configure in the Prisma Browser console.",
    actions: [
      {
        label: "Read the guide",
        to: "/prisma-browser/guide/getting-started",
        variant: "primary",
      },
      {
        label: "Browse the API reference",
        to: API_REF_URL,
        variant: "ghost",
      },
    ],
  },
  useCasesTitle:
    "Unlock new use cases and scale your Prisma Browser automation",
  useCasesLede:
    "From just-in-time access to policy as code, automate the workflows that matter most.",
  useCases: [
    {
      title: "Just-in-time access control",
      body: "Grant time-boxed access from your internal ticketing system (ServiceNow and others) by approving requests through the API.",
      icon: "fa-user-clock",
      to: "/prisma-browser/guide/handle-user-access-requests",
    },
    {
      title: "Manage allow / block URLs",
      body: "Keep allow and block URL lists in sync with an external source of truth.",
      icon: "fa-list-check",
      to: "/prisma-browser/guide/manage-allow-block-list",
    },
    {
      title: "Policy as code",
      body: "Author, version, and publish policy rules from your own pipeline, no console clicks.",
      icon: "fa-code-branch",
      to: "/prisma-browser/guide/create-and-publish-a-security-rule",
    },
    {
      title: "Manage allowed extensions",
      body: "Curate the allowed browser extension list on a rule straight from your tooling.",
      icon: "fa-puzzle-piece",
      to: "/prisma-browser/guide/manage-allowed-extensions",
    },
    {
      title: "Automated remediation",
      body: "Suspend a user or quarantine a device in one call inside an incident-response flow.",
      icon: "fa-shield-halved",
      to: "/prisma-browser/guide/suspend-a-compromised-user",
    },
    {
      title: "Credential hygiene",
      body: "Rotate Google Cloud Storage keys on a schedule with no downtime.",
      icon: "fa-key",
      to: "/prisma-browser/guide/rotate-cloud-storage-credentials",
    },
    {
      title: "Gradual rollout",
      body: "Expand a rule's scope batch by batch to release changes in controlled waves.",
      icon: "fa-arrow-trend-up",
      to: "/prisma-browser/guide/gradual-rollout-with-user-group",
    },
  ],
  cards: [
    {
      title: "Developer guide",
      body: "Learn the concepts, building blocks, and copy-paste use cases for automating Prisma Browser.",
      to: "/prisma-browser/guide/guide-overview",
    },
    {
      title: "REST API reference",
      body: "Review every endpoint, parameter, and schema available for the Prisma Browser Management API.",
      to: API_REF_URL,
    },
    {
      title: "Release notes",
      body: "Track every change to the Prisma Browser public API, and subscribe to stay up to date.",
      to: "/prisma-browser/release-notes",
    },
    {
      title: "Terraform Provider",
      // Provider not yet published; render the card disabled with a badge.
      comingSoon: true,
      body: "Manage your Prisma Browser configuration as code with the Prisma Browser Terraform provider.",
    },
  ],
};

export const RELEASE_NOTES_CONTENT = {
  title: "Release notes",
  description:
    "Every customer-facing change to the Prisma Browser Management API, with before/after diffs and links to the affected endpoint.",
  heading: "Release notes",
  lead: "Everything we ship for the Prisma Browser Management API, newest first. Pick a date to see exactly what changed, including breaking changes, what you need to do, and links to the affected endpoints.",
};
