name: Deploy Preview

on:
  workflow_run:
    workflows: [CodeQL]
    types:
      - completed

jobs:
  build_and_preview:
    name: Build and Preview
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: codeql-analysis.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: pr_num
        run: echo ::set-output name=content::$(cat ./pr_num/pr_num.txt)
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build site
        run: yarn install && yarn run build

      - name: Deploy to Firebase
        id: deploy_preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAN_DEV_F1B58 }}'
          projectId: pan-dev-f1b58
          channelId: 'pr${{ steps.pr_num.outputs.content }}'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          
      - name: 'Comment PR'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ steps.pr_num.outputs.content }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔥 Deploy Preview URL: ${{ steps.deploy_preview.outputs.details_url }} \n\n🦝 Deploy Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
    environment:
      name: build
      url: ${{ steps.deploy_preview.outputs.details_url }}
