name: Deploy

on:
  workflow_run:
    workflows:
      - Analyze
    types:
      - completed

jobs:
  build_and_preview:
    name: Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Build site  
        run: yarn install && yarn run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAN_DEV_F1B58 }}'
          projectId: pan-dev-f1b58
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
    environment:
          name: build
